### PR TITLE
Honor auto_pad attribute in ConvTranspose 

### LINKED ISSUE #4086: ConvTranspose auto_pad=SAME_UPPER/SAME_LOWER not working properly
**Describe the bug**
Using ConvTranspose with auto_pad=SAME_UPPER. Program below prints output shape as `(1, 1, 4, 4)` which is different than the input shape. Should have been the same shape.
But also, node is created with the correct shape` (1,1,2,2) `and the checker passed. The actual output values indicate auto_pad=VALID is likely used internally.

**Urgency**
None

**System information**
Windows 10
ONNX Runtime installed from binary:
ONNX Runtime version: 1.3.0
Python version:  3.5.6
CUDA/cuDNN version: None

**To Reproduce**
```
from onnx import helper, checker, AttributeProto, TensorProto, GraphProto
import onnxruntime as rt
import numpy as np

X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 1, 2, 2])
W = helper.make_tensor_value_info('W', TensorProto.FLOAT, [1, 1, 3, 3])
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, 1, 2, 2])
node_def = helper.make_node("ConvTranspose", ["X", "W"], ["Y"], auto_pad="SAME_UPPER", strides=[1, 1])
graph_def = helper.make_graph([node_def], 'deconv-model', [X, W], [Y])
model_def = helper.make_model(graph_def, producer_name='')

checker.check_model(model_def)
with open("deconv.onnx", "wb") as f:
    f.write(model_def.SerializeToString())

sess = rt.InferenceSession("deconv.onnx")

X = np.arange(2, 6, 1).reshape(1, 1, 2, 2)
W = np.arange(2, 11, 1).reshape(1, 1, 3, 3)

onnx_pred = sess.run(["Y"], {"X": X.astype(np.float32), "W": W.astype(np.float32)})[0]
print(onnx_pred.shape)
```
**Expected behavior**
should print `(1, 1, 2, 2)`, prints` (1, 1, 4, 4)`

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: Honor auto_pad attributes (if set) in ConvTranspose 

**Motivation and Context**
Resolve #4086

### CODE REVIEW

File: onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc [hunk 1]
```diff
@@ -56,8 +63,80 @@ void TestConvTransposeOp(const ConvTransposeOpAttributes& attributes,
 
   test.Run(expect_result, err_str, excluded_provider_types);  // Disable TensorRT because weight as input is not supported
 }
+
 }  // namespace
 
+TEST(ConvTransposeTest, ConvTranspose_1D_AsymmetricPads) {
```
Comment (hariharans29) [inline onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc:69]: Builds are failing on account of the added tests as something in the CPU implementation is unable to handle asymmetric padding correctly (CUDA by definition can't handle asymmetric padding). Need to fix this issue before these tests will pass.

File: onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc [hunk 2]
```diff
@@ -56,8 +63,81 @@ void TestConvTransposeOp(const ConvTransposeOpAttributes& attributes,
...
```
Comment (hariharans29) [inline onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc:69]: There are 3 new tests associated with this change starting here. The rest are just formatting changes.

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h [hunk 3]
```diff
@@ -177,40 +184,47 @@ struct ConvTransposeAttributes : public ConvAttributes {
...
+      if (pad_type == AutoPadType::SAME_UPPER) {  // pad more on head when total_pad is odd.
+        *pad_head = total_pad - total_pad / 2;
+        *pad_tail = total_pad / 2;
+      } else {
+        // for pad_type is NOTSET, SAME_LOWER or VALID
+        // set pad_head as total_pad/2, pad_tail as total_pad-total_pad/2.
+        // That said, we pad more on tail when total_pad is odd.
+        *pad_head = total_pad / 2;
+        *pad_tail = total_pad - total_pad / 2;
       }
```
Comment (jcwchen) [inline onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:223]: Could we merge line 193 to line 202 and line 214 to line 223 with the same code?

**Comment by jiafatom** [comment]
A little confused about the logic: `ComputeTotalPad` considers `strides` there, then the output shape should also consider `strides`. Why output shape is the same as input shape at the end? Can we have a unit test that has `stride > 1`?

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h (hunk 3 above)
Comment (hariharans29) [reply onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:223]: sure - seems reasonable, I ll do that.

Comment (hariharans29) [reply onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h]: Fixed

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc [hunk 4]
```diff
@@ -1830,6 +1831,24 @@ static bool ConvTransposeNeedFallbackToCPU(const onnxruntime::Node& node) {
...
+                  "auto_pad must be either NOTSET, VALID, SAME_UPPER, SAME_LOWER");
+
+      // If auto_pad is SAME_UPPER or SAME_LOWER, pads will be computed dynamically at runtime
+      // based on the provided input shape. This may or may not lead to symmetric padding.
+      // If it turns out to be asymmetric padding, CuDNN will return a cryptic unfriendly error message.
+      // So drop down the node to CPU if auto_pad is SAME_UPPER or SAME_LOWER even if it may lead to
+      // symmetric padding.
+      // TODO: Remove this after we have supported asymmetric padding in the CUDA ConvTranspose kernel
+      if (auto_pad_attr == "SAME_UPPER" || auto_pad_attr == "SAME_LOWER") {
+        return true;
```
Comment (hariharans29) [inline onnxruntime/core/providers/cuda/cuda_execution_provider.cc:1849]: Drop down the ConvTranspose node to CPU if the auto_pad attribute is in play - because the dynamically computed pads may or may not be symmetric - it is better to be safe than sorry. This shouldn't cause perf regression in shipped prod models as auto_pad was never supported in ConvTranspose previously.

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h [hunk 5]
```diff
@@ -177,40 +198,28 @@ struct ConvTransposeAttributes : public ConvAttributes {
...
-    } else {
-      *out_size =
-          (in_size - 1) * stride + adj + (kernel - 1) * dilation + 1 - *pad_head - *pad_tail;
+
+    // Output shape is not provided - it needs to be computed along with pad values (if applicable)
+
+    // Compute padding if the auto_pad attribute is SAME_UPPER/SAME_LOWER
+    if (pad_type == AutoPadType::SAME_UPPER || pad_type == AutoPadType::SAME_LOWER) {
+      // total pad
+      int64_t total_pad = ComputeTotalPad(in_size, stride, adj,
```
Comment (jiafatom) [inline onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:216]: auto

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h [hunk 6]
```diff
@@ -177,40 +198,28 @@ struct ConvTransposeAttributes : public ConvAttributes {
...
-        *pad_tail = paddings / 2;
-      } else {
-        // for pad_type is NOTSET, SAME_LOWER or VALID
-        // set pad_head as paddings/2, pad_tail as paddings-paddings/2.
-        // That said, we pad more on tail when paddings are odd.
-        *pad_head = paddings / 2;
-        *pad_tail = paddings - paddings / 2;
-      }
+      // total pad
+      int64_t total_pad = ComputeTotalPad(in_size, stride, adj,
```
Comment (jiafatom) [inline onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:205]: auto

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h [hunk 7]
```diff
@@ -167,6 +167,27 @@ struct ConvTransposeAttributes : public ConvAttributes {
   const std::vector<int64_t> output_shape;
 
  private:
+  int64_t ComputeTotalPad(int64_t in_size, int64_t stride, int64_t adj,
+                          int64_t kernel, int64_t dilation, int64_t out_size) const {
+    int64_t total_pad =
```
Comment (jiafatom) [inline onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:172]: `return std::max<int64_t>(0, (in_size - 1) * stride + adj + (kernel - 1) * dilation + 1 - out_size);` ?

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h [hunk 8]
```diff
@@ -167,6 +167,27 @@ struct ConvTransposeAttributes : public ConvAttributes {
...
+  void DistributePadding(AutoPadType pad_type, const int64_t& total_pad,
+                         int64_t& pad_head, int64_t& pad_tail) const {
+    if (pad_type == AutoPadType::SAME_UPPER) {  // pad more on head when total_pad is odd.
+      pad_head = total_pad - total_pad / 2;
+      pad_tail = total_pad / 2;
+    } else {
+      // for pad_type is NOTSET, SAME_LOWER or VALID
+      // set pad_head as total_pad/2, pad_tail as total_pad-total_pad/2.
+      // That said, we pad more on tail when total_pad is odd.
+      pad_head = total_pad / 2;
```
Comment (jiafatom) [inline onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:186]: Make sure the logic for NOTSET, SAME_LOWER or VALID are same here.

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h (hunk 7 above)
Comment (hariharans29) [reply onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:172]: sure, fixed

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h (hunk 8 above)
Comment (hariharans29) [reply onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h:186]: This has always been as is- I guess only "SAME_UPPER" is special in the way it does the distribution. "SAME_LOWER " is the default way to distribute the padding. So, I guess this is okay.

**Review by jiafatom — DISMISSED** [review]
mainly checked the logic part, LGTM.

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc [hunk 9]
```diff
@@ -1830,6 +1831,24 @@ static bool ConvTransposeNeedFallbackToCPU(const onnxruntime::Node& node) {
...
+                      auto_pad_attr == "VALID" || auto_pad_attr == "NOTSET",
+                  "auto_pad must be either NOTSET, VALID, SAME_UPPER, SAME_LOWER");
+
+      // If auto_pad is SAME_UPPER or SAME_LOWER, pads will be computed dynamically at runtime
+      // based on the provided input shape. This may or may not lead to symmetric padding.
+      // If it turns out to be asymmetric padding, CuDNN will return a cryptic unfriendly error message.
+      // So drop down the node to CPU if auto_pad is SAME_UPPER or SAME_LOWER even if it may lead to
+      // symmetric padding.
+      // TODO: Remove this after we have supported asymmetric padding in the CUDA ConvTranspose kernel
+      if (auto_pad_attr == "SAME_UPPER" || auto_pad_attr == "SAME_LOWER") {
```
Comment (pranavsharma) [inline onnxruntime/core/providers/cuda/cuda_execution_provider.cc:1848]: Can we log something saying why the fallback is taking place to CPU (unless it's not logged anywhere else)?

Comment (hariharans29) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:1848]: Good catch - I actually meant to do that at the time of writing the "if", but it seems like I have forgotten. Let me add the logs, thanks.

Comment (hariharans29) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:1848]: It should be logged somewhere else that the node is falling back - but it may be meaningful to add a more informative log saying why this node is falling back.

Comment (pranavsharma) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:1848]: Yeah, the layer that logs above this will lose the reason making users wonder.

Comment (hariharans29) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:1851]: Added logs

**Review by pranavsharma — APPROVED** [review]
