### PR TITLE
[ARM CPU] Fix fp16 const initialization on no-fp16 platform

### LINKED ISSUE #23957: Illegal instruction when importing onnxruntime
### Describe the issue

In a fresh Raspberry PI OS Bookworm 64 bits install on a Raspberry PI 4, after installing onnxruntime using pip in a VirtualEnvironment, when importing it, i get:

```
(artStyle) pi@artsyStyle:~/artStyle $ python
Python 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
Illegal instruction
```

Here's the system specs:

Raspberry PI OS:
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

Python Version:
```
python -V
Python 3.11.2
```

ONNX Runtime version installed by pip:

`onnxruntime-1.21.0-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl`

### To reproduce

- Fresh Install Raspberry PI OS Bookworm 64 bits
- Create a virtual environment with pip
- Install onnxruntime
- try to import it. 

### Urgency

I'm not saying it's urgent, but it's definitely an issue. Raspberry PIs are used at the edge all the time. 

### Platform

Linux

### OS Version

Debian GNU/Linux 12 (bookworm)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-1.21.0-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

### Execution Provider Library Version

_No response_

### PR DESCRIPTION
**Pull request by fajin-corp**
### Description
Fix fp16 const initialization on no-fp16 platform [such as Raspberry PI](https://github.com/microsoft/onnxruntime/issues/23957)

### Motivation and Context
Resolve #23957

### CODE REVIEW

**Review by snnn — DISMISSED** [review]

**Review by amarin16 — APPROVED** [review]

File: onnxruntime/core/mlas/lib/softmax_kernel_neon_fp16.cpp [hunk 1]
```diff
@@ -432,45 +429,43 @@ const MlasTanhConstants<_mlas_fp16_> TanhConstantsFp16 = {
...
-    MlasBroadcastFloat16x4(TanhConstantsFp16.beta_0),
-};
-
 template <typename T>
 MLAS_FORCEINLINE
 MlasTanhConstants<T> Get_Tanh_Constants();
 
 template <>
 MLAS_FORCEINLINE
 MlasTanhConstants<float16x8_t> Get_Tanh_Constants<float16x8_t>() {
```
Comment (yihonglyu) [inline onnxruntime/core/mlas/lib/softmax_kernel_neon_fp16.cpp:438]: How about using
```
const MlasTanhConstants<float16x8_t>& Get_Tanh_Constants<float16x8_t>() {
...
}
```

File: onnxruntime/core/mlas/lib/softmax_kernel_neon_fp16.cpp [hunk 2]
```diff
@@ -64,59 +63,57 @@ const MlasExpConstants<_mlas_fp16_> ExpConstantsFp16 = {
...
-
 template <typename T>
 MLAS_FORCEINLINE
-MlasExpConstants<T> Get_Exp_Constants();
+const MlasExpConstants<T>& Get_Exp_Constants();
 
 template <>
 MLAS_FORCEINLINE
-MlasExpConstants<float16x8_t> Get_Exp_Constants<float16x8_t>() {
+const MlasExpConstants<float16x8_t>& Get_Exp_Constants<float16x8_t>() {
```
Comment (yihonglyu) [inline onnxruntime/core/mlas/lib/softmax_kernel_neon_fp16.cpp:72]: Should the use of Get_Exp_Constants be changed to something like this to avoid copying?
```
const auto& constants = Get_Exp_Constants<T>();
```

Comment (fajin-corp) [reply onnxruntime/core/mlas/lib/softmax_kernel_neon_fp16.cpp:72]: auto includes the case of auto* and auto&

Comment (edgchen1) [reply onnxruntime/core/mlas/lib/softmax_kernel_neon_fp16.cpp:72]: I believe @yihonglyu is right - I think in this case `auto` will be deduced to `MlasExpConstants<float16x8_t>`.

https://godbolt.org/z/vejxa8nPd

**Review by edgchen1 — APPROVED** [review]

**Review by yihonglyu — APPROVED** [review]
LGTM, thanks!

**Comment by snnn** [comment]
This PR has been cherry-picked into the `rel-1.21.1` branch in PR #24188. Removing the `release:1.21.1` label.
