### PR TITLE
Fix a bug in ReluClip fusion

### LINKED ISSUE #9753: Crashes when relu is followed by a clip
**Describe the bug**
On opset version 11, when relu is followed by a clip (`clip(relu(x),-1,1)`), ORT raises segmentation fault.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9.0
- Python version: 3.7.11
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 11.1/8.0.5
- GPU model and memory: RTX2080, 8GB
- PyTorch version: 1.10.0

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```python
import torch
import onnx
import onnxruntime as ort


class Model(torch.nn.Module):
    @torch.no_grad()
    def forward(self, x):
        x = torch.relu(x)  # can run succesfully if comment out this line
        x = torch.clip(x, -1, 1)
        return x


model = Model()
inputs = (torch.randn(1, 1, 1, 1),)
output_names = ["output"]
torch.onnx.export(model, inputs, "1.onnx", verbose=False,
                  input_names=["input"], output_names=output_names, opset_version=11)

onnx_model = onnx.load("1.onnx")
sess = ort.InferenceSession(
    onnx._serialize(onnx_model))
res = sess.run(output_names, {"input": inputs[0].numpy()})
```
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
Attached file: [1.onnx.zip](https://github.com/microsoft/onnxruntime/files/7531442/1.onnx.zip)

Plain text proto:
```proto
ir_version: 7
producer_name: "pytorch"
producer_version: "1.10"
graph {
  node {
    input: "input"
    output: "1"
    name: "Relu_0"
    op_type: "Relu"
  }
  node {
    input: "1"
    input: "7"
    input: "8"
    output: "output"
    name: "Clip_1"
    op_type: "Clip"
  }
  name: "torch-jit-export"
  initializer {
    data_type: 1
    name: "7"
    raw_data: "\000\000\200\277"
  }
  initializer {
    data_type: 1
    name: "8"
    raw_data: "\000\000\200?"
  }
  input {
    name: "input"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  output {
    name: "output"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
}
opset_import {
  version: 11
}
```

**Expected behavior**
Should not crash, but got segmentation fault.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: 

`Graph::AddInitializedTensor()` doesn't create a NodeArg for the TensorProto if the graph is loaded from a model file (even if it doesn't exist in the graph).
 
See here-
https://github.com/microsoft/onnxruntime/blob/ac57afc3a69dfc6a57caeee678966a1fce50bca9/onnxruntime/core/graph/graph.cc#L2790

The call to `AddInitializedTensor()` from the ReluClip fusion optimizer breaks the OP's model in #9753 because the graph is loaded from a model file and hence the initialized tensor added to the graph is left without a corresponding NodeArg by the logic pasted above.
 
The test added in https://github.com/microsoft/onnxruntime/pull/2059/ does emulate the model but the NodeArg does end up getting created in that instance as the graph is not loaded from a model file.

**Motivation and Context**
Resolve #9753

### CODE REVIEW

File: include/onnxruntime/core/graph/graph.h [hunk 1]
```diff
@@ -636,8 +636,12 @@ class Graph {
...
 
 #if !defined(ORT_MINIMAL_BUILD) || defined(ORT_EXTENDED_MINIMAL_BUILD)
-  /** Add an initializer tensor to the Graph. */
-  void AddInitializedTensor(const ONNX_NAMESPACE::TensorProto& tensor_proto);
+  /** Add an initializer tensor to the Graph. 
+    @param force_nodearg_creation If true creates a corresponding NodeArg for the initialized tensor.
+    If false, a NodeArg is created ONLY if the graph is not loaded from a model file and a NodeArg
+    with the same name as the initialized tensor_proto does not exist.
+  */
+  void AddInitializedTensor(const ONNX_NAMESPACE::TensorProto& tensor_proto, bool force_nodearg_creation = false);
```
Comment (pranavsharma) [inline include/onnxruntime/core/graph/graph.h:644]: When would clients of this class want to force the creation of node arg? In other words, under what circumstances should I set this to true?

Comment (hariharans29) [reply include/onnxruntime/core/graph/graph.h:644]: Well clients need to ensure that a NodeArg exists for an initialized tensor that is getting added to the graph. Either, they do a `GetOrCreateNodeArg()` on the client side along with `AddInitializedTensor()` or they do a `AddInitializedTensor(..., true)` and force the initializer addition logic to create a NodeArg (if it doesn't already exist). This new interface is just exposing a new way to keep client side code a bit more concise. 

Some optimizers are lucky enough to avoid creating a NodeArg altogether for an initialized tensor because they will use a name for the initializer that already exists in the graph - for example, Constant Folding, where the name of the initializer is the same as the output of a node getting folded in which case a separate NodeArg creation step is not required.

Comment (yuslepukhin) [reply include/onnxruntime/core/graph/graph.h:644]: I am curious why this was specifically NOT created in the first place? This change may be circumventing some prior logic. The PR description does not address it.

Comment (hariharans29) [reply include/onnxruntime/core/graph/graph.h:644]: NOT creating it in the first place is the oversight/bug that this PR is solving :)

Perhaps you can elaborate on what you think the PR may be circumventing ? I thought the PR description was clear enough but I am happy to improve the description if you have something more specific.

FWIW - I spoke to the original implementer of this fusion @skottmckay and we did agree that this was a bug and he was the one who recommended this interface change in `AddInitializedTensor()`. In my original fix, I had the client-side optimizer create the NodeArg (as opposed to having `AddInitializedTensor()` create the NodeArg).

Comment (pranavsharma) [reply include/onnxruntime/core/graph/graph.h:644]: Should clients be relieved from the responsibility of setting this boolean? Can AddInitializedTensor take this decision on behalf of the clients just like how it's taking a decision based on is_loaded_from_model_file_?

Comment (hariharans29) [reply include/onnxruntime/core/graph/graph.h:644]: Not sure if it can/supposed to take such a decision. 

The clients can never truly be "relieved" of this responsibility (they never were / they never are going to be). The client needs to make sure that the corresponding NodeArg exists. Even in existing optimizers, there is a call to GetOrCreateNodeArg() where applicable. This is exactly the same but via a boolean flag.

Comment (pranavsharma) [reply include/onnxruntime/core/graph/graph.h:644]: The semantics of the function seem a bit inconsistent. In one case it takes the decision on behalf of the client and in other cases it expects the client to tell it explicitly to create the NodeArg. AddInitializedTensor should either assume that the NodeArg is created or create it if not present. I don't think there's any use case of calling AddInitializedTensor where you wouldn't create a NodeArg for it. We can take this offline.

Comment (hariharans29) [reply include/onnxruntime/core/graph/graph.h:644]: Spoke offline. Will remove the change to AddInitializedTensor(). Will keep all the changes local to the optimizer.

**Review by pranavsharma — APPROVED** [review]
