### PR TITLE
Fix a buffer reuse bug in allocation_planner.cc

### LINKED ISSUE #7633: EfficientDet fails on parallel executor
**Describe the bug**
The efficientdet model succeeds using the sequential executor but fails with the parallel executor.  Likely one of the kernels is not thread safe.  Run the provided script to reproduce.  Fails in onnxruntime 1.7.0 and latest ort nightly.

**To Reproduce**
https://microsoft-my.sharepoint-df.com/:u:/p/tomwi/EWmjsREtb21PjAPlkMtcSgYBv94X-sebK1UwDRQHrlMp7Q?e=c9OoR0

Crashes with error:
```
RUNTIME_EXCEPTION : Non-zero status code returned while running Pad node. Name:'StatefulPartitionedCall/Preprocessor/ResizeToRange/Pad' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\op_kernel.cc:76 onnxruntime::OpKernelContext::OutputMLValue status.IsOK() was false. 
Tensor shape cannot contain any negative value
```

**Urgency**
Having efficientdet ORT perf beat TF would help with OKR progress.

### PR DESCRIPTION
**Pull request by snnn**
**Description**: 

Fix a buffer reuse bug in allocation_planner.cc

Resolve #7633

I will add the model to our model tests.

**Motivation and Context**
- Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here.

### CODE REVIEW

**Review by SherlockNoMad — DISMISSED** [review]
is there a real model using parallel executor?

File: onnxruntime/core/framework/allocation_planner.cc [hunk 1]
```diff
@@ -731,7 +731,7 @@ class PlannerImpl {
           // we do not try sharing-optimization for non-tensors
           AllocPlan(current).alloc_kind = AllocKind::kAllocate;
           AllocPlan(current).program_counter.AddStart(program_counter);
-        } else if (FindReusableInput(*pnode, static_cast<int>(output_arg_def_index), &reused)) {
+        } else if (!context_.IsParallelExecutionEnabled() && FindReusableInput(*pnode, static_cast<int>(output_arg_def_index), &reused)) {
           // Reuse one of this node's input buffers as the output buffer (for in-place update)
```
Comment (skottmckay) [inline onnxruntime/core/framework/allocation_planner.cc:735]: Can we instead change FindReusableInput to look at the edges for the input it's considering re-using and require there to be only one if parallel execution is enabled?

Comment (snnn) [reply onnxruntime/core/framework/allocation_planner.cc:735]: Do you know why it works in sequential mode?

Comment (snnn) [reply onnxruntime/core/framework/allocation_planner.cc:735]: I read the code again. It is good in sequential mode because the planner tracks use count. And when ever a reuse happens, it will increase the use count. But all such things based on an assumption that the graph will be executed in topological sort order. For example, the parent loop of the line 733 iterates all the nodes in topological sort order. It doesn't make sense for parallel execution.  Even through we can do some improvements here, I feel it's not worth. We need to change the logic to track edge count instead of tracking usage count till current program_counter. I think we should create a new planner class instead.

**Review by skottmckay — APPROVED** [review]
:shipit:
