### PR TITLE
Fix MatMulScaleFusion handling of scales with leading dimensions.

### LINKED ISSUE #24407: Incompatible dimensions for matrix multiplication due to ORT_ENABLE_ALL
### Describe the issue

When using ORT_ENABLE_ALL to optimize the onnx model, the following error occurs.
```c
Traceback (most recent call last):
  File "/home/carla/Documents/test_onnxruntime/0414/onnx_output97016/test.py", line 17, in <module>
    ort_session = onnxruntime.InferenceSession(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carla/anaconda3/envs/nnsmith-onnxruntime/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/carla/anaconda3/envs/nnsmith-onnxruntime/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 544, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (/MatMul/MatMulScaleFusion/) Op (FusedMatMul) [ShapeInferenceError] Incompatible dimensions for matrix multiplication

```

This bug is similar to  [#11846](https://github.com/microsoft/onnxruntime/issues/11846), but this issue provides testcase.

### To reproduce

Environment
OS: Ubuntu 20.04
onnxruntime: 1.22.0.dev20250402004

Steps to reproduce
This bug can be reproduced by the following code with the model in the attachment. However, if we replace ORT_ENABLE_ALL with ORT_ENABLE_BASIC, every thing is ok.

```python
import onnx
import onnxruntime


onnx_model = onnx.load("model.onnx")

sess_options = onnxruntime.SessionOptions()              
sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL

ort_session = onnxruntime.InferenceSession(
                 onnx_model.SerializeToString(), sess_options, providers=["CPUExecutionProvider"]
              )
```

[model.zip](https://github.com/user-attachments/files/19730830/model.zip)

### Urgency

_No response_

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.22.0.dev20250402004

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

_No response_

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

Fix MatMulScaleFusion handling of scales with leading dimensions. The previous approach accepted a Mul/Div with a scale that broadcasted additional leading dimensions to its output shape. This caused a shape mismatch in the fused replacement.

### Motivation and Context

Fix #24407.

### CODE REVIEW

File: onnxruntime/core/optimizer/matmul_scale_fusion.cc [hunk 1]
```diff
@@ -26,20 +26,36 @@ struct ExtractScalarAsFloatDispatchTarget {
...
 };
 
-std::optional<float> GetScalarConstantInitializer(const Graph& graph, const NodeArg& node_arg) {
+std::optional<TensorShape> GetTensorShape(const NodeArg& node_arg) {
+  const auto* shape_proto = node_arg.Shape();
+  if (!shape_proto) {
+    return std::nullopt;
+  }
+
+  const auto shape = utils::GetTensorShapeFromTensorShapeProto(*shape_proto);
```
Comment (yuslepukhin) [inline onnxruntime/core/optimizer/matmul_scale_fusion.cc:35]: nit: simply return

**Review by yuslepukhin — APPROVED** [review]

**Review by yuslepukhin — APPROVED** [review]
