### PR TITLE
Fix CUDA Reduce ops

### LINKED ISSUE #2247: ReduceMin/ReduceMax do not reduce axes on Cuda provider
**Describe the bug**
When using the Reduce operators (e.g. ReduceMin) with no axes sepcified, and keep_dims==0, the dimensions of the input tensor are not reduced when running via the Cuda provider.  If the exact same Onnx model is used with the CPU provider, the axes are reduced as expected.

**Urgency**
A workaround is possible: instead of 
`m = data.min()`
you can write
`m, _ = data.view(-1).min(dim = 0, keepdim = True)`

**System information**
- OS Platform and Distribution: Windows 7 x64
- ONNX Runtime installed from: NuGet (C#)
- ONNX Runtime version: 0.5.0, 0.5.1
- Python version: 3.7
- Visual Studio version (if applicable): 2019 (16.3.1)
- CUDA/cuDNN version: 10.0
- GPU model and memory: RTX 2080 Ti

**To Reproduce**
* Create a pytorch model that uses the .min() operator on a tensor with more than one dimension
`data = torch.randn(2, 2)
data_min = data.min()`
* Export the model to onnx, import in OnnxRuntime for C#
* Run the model via CPU e.g.
`new InferenceSession(pathToOnnxFile, SessionOptions.Default);`
* Check the output is a single scalar tensor.
* Run the model via GPU e.g.
`new InferenceSession(pathToOnnxFile, SessionOptions.MakeSessionOptionWithCudaProvider());`
* The output has the same dimensions as the input

**Expected behavior**
The results should be the same for both providers; and the number of dimensions should be reduced.

**Additional context**
I'm not a CUDA programmer, but looking at the code in https://github.com/microsoft/onnxruntime/blob/90858b732a1d27657fc1424c91ccbfdf46082437/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc#L91 it seems the reduced dimensions are correctly calculated from *output_dims* and stored in *squeezed_output_dims*, but then later, these reduced dimensions are ignored when creating the output tensor https://github.com/microsoft/onnxruntime/blob/90858b732a1d27657fc1424c91ccbfdf46082437/onnxruntime/core/providers/cuda/reduction/reduction_ops.cc#L109

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: CUDA Reduce ops are unable to handle the case where all axes were being reduced upon and keepdims = false. Instead of producing a scalar which is the correct output shape, they were producing incorrect results  

**Motivation and Context**
Fix #2247

### CODE REVIEW

File: onnxruntime/core/providers/cuda/reduction/reduction_ops.cc [hunk 1]
```diff
@@ -99,12 +101,18 @@ Status ReduceKernel<allow_multi_axes>::ComputeImpl(OpKernelContext* ctx, cudnnRe
...
-  } else {
+  } else if (axes_.size() > 0) {
+    // we are not going to keep the reduced dims, hence compute the final output dim accordingly
+    squeezed_output_dims.reserve(rank);  // even though we won't use the full capacity, it is better to reserve for peak possible usage
     for (size_t i = 0; i < rank; ++i) {
       if (!reduced[i])
         squeezed_output_dims.push_back(input_dims[i]);
     }
+  } else {
+    // 'axes' is empty and keepdims is false => we reduce on all axes AND drop all dims,
```
Comment (hariharans29) [inline onnxruntime/core/providers/cuda/reduction/reduction_ops.cc]: we already validate to make sure the input is non-empty in line 94 because we can't have an empty input and reduce on all dims while dropping all the dims to produce a scalar. But if we have reached this line of execution, we have already validated to make sure the input is non-empty...

File: onnxruntime/core/providers/cuda/reduction/reduction_ops.cc [hunk 2]
```diff
@@ -263,7 +271,7 @@ Status ReduceKernel<allow_multi_axes>::ComputeImpl(OpKernelContext* ctx, cudnnRe
   }
 
   return Status::OK();
-}
+}  // namespace cuda
```
Comment (skottmckay) [inline onnxruntime/core/providers/cuda/reduction/reduction_ops.cc]: I don't think this was intended

Comment (hariharans29) [reply onnxruntime/core/providers/cuda/reduction/reduction_ops.cc]: you're right. I ll fix it, thanks.
