### PR TITLE
Use manylinux2010 image to build linux python wheels

### LINKED ISSUE #1001: Need CentOS support
**Describe the bug**
I would like to be able to use onnxruntime on CentOS 7.6. I can pip install onnxruntime 0.4.0 on CentOS 7.6 fine. But when I try to "import onnxruntime" using python 3.6.3 it fails:
```
/opt/app-root/lib/python3.6/site-packages/onnxruntime/capi/_pybind_state.py:12: UserWarning: Cannot load onnxruntime.capi. Error: '/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/app-root/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so)'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/app-root/lib/python3.6/site-packages/onnxruntime/__init__.py", line 21, in <module>
    from onnxruntime.capi._pybind_state import RunOptions, SessionOptions, get_device, NodeArg, ModelMetadata
ImportError: cannot import name 'RunOptions'
```
This almost certainly fails for other supported (>=3.5) versions of python though I haven't tried any other versions.

The output of `strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX` is:
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
From https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html it appears that onnxruntime is built with gcc 4.9 on Ubuntu but CentOS 7.6 only has gcc 4.8. And this appears to be the root of the problem.

**System information**

- OS Platform and Distribution: centos/python-36-centos7:1 from DockerHub (7.6)
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.4.0
- Python version: 3.6

**Discussion**
I wanted to open this as an issue to hopefully spark some discussion and/or see if CentOS support is something that is being worked on by anybody.

Does anybody know if onnxruntime can be built with gcc 4.8? Or if there are components in the onnxruntime build tool chain that absolutely requires gcc 4.9?

### PR DESCRIPTION
**Pull request by mayeut**
**Description**: Use manylinux2010 docker image to build linux python wheels.

**Motivation and Context**
- Why is this change required? What problem does it solve?
Before this change, linux wheels were built on Ubuntu 16.04 and were renamed manylinux1 wheels in order to be uploaded to PyPI. However, they do not respect the manylinux1 policy and the result is that `pip install onnxruntime` install those none compliant packages on system that don't support them. Building on manylinux2010 docker image allow wheels built to truly be compliant with a manylinux policy in order to provide onnxruntime to a wider audience.
- If it fixes an open issue, please link to the issue here.
This fixes #1001

### CODE REVIEW

**Comment by mayeut** [comment]
Probably also fixes #1113

File: tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ls -al /opt/onnxruntime-python/bin
+
+echo "#!/bin/sh" > /opt/entrypoint.sh
+echo "source /opt/onnxruntime-python/bin/activate" >> /opt/entrypoint.sh
+echo "exec \"$@\"" >> /opt/entrypoint.sh
+
+mkdir -p $HOME/.aria2
+echo "ca-certificate=/opt/_internal/certs.pem" > $HOME/.aria2/aria2.conf
+
+mkdir -p /tmp/libpng
```
Comment (snnn) [inline tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh]: libpng is not needed for building the python package.

File: tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+do case "${parameter_Option}"
+in
+p) PYTHON_VER=${OPTARG};;
+esac
+done
+
+PYTHON_VER=${PYTHON_VER:=3.5}
+CPYTHON_VER=cp${PYTHON_VER//./}
+
+curl -fsSLo /tmp/rpmforge.rpm http://repository.it4i.cz/mirrors/repoforge/redhat/el6/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
```
Comment (snnn) [inline tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh]: Please add a comment, which do you need from this repo?

File: tools/ci_build/github/linux/docker/scripts/install_deps.sh [hunk 3]
```diff
@@ -37,7 +37,7 @@ rm -rf /tmp/src
 DISTRIBUTOR=$(lsb_release -i -s)
 if [ "$DISTRIBUTOR" = "Ubuntu" ]; then
   apt-get -y remove libprotobuf-dev protobuf-compiler
-else
+elif [ "$DISTRIBUTOR" != "CentOS" ]; then
```
Comment (snnn) [inline tools/ci_build/github/linux/docker/scripts/install_deps.sh]: We need to uninstall  protobuf-devel protobuf-compiler if they are installed.  Here this 'elif' looks confusing.

File: tools/ci_build/github/linux/docker/Dockerfile.manylinux2010_gpu [hunk 4]
```diff
@@ -0,0 +1,66 @@
+FROM quay.io/pypa/manylinux2010_x86_64:latest
```
Comment (snnn) [inline tools/ci_build/github/linux/docker/Dockerfile.manylinux2010_gpu]: I guess this requires nvidia-docker runtime v2, right?

File: setup.py [hunk 5]
```diff
@@ -38,12 +43,69 @@
...
+
+        def run(self):
+            if is_manylinux2010:
+                source = 'onnxruntime/capi/onnxruntime_pybind11_state.so'
+                dest = 'onnxruntime/capi/onnxruntime_pybind11_state_manylinux2010.so'
+                logger.info('copying %s -> %s', source, dest)
+                copyfile(source, dest)
+                result = subprocess.run(['patchelf', '--print-needed', dest], check=True, stdout=subprocess.PIPE, universal_newlines=True)
+                cuda_dependencies = ['libcublas.so', 'libcudnn.so', 'libcudart.so']
+                to_preload = []
```
Comment (snnn) [inline setup.py]: Could you please give an example of the to_preload list?

File: tools/ci_build/github/linux/docker/Dockerfile.manylinux2010_gpu (hunk 4 above)
Comment (mayeut) [reply tools/ci_build/github/linux/docker/Dockerfile.manylinux2010_gpu]: The manylinux2010 docker images has no adherence whatsoever to NVIDIA docker.
The relevant bits are line 54 of that file.
It probably will not work with nvidia-docker v1, if this is an issue, I can add the lines needed for that.

File: setup.py (hunk 5 above)
Comment (mayeut) [reply setup.py]: `['libcublas.so.10.0', 'libcudnn.so.7', 'libcudart.so.10.0']`

File: tools/ci_build/github/linux/docker/scripts/install_deps.sh (hunk 3 above)
Comment (mayeut) [reply tools/ci_build/github/linux/docker/scripts/install_deps.sh]: Why should it be uninstalled ? There's no comment about this and the build is working fine so I did not bother to uninstall only the dev/compiler parts of a full installation from sources.

File: setup.py (hunk 5 above)
Comment (snnn) [reply setup.py]: Why they need be preloaded? I guess they can be automatically loaded when needed.

File: tools/ci_build/github/linux/docker/scripts/install_deps.sh (hunk 3 above)
Comment (snnn) [reply tools/ci_build/github/linux/docker/scripts/install_deps.sh]: onnxruntime  depends on protobuf 3.x.
However, the protobuf lib in ubuntu repo, is 2.x.

If we have both of them on the disk, onnxruntime may wrongly pick up the 2.x version header file

Comment (mayeut) [reply tools/ci_build/github/linux/docker/scripts/install_deps.sh]: Here I skip uninstalling on CentOS / manylinux because we never installed protobuf system package in the first place but used install_protobuf.sh which installs protobuff 3.6.1, we should be safe here.

File: setup.py (hunk 5 above)
Comment (mayeut) [reply setup.py]: In order for `auditwheel` to create a manylinux2010 compliant wheel, cuda libraries dependencies are removed from the python C extension, thus they need to be preloaded.

File: tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh (hunk 1 above)
Comment (mayeut) [reply tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh]: removed

File: tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh (hunk 2 above)
Comment (mayeut) [reply tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh]: done

**Comment by raymondxyang** [comment]
Thanks for the work! The manylinux2010 and auditwheel really helps our distribution. I queued it in release pipeline for validation.

**Comment by mayeut** [comment]
I pushed a new commit reverting a change introduced in `cmake/CMakeLists.txt`. It should solve the windows issue.

**Comment by raymondxyang** [comment]
I'll unblock the Windows failure tomorrow (some build environment related). Sorry for the delay..

**Comment by raymondxyang** [comment]
Hi @mayeut could you pull ziya/update-cuda branch to unblock the windows build? I already altered the VMs for cuda 10.

**Comment by raymondxyang** [comment]
For the Linux fail on mnist model, it's a known flaky case (we are looking into it) and we will check in your PR first.

**Comment by mayeut** [comment]
> Hi @mayeut could you pull ziya/update-cuda branch to unblock the windows build? I already altered the VMs for cuda 10.

@raymondxyang, done

File: tools/ci_build/github/linux/docker/scripts/install_deps.sh (hunk 3 above)
Comment (snnn) [reply tools/ci_build/github/linux/docker/scripts/install_deps.sh]: Please add a comment there. Because install_deps.sh  doesn't know why CentOS doesn't have this package installed. 
And, what ever how did you installed protobuf, it's safer to uninstall it before building onnxruntime. Because, it's lesser chance to have version conflict.

Comment (mayeut) [reply tools/ci_build/github/linux/docker/scripts/install_deps.sh]: It's already changed in the latest commit, I forgot to give you a heads-up. Please check the new diff on this file.

**Comment by raymondxyang** [comment]
Thanks for the contribution :)))

File: cmake/onnxruntime_python.cmake [hunk 6]
```diff
@@ -60,7 +60,7 @@ onnxruntime_add_include_to_target(onnxruntime_pybind11_state gsl)
 if(APPLE)
   set(ONNXRUNTIME_SO_LINK_FLAG "-Xlinker -exported_symbols_list ${ONNXRUNTIME_ROOT}/python/exported_symbols.lst")
 elseif(UNIX)
-  set(ONNXRUNTIME_SO_LINK_FLAG "-Xlinker --version-script=${ONNXRUNTIME_ROOT}/python/version_script.lds -Xlinker --no-undefined -Xlinker --gc-sections")
+  set(ONNXRUNTIME_SO_LINK_FLAG "-Xlinker --version-script=${ONNXRUNTIME_ROOT}/python/version_script.lds -Xlinker --gc-sections")
```
Comment (snnn) [inline cmake/onnxruntime_python.cmake]: Please revert this line back.

Comment (snnn) [reply cmake/onnxruntime_python.cmake]: I added the "--no-undefined" flag here in purpose.  If you can't build onnxruntime without the flag, then it means you missed something in the link inputs.  This flag is a safety check for us to know what's going on.  I'd rather prefer to keep it.

File: cmake/onnxruntime_common.cmake [hunk 7]
```diff
@@ -67,3 +67,18 @@ if(WIN32)
...
+include(CheckFunctionExists)
+if ("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
+  check_library_exists(rt clock_gettime "time.h" HAVE_CLOCK_GETTIME)
+
+  if (NOT HAVE_CLOCK_GETTIME)
+    set(CMAKE_EXTRA_INCLUDE_FILES time.h)
+    check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
+    set(CMAKE_EXTRA_INCLUDE_FILES)
+  else()
+    target_link_libraries(onnxruntime_common rt)
```
Comment (snnn) [inline cmake/onnxruntime_common.cmake]: First , I don't prefer to use target_link_libraries on static libs.
Second, at least, it should be target_link_libraries(onnxruntime_common  PRIVATE rt). It missed the keyword.

File: tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+yum -y install openblas-devel zlib-devel curl-devel expat-devel aria2 rsync redhat-lsb-core
+yum -y clean all
+
+/opt/python/${CPYTHON_VER}-${CPYTHON_VER}m/bin/python -m venv /opt/onnxruntime-python
+source /opt/onnxruntime-python/bin/activate
+if [ ! -f /opt/onnxruntime-python/bin/python${PYTHON_VER} ]; then
+  ln -s python /opt/onnxruntime-python/bin/python${PYTHON_VER}
+fi
+python -m pip install --upgrade --force-reinstall pip==19.1.1
+python -m pip install --upgrade --force-reinstall numpy==1.16.3
```
Comment (snnn) [inline tools/ci_build/github/linux/docker/scripts/install_manylinux2010.sh]: This line must be fixed. @raymondxyang

File: cmake/onnxruntime_python.cmake (hunk 6 above)
Comment (mayeut) [reply cmake/onnxruntime_python.cmake]: @snnn, manylinux images do not provide a library to link against for python on purpose. All those symbols will be provided by the python executable (built statically). That just works the way symbol resolution is done on Linux but prevents the usage of  "--no-undefined" flag here. It was defined this way in order to allow usage of manylinux wheels wether python was built with static or dynamic libraries.
