### PR TITLE
[js/webgpu] fix Conv2DMatMul shader's out-of-bound read

### LINKED ISSUE #22983: [Web] Stable Diffusion Inpainting FP16 UNET outputs NANs
### Describe the issue

I converted [stable-diffusion-inpainting](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-inpainting) and [stable-diffusion-2-inpainting](https://huggingface.co/stabilityai/stable-diffusion-2-inpainting) to FP16 ONNX format using both the [optimum-cli export](https://huggingface.co/docs/optimum/main/en/exporters/onnx/usage_guides/export_a_model#exporting-a-model-to-onnx-using-the-cli) command and [this](https://github.com/Amblyopius/Stable-Diffusion-ONNX-FP16/blob/main/conv_sd_to_onnx.py) script. The models work fine in Python ONNX Runtime but in ONNX Runtime Web, the UNET outputs NANs for some unknown reason as shown below:

Image

The code running the models in the browser was translated to JavaScript from the [pipeline script](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py) and the [ONNX pipeline script](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion_inpaint.py) and I'm pretty sure that my code is correct but I could be wrong. The shapes are as expected as ORT Web does not complain about this.

Does anybody have any idea what could be causing these NANs in the UNET? Could this be an issue of the model conversion or my code? Any assistance with this will be greatly appreciated as I have tried pretty much all I can think of.

### Additional Context
- There is a Nearest Neighbor Interpolation resize done in this pipeline which I achieved using OpenCV.js like so: 
```js
const maskCV = cv.matFromArray(width, height, cv.CV_32FC1, maskCondition);
const interpolatedMask = new cv.Mat();
const dSize = new cv.Size(height / this.vaeScaleFactor, width / this.vaeScaleFactor);
cv.resize(maskCV, interpolatedMask, dSize, 0, 0, cv.INTER_NEAREST);
```

### To reproduce

To quickly reproduce the issue I guess that the UNET of any of my converted models can be loaded in an Inference Session and an object of 3 random inputs can be passed as input to the Session. The object consists of the following entries:

```js
{
sample: shape [2, 9, 64, 64] | type float32,
timestep: shape [1] | type float32,
encoder_hidden_states: shape [2, 77, 1024] | type float32
}
 ```

Some of the models I have converted are:
- [ONNX Stable Diffusion Inpainting 2 FP16](https://huggingface.co/jdp8/sd-2-inpainting-fp16/tree/main).
- [ONNX Stable Diffusion Inpainting 2 FP16 with opset 20](https://huggingface.co/jdp8/sd-2-inpainting-opset-20-skip-layer-norm-fp16/tree/main).
- [ONNX Stable Diffusion Inpainting 2 FP16 with upcasted Attention](https://huggingface.co/jdp8/sd-2-inpainting-upcast-fp16/tree/main).
- Many more models which can be found in my [HuggingFace Repo](https://huggingface.co/jdp8).

### Urgency

Somewhat urgent.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.20.0

### Execution Provider

'webgpu' (WebGPU)

### PR DESCRIPTION
**Pull request by fs-eire**
### Description

Fix a bug caused by potential out-of-bound reads of `W` in the Conv2DMatMul shader.

### Motivation and Context

Fixes #22983

### CODE REVIEW

**Comment by fs-eire** [comment]
@qjia7 PTAL

File: js/web/lib/wasm/jsep/webgpu/ops/3rd-party/conv2d_mm_webgpu.ts [hunk 1]
```diff
@@ -143,7 +143,15 @@ const conv2dCommonSnippet = (
...
-  const sampleW = `${getWSnippet(innerElementSizeW)}`;
+  const sampleW =
+    fitInner && fitBOuter
+      ? getWSnippet(innerElementSizeW)
+      : `
+    let col = colIn * ${innerElementSizeW};
+    if (row < uniforms.dim_inner && col < uniforms.dim_b_outer) {
+      ${getWSnippet(innerElementSizeW)}
+    }
+    return ${typeSnippet(innerElementSizeW, dataType)}(0.0);`;
```
Comment (qjia7) [inline js/web/lib/wasm/jsep/webgpu/ops/3rd-party/conv2d_mm_webgpu.ts:154]: This is for channel last case. The channel first is missing.
```suggestion
  const sampleW = isChannelsLast ?
  fitInner && fitBOuter
    ? getWSnippet(innerElementSizeW)
    : `
  let col = colIn * ${innerElementSizeW};
  if (row < uniforms.dim_inner && col < uniforms.dim_b_outer) {
    ${getWSnippet(innerElementSizeW)}
  }
  return ${typeSnippet(innerElementSizeW, dataType)}(0.0);`
  : `
  let col = colIn * ${innerElementSizeW};
  if (row < uniforms.dim_inner && col < uniforms.dim_a_outer) {
    ${getWSnippet(innerElementSizeW)}
  }
  return ${typeSnippet(innerElementSizeW, dataType)}(0.0);`;
```

**Review by qjia7 — APPROVED** [review]
LGTM, thanks!

**Review by guschmue — APPROVED** [review]
