### PR TITLE
Fixes #1007, base_value in TreeEnsembleClassifier

### LINKED ISSUE #1007: TreeEnsembleClassifier: base_value not tested, fails for binary classification
**Describe the bug**
If base_value is specified and the number of classes is 2, the score of the second class is constant.

**System information**
- OS Platform and Distribution: Windows
- ONNX Runtime installed from source
- ONNX Runtime version: 0.4
- Python version: 3.7
- Visual Studio version 2017

### PR DESCRIPTION
**Pull request by xadupre**

### CODE REVIEW

File: onnxruntime/test/providers/cpu/ml/tree_ensembler_classifier_test.cc [hunk 1]
```diff
@@ -151,5 +151,107 @@ TEST(MLOpTest, TreeEnsembleClassifierBinary) {
   test.Run();
 }
 
+TEST(MLOpTest, TreeEnsembleClassifierBinaryBaseValue) {
+  OpTester test("TreeEnsembleClassifier", 1, onnxruntime::kMLDomain);
+
+  std::vector<float> base_values = {-1.202673316001892f, -1.202673316001892f};
```
Comment (jignparm) [inline onnxruntime/test/providers/cpu/ml/tree_ensembler_classifier_test.cc]: Which scikit-learn tree algorithm generated these base_values (e.g. RandomForest, ExtraTrees)?

Would be helpful to put the scikit-learn script that generated this exact tree, or a few comments about how this test case was generated.

Comment (xadupre) [reply onnxruntime/test/providers/cpu/ml/tree_ensembler_classifier_test.cc]: Fixed.
