### PR TITLE
Bug fix for shape of optional output in Dropout op

### LINKED ISSUE #1487: DropOut fails when mask output tensor provided
**Describe the bug**
Executing a model with DropOut that includes the bool8 mask tensor fails with the following error:

    Error: HRESULT=0x80004005 message=S:\WindowsAI\engine\lotus\onnxruntime\core\framework\execution_frame.cc:63 onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{5} Requested shape:{}
    Stacktrace:
    s:\windowsai\engine\lotus\onnxruntime\core\framework\op_kernel.cc(40): onnxruntime::OpKernelContext::OutputMLValue
    s:\windowsai\engine\lotus\onnxruntime\core\framework\op_kernel.cc(27): onnxruntime::OpKernelContext::Output
    s:\windowsai\engine\lotus
    EndGroup: Test:#3; Graph:Dropout_identity_with_mask_float32; Executor:WinMLOperatorExecutor_Cpu; [Failed]

https://github.com/onnx/onnx/blob/master/docs/Operators.md#dropout

Appears the bug is in providers\cpu\tensor\identity_op.h, passing an empty shape instead of the actual shape.

    if (is_dropout) {
      context->Output(1, std::vector<int64_t>());
    }

Shouldn't that be: `context->Output(1, shape);`? (the test passes for me locally if I change that line)

**Urgency**
Before Vibranium desired.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 18874 2019-04-05
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: bf6f19c6b729ee2b5e067f48b30bb412951b828a engine/lotus (v0.1.4-709-gbf6f19c6)
- Python version: NA
- Visual Studio version (if applicable): Visual Studio 2017 15.8.5
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: AMD Radeon, 32GBs system RAM

**To Reproduce**
Load the given model with a mask.

    {
      "graph_name": "Dropout float32 with mask",
      "op_type": "Dropout",
      "version": 10,
      "ratio": 0,
      "data": [2, 3, 4, 5, 6],
      "output": [2, 3, 4, 5, 6],
      "mask": [0, 0, 0, 0, 0], // No values were dropped.
      "T": "float32"
    }
--------
    ir_version: 3
    producer_name: "OnnxConformanceTest"
    graph {
      node {
        input: "data"
        output: "output"
        output: "mask"
        op_type: "Dropout"
        attribute {
          name: "ratio"
          f: 0
          type: FLOAT
        }
        domain: ""
      }
      initializer {
        dims: 5
        data_type: FLOAT
        name: "data"
        raw_data: "\000\000\000@\000\000@@\000\000\200@\000\000\240@\000\000\300@"
      }
      input {
        name: "data"
        type {
          tensor_type {
            elem_type: FLOAT
            shape {
              dim {
                dim_value: 5
              }
            }
          }
        }
      }
      output {
        name: "output"
        type {
          tensor_type {
            elem_type: FLOAT
            shape {
              dim {
                dim_value: 5
              }
            }
          }
        }
      }
      output {
        name: "mask"
        type {
          tensor_type {
            elem_type: BOOL
            shape {
              dim {
                dim_value: 5
              }
            }
          }
        }
      }
    }
    opset_import {
      version: 10
    }

**Expected behavior**
For inference, the bool8 mask tensor should be all 0's (I think anyway from my reading of the spec, assuming 1 means it was dropped and 0 means it was preserved) rather than error.

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: 
Dropout op produces an output 'mask' (optionally).This change is to fix the shape of the output if generated.

As part of this change, bring Dropout kernels declared for CUDA on parity with their CPU equivalent (needed for new tests to pass)

CC: @fdwr 

**Motivation and Context**
Resolve #1487

### CODE REVIEW

**Comment by hariharans29** [comment]
@fdwr - you are right. The spec could be clearer. However, as you say, I think the value will be 1 when the input is dropped and 0 if not (intuitively).

But in my opinion - the value of 'mask' during inferencing can be "don't cares" as logically I don't see any rationale behind assigning any value since there is no real "dropping" performed.  One could argue that since we are "preserving" input values, the mask should be 0, but I feel "preserving" is not the same thing as "not dropping". Anyway, these are just details....

**Comment by hariharans29** [comment]
CC: @scottmckay and @HectorSVC for review feedback!

File: onnxruntime/core/providers/cpu/tensor/identity_op.h [hunk 1]
```diff
@@ -43,7 +43,18 @@ class IdentityOp final : public OpKernel {
...
+      // a 'nullptr' returned would make it an unused optional output
+      if (mask != nullptr) {
+        // Opset 7 differs with Opset 10 in that the type of the 'mask'
+        // output is tied with the type of the input in Opset 7 whereas
+        // the type of 'mask' in Opset 10 is 'bool' always
+        // so we have a common solution
+        void* mask_data = mask->MutableDataRaw();
+        // In 'test'/'inference' mode, there are no input values dropped out
+        // so fill the buffer with 0/false
+        memset(mask_data, 0, shape.Size() * mask->DataType()->Size());
```
Comment (skottmckay) [inline onnxruntime/core/providers/cpu/tensor/identity_op.h]: mask->SizeInBytes()

Comment (hariharans29) [reply onnxruntime/core/providers/cpu/tensor/identity_op.h]: Fixed, thanks

File: onnxruntime/core/providers/cpu/tensor/identity_op.h [hunk 2]
```diff
@@ -43,7 +43,18 @@ class IdentityOp final : public OpKernel {
...
+      // a 'nullptr' returned would make it an unused optional output
+      if (mask != nullptr) {
+        // Opset 7 differs with Opset 10 in that the type of the 'mask'
+        // output is tied with the type of the input in Opset 7 whereas
+        // the type of 'mask' in Opset 10 is 'bool' always
+        // so we have a common solution
+        void* mask_data = mask->MutableDataRaw();
+        // In 'test'/'inference' mode, there are no input values dropped out
+        // so fill the buffer with 0/false
+        memset(mask_data, 0, mask->SizeInBytes());
```
Comment (snnn) [inline onnxruntime/core/providers/cpu/tensor/identity_op.h]: What if the tensor type is string?

Comment (skottmckay) [reply onnxruntime/core/providers/cpu/tensor/identity_op.h]: Input is constrained to a few numeric types so it shouldn't be.

Comment (snnn) [reply onnxruntime/core/providers/cpu/tensor/identity_op.h]: Then why " if (target != source)  " has such handling?

Comment (hariharans29) [reply onnxruntime/core/providers/cpu/tensor/identity_op.h]: I think Dropout doesn't support 'string' type (https://github.com/onnx/onnx/blob/master/docs/Operators.md#Dropout). 

For opset 8 onwards, the (optional) mask is always boolean. So not a problem here.

For opset 7, the (optional) mask is of the same type as the input tensor and the input types supported are float, double, float16. So string doesn't come into the picture here.

The question is - should I do something for float16 though ? (I suppose not)

Comment (hariharans29) [reply onnxruntime/core/providers/cpu/tensor/identity_op.h]: > Then why " if (target != source) " has such handling?

THat's because this kernel inherently supports 2 ops - Identity and Dropout. Identity supports string. Dropout does not. The new logic comes in the Dropout section.

**Comment by hariharans29** [comment]
Will merge if @snnn has no concerns...

File: onnxruntime/core/providers/cpu/tensor/identity_op.h (hunk 2 above)
Comment (fdwr) [reply onnxruntime/core/providers/cpu/tensor/identity_op.h]: @hariharans29 : Doesn't float16 come for free anyway due to the implicit cast nodes? So, I don't think you need to "do something" special for it to work.

Comment (hariharans29) [reply onnxruntime/core/providers/cpu/tensor/identity_op.h]: You are right @fdwr :). No action needed.
