### PR TITLE
Fix shape inference failure with in-memory external data

### LINKED ISSUE #26261: 🐛 Bug Report: ONNXRuntime 1.23 fails to load model with external data (works fine in 1.22.x)
### Describe the issue

After upgrading from onnxruntime 1.22 to 1.23.0, loading a previously working ONNX model throws a shape inference error related to external data.
This issue does not occur in version 1.22.x the same code and model run successfully there.
```
[ONNXRuntimeError] : 1 : FAIL : Node (/decoder/Split_33) Op (Split) [ShapeInferenceError] Cannot parse data from external tensors. Please load external data into raw data for tensor: /decoder/Constant_1066_output_0
```

Related: https://github.com/danielgatis/rembg/issues/790

### To reproduce

```python
import onnxruntime as ort

model_path = "BiRefNet-COD-epoch_125.onnx"
session = ort.InferenceSession(
    model_path,
    providers=["CPUExecutionProvider"]
)
```
[BiRefNet-COD-epoch_125.onnx](https://github.com/ZhengPeng7/BiRefNet/releases/download/v1/BiRefNet-COD-epoch_125.onnx)

### Urgency

_No response_

### Platform

Linux

### OS Version

Linux Mint 22 Cinnamon

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.23.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CPU

### Execution Provider Library Version

_No response_

### PR DESCRIPTION
**Pull request by snnn**
## Description

Fixes #26261

This PR resolves a regression introduced in v1.23.0 where models with Constant nodes containing tensors larger than 127 bytes fail to load with a shape inference error.

### Root Cause

Commit 3b97d79b3c (PR #25320) introduced an optimization to convert large Constant node tensors (> 127 bytes) into OrtValues with in-memory external data references for better memory management. However, ONNX shape inference cannot distinguish between in-memory and file-based external data, and rejects any TensorProto with `data_location = EXTERNAL`.

### The Fix

Modified `InferenceContextImpl::getInputData()` to:
1. Detect tensors with in-memory external data using `utils::HasExternalDataInMemory()`
2. Retrieve the corresponding OrtValue
3. Create a temporary TensorProto with embedded data (not external reference)
4. Provide this temporary proto to ONNX shape inference

This allows ONNX shape inference to access the actual tensor data without rejecting it as external.

### Memory Impact

This fix introduces a minor and temporary increase in memory usage during the model loading phase. 

- **When:** The additional memory is allocated only when the shape inference engine needs to access the data of a constant tensor that is larger than 127 bytes. This is a one-time event during the initial analysis of the model.
- **What:** The fix creates a temporary in-memory copy of the tensor data.
- **Duration:** This temporary copy is released as soon as shape inference is complete.

The impact on the overall peak memory usage of the application is expected to be negligible. The memory usage during inference is not affected. While it is theoretically possible for the temporary tensor to be large if a multi-gigabyte constant tensor is used for shape inference, this is a highly unlikely scenario in practice for well-designed models.

### Testing

- Tested with the problematic model from issue #26261
- All optimization levels now work correctly (DISABLE_ALL, BASIC, EXTENDED, ALL)
- Unit tests to be added

### Changes

- **onnxruntime/core/graph/graph.cc**: 
  - Modified `getInputData()` method in `InferenceContextImpl` class
  - Added `temp_tensor_protos_` member to store temporary TensorProtos during shape inference

## TODO

- [ ] Add unit tests
- [ ] Run full test suite

### CODE REVIEW

**Comment by snnn** [comment]
## Update: Unit Test Added

I've added a comprehensive unit test in `onnxruntime/test/ir/graph_test.cc`:

### Test: `GraphTest.ShapeInferenceWithInMemoryExternalData`

**What it tests:**
- Creates a Constant node with a 128-byte tensor (16 INT64 values)
- This is just over the 127-byte threshold that triggers in-memory externalization
- Uses this constant as input to a Split node (which requires constant data for shape inference)
- Verifies that the model loads, shape inference succeeds, and graph resolves correctly

**Before the fix:** Test would fail with:
```
Cannot parse data from external tensors. Please load external data into raw data for tensor
```

**With the fix:** Test passes ✅

### Test Execution

```bash
cd build_dir
./onnxruntime_test_all --gtest_filter="GraphTest.ShapeInferenceWithInMemoryExternalData"
```

Result:
```
[  PASSED  ] 1 test.
```

### Next Steps

The PR now includes:
- ✅ Bug fix implementation
- ✅ Unit test coverage
- 🔄 Awaiting CI results and review

**Comment by snnn** [comment]
## Summary: Investigation Complete

I've completed a thorough investigation and fix for issue #26261.

### What Was Done:

1. **Root Cause Analysis** - Used GDB to trace the exact failure point
2. **Fix Implementation** - Modified `InferenceContextImpl::getInputData()` to handle in-memory external data
3. **Unit Tests Added** - Two test cases for regression prevention
4. **Real-World Validation** - Confirmed fix works with the actual problematic model

### Test Validation:

**Real-World Model (BiRefNet-COD-epoch_125.onnx):**
- ✅ **WITH fix**: Loads successfully with ALL optimization levels
- ❌ **WITHOUT fix**: Fails with `Cannot parse data from external tensors` error

**Unit Tests:**
- `GraphTest.ShapeInferenceWithInMemoryExternalData` - Basic coverage via Model::Load
- `GraphTest.ShapeInferenceWithInMemoryExternalDataViaSession` - Coverage via InferenceSession

Note: The unit tests pass even without the fix due to optimization paths in the test environment, but provide regression coverage for the code path. The real validation comes from the actual model test which definitively fails without the fix and succeeds with it.

### Ready for Review

The PR includes:
- ✅ Bug fix with detailed comments
- ✅ Unit test coverage  
- ✅ Validation with real-world model
- ✅ Documentation of root cause

All changes are minimal and surgical, focused solely on fixing the regression introduced in v1.23.0.

**Comment by snnn** [comment]
## ✅ Success: Unit Test Now Properly Catches the Bug!

I've successfully created a unit test that definitively fails without the fix and passes with it.

### Test: `GraphTest.ShapeInferenceAfterInitializerExternalization`

**What it does:**
1. Creates a model with a 128-byte initializer (just over the 127-byte threshold)
2. Calls `ConvertInitializersIntoOrtValues()` to trigger in-memory externalization
3. Calls `SetGraphResolveNeeded()` to force re-resolution
4. Calls `Resolve()` again which runs shape inference on the externalized data

**Results:**
- ❌ **WITHOUT the fix**: `FAILED` with exact error:
  ```
  Node (split_node) Op (Split) [ShapeInferenceError] Cannot parse data from 
  external tensors. Please load external data into raw data for tensor: split_sizes
  ```

- ✅ **WITH the fix**: `PASSED` - shape inference successfully accesses the externalized data

### Why This Test Works

The key insight was understanding that:
1. `ConvertInitializersIntoOrtValues()` is called AFTER initial `Resolve()` in InferenceSession
2. We need to call `SetGraphResolveNeeded()` to force shape inference to run again
3. This recreates the exact scenario where transformers/optimizations modify the graph after externalization

This test provides robust regression coverage and will catch any similar issues in the future.

File: onnxruntime/core/graph/graph.cc [hunk 1]
```diff
@@ -2678,6 +2678,30 @@ class InferenceContextImpl : public ONNX_NAMESPACE::InferenceContext {
...
+        if (graph_.GetOrtValueInitializer(def->Name(), ort_value, true)) {
+          // Create a temporary TensorProto with the actual data from the OrtValue
+          // This allows ONNX shape inference to access the data
+          const Tensor& tensor = ort_value.Get<Tensor>();
+          auto temp_tensor_proto = std::make_unique<ONNX_NAMESPACE::TensorProto>(
+              utils::TensorToTensorProto(tensor, initializer->name(), /*use_tensor_buffer=*/false));
+
+          const TensorProto* result = temp_tensor_proto.get();
+          // Store the temporary proto so it outlives this call
+          temp_tensor_protos_.push_back(std::move(temp_tensor_proto));
```
Comment (yuslepukhin) [inline onnxruntime/core/graph/graph.cc]: Nice fix, I was thinking about it this morning. This will open the door for more memory savings.

File: onnxruntime/test/ir/graph_test.cc [hunk 2]
```diff
@@ -2573,5 +2577,263 @@ TEST_F(GraphTest, GraphConstruction_MemoryEfficientTopologicalSort_SubgraphGener
...
+  // Before the fix, this would fail with:
+  // "Cannot parse data from external tensors. Please load external data into raw data for tensor"
+  std::shared_ptr<Model> model;
+  ASSERT_STATUS_OK(Model::Load(std::move(model_proto), model, nullptr, *logger_));
+
+  // Verify the graph was properly constructed
+  Graph& graph = model->MainGraph();
+  ASSERT_STATUS_OK(graph.Resolve());
+
+  // Verify the constant node was converted to an initializer
```
Comment (yuslepukhin) [inline onnxruntime/test/ir/graph_test.cc:2653]: The comment is misleading. The initializer stays the same in the graph. It is only convered within the InferenceContext while inference is in progress.

**Comment by yuslepukhin** [comment]
One more thing. ORT has several implementations of InterenceContext interface. Please, check them all.

File: onnxruntime/core/graph/graph.cc [hunk 3]
```diff
@@ -2678,6 +2678,27 @@ class InferenceContextImpl : public ONNX_NAMESPACE::InferenceContext {
...
+        OrtValue ort_value;
+        if (graph_.GetOrtValueInitializer(def->Name(), ort_value, true)) {
+          // Create a temporary TensorProto with the actual data from the OrtValue
+          // This allows ONNX shape inference to access the data
+          const Tensor& tensor = ort_value.Get<Tensor>();
+          auto temp_tensor_proto = utils::TensorToTensorProto(tensor, initializer->name(), /*use_tensor_buffer=*/false);
+          // Store the temporary proto so it outlives this call, maintain pointers steady
+          temp_tensor_protos_.push_back(std::make_unique<ONNX_NAMESPACE::TensorProto>(std::move(temp_tensor_proto)));
+          return temp_tensor_protos_.back().get();
+        } else {
```
Comment (snnn) [inline onnxruntime/core/graph/graph.cc:2695]: Using `emplace_back` is a more modern and idiomatic C++17 approach for constructing the element in-place within the vector
```diff
-          auto temp_tensor_proto = utils::TensorToTensorProto(tensor, initializer->name(), /*use_tensor_buffer=*/false);
-          // Store the temporary proto so it outlives this call, maintain pointers steady
-          temp_tensor_protos_.push_back(std::make_unique<ONNX_NAMESPACE::TensorProto>(std::move(temp_tensor_proto)));
-          return temp_tensor_protos_.back().get();
+          // Store the temporary proto so it outlives this call, maintain pointers steady.
+          // Use emplace_back to construct the unique_ptr in-place.
+          temp_tensor_protos_.emplace_back(std::make_unique<ONNX_NAMESPACE::TensorProto>(
+              utils::TensorToTensorProto(tensor, initializer->name(), /*use_tensor_buffer=*/false)));
+          return temp_tensor_protos_.back().get();
```

**Comment by apsonawane** [comment]
Cherry-picked for 1.23.2. Removing the release tag and adding cherry-pick tag
