### PR TITLE
[js/webgpu] Fix conv2d with activation

### LINKED ISSUE #18297: [Web] WebGPU has conformance regression due to introduction of FusedConv
### Describe the issue

Due to PR below, some models (like mobilenetv2-12 and detr-resnet-50) have conformance regression

commit a2e9ba72d5a5f61e1324ffc2a80d748d01be9120 (HEAD -> main)
Author: satyajandhyala <satya.k.jandhyala@gmail.com>
Date:   Wed Nov 1 15:34:51 2023 -0700

    [JS/Web]Added FusedConv. (#17766)

### To reproduce

* Build the latest ONNX Runtime WebGPU
* Visit below url and point <local_build> to your local build. For example: ortUrl=https://abc.com/onnxruntime
https://webatintel.github.io/ort-toolkit/?tasks=conformance&ep=webgpu&modelName=mobilenetv2-12&modelUrl=hf&ortUrl=<local_build>
* You may see {"result":false} in "Test Results" section.

### Urgency

_No response_

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

a2e9ba72d5a5f61e1324ffc2a80d748d01be9120

### Execution Provider

'webgpu' (WebGPU)

### PR DESCRIPTION
**Pull request by qjia7**
### Description
Fix #18297

With PR #17766, conv2d activation in mobilenetv2-12 will not be empty. However, activation is not supported yet in [biasActivationSnippet](https://github.com/microsoft/onnxruntime/blob/main/js/web/lib/wasm/jsep/webgpu/ops/3rd-party/activation_util.ts#L48C14-L48C36). This PR makes all places unify to use [getActivationSnippet](https://github.com/microsoft/onnxruntime/blob/main/js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts#L13) to fix this issue.

### CODE REVIEW

**Comment by qjia7** [comment]
@satyajandhyala @guschmue @fs-eire Please take a look, thanks.

File: js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ export interface InternalActivationAttributes {
 }
 
 export const getActivationSnippet = (attributes: InternalActivationAttributes, valueType: string):
-    {activationFunction: string; applyActivation: string;} => {
+    {activationFunction: string; applyActivation: string} => {
```
Comment (gyagp) [inline js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts:14]:
```suggestion
    {activationFunction: string, applyActivation: string} => {
```

Comment (qjia7) [reply js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts:14]: Changing it to comma will cause the lint error:
```
/workspace/users/jiajia/onnxruntime/js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts
  14:33  error  Expected a semicolon  @typescript-eslint/member-delimiter-style

Comment (gyagp) [reply js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts:14]: Both should be OK, but our .eslintrc.js has below configuration, so comma is not allowed here.
    '@typescript-eslint/member-delimiter-style': [
      'error', {
        'multiline': { 'delimiter': 'semi', 'requireLast': true },
        'singleline': { 'delimiter': 'semi', 'requireLast': false }
      }
    ],

**Comment by satyajandhyala** [comment]
Just to clarify, Conv2d is using two separate flows 
[one](https://github.com/microsoft/onnxruntime/blob/25fbc2b0abb18a1277c0f5d4b6c38bf58b9de154/js/web/lib/wasm/jsep/webgpu/ops/conv.ts#L199) using createMatmuProgramInfo and
[the other](https://github.com/microsoft/onnxruntime/blob/25fbc2b0abb18a1277c0f5d4b6c38bf58b9de154/js/web/lib/wasm/jsep/webgpu/ops/conv.ts#L228) using createConv2DMatMulProgramInfo. 

The first one uses read/write snippets create by matMulReadWriteSource defined in matmul_packed_webgpu.ts  and the later uses read/write snippets create by conv2dCommonSnippet defined in conv2d_mm_webgpu.ts. The previous changes I made to support conv-activation fusion only supported the later. The first flow does not work with my previous changes although it work in other case.

**Review by guschmue — APPROVED** [review]

**Review by satyajandhyala — APPROVED** [review]

**Comment by guschmue** [comment]
Verified that it will fix https://github.com/microsoft/onnxruntime/issues/18297

File: js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts (hunk 1 above)
Comment (guschmue) [reply js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts:14]: resolving this one so we can merge the fix
