### PR TITLE
Fix memleakdbg call stack output.

### LINKED ISSUE #24535: ORT Debug Build Fails to Infer for Every Model
### Describe the issue

When building ONNX Runtime in Debug configuration, inference consistently fails for all models tested (e.g., SqueezeNet, AlexNet). The same models run successfully with a Release build. This issue appears to be isolated to the Debug build configuration and is reproducible across different models.

The inference attempt in Debug mode results in the following error (attached below), indicating a possible issue in debug-specific assertions, memory checks, or internal state validations.
Image

### To reproduce

1) git clone --recursive https://github.com/microsoft/onnxruntime
2) cd onnxruntime
3) build.bat --config Debug --build_shared_lib --parallel
4) cd build/Windows/Debug/Debug
5) onnxruntime_perf_test.exe -v -m times -r 1 -I "C:\Users\Administrator\Downloads\squeezenet1.1-7.onnx"

### Urgency

_No response_

### Platform

Windows

### OS Version

Windows 

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

main 

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

_No response_

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

Fix memleakdbg call stack output.

The call stack output was getting clobbered:
`C:\dev\onnxruntime\build\Debug\_deps\googletest-src\googletest\include\gtest\internal\gtest-port.h(1631): l\gtest-port.h(1631): eadLocal<testing::Sequence *>::GetOrCreateValue`

I think the issue is that this aliasing of `buffer` and `symbol`:
https://github.com/microsoft/onnxruntime/blob/173a11a4e7a2f7a360c9db6abbe601a06a16f004/onnxruntime/core/platform/windows/debug_alloc.cc#L97-L100

does not play nicely with a call to `_snprintf_s` like this:
https://github.com/microsoft/onnxruntime/blob/173a11a4e7a2f7a360c9db6abbe601a06a16f004/onnxruntime/core/platform/windows/debug_alloc.cc#L115

The clobbered output does not match the predefined, ignored patterns, so we see spurious mem leak check output.

This change updates the memleakdbg output generation to use C++ ostreams and instead of fixed size buffers and `_snprintf_s`.

### Motivation and Context

Fix spurious mem leak check output.
Fix #24535.

### CODE REVIEW

File: onnxruntime/core/platform/windows/debug_alloc.cc [hunk 1]
```diff
@@ -271,12 +269,8 @@ Memory_LeakCheck::~Memory_LeakCheck() {
...
     DebugPrint("-----Ending Heap Trace-----\n\n");
 
-    std::string string;
-    char buffer[1024];
-    _snprintf_s(buffer, _TRUNCATE, "%d bytes of memory leaked in %d allocations", static_cast<int>(leaked_bytes), static_cast<int>(leak_count));
-    string.append(buffer);
-
-    std::cout << "\n----- MEMORY LEAKS: " << string.c_str() << "\n";
+    std::cout << "\n----- MEMORY LEAKS: " << leaked_bytes << " bytes of memory leaked in "
+              << leak_count << " allocations" << "\n";
```
Comment (edgchen1) [inline onnxruntime/core/platform/windows/debug_alloc.cc:273]:
```suggestion
              << leak_count << " allocations\n";
```

File: onnxruntime/core/platform/windows/debug_alloc.cc [hunk 2]
```diff
@@ -75,45 +75,43 @@ struct SymbolHelper {
...
       }
     }
     return true;
   }
 
-  void Lookup(std::string& string, const ULONG_PTR address) {
-    alignas(SYMBOL_INFO) char buffer[kInitialBufferSize] = {0};
-    SYMBOL_INFO* symbol = reinterpret_cast<SYMBOL_INFO*>(buffer);
+  void Lookup(const void* address, std::ostream& message) {
+    alignas(SYMBOL_INFO) char symbol_buffer[kSymbolBufferSize] = {0};
```
Comment (RyanUnderhill) [inline onnxruntime/core/platform/windows/debug_alloc.cc:98]:
```suggestion
    alignas(SYMBOL_INFO) std::byte symbol_buffer[kSymbolBufferSize] = {0};
```
To avoid anyone accidentally writing directly to symbol_buffer as a string again?

Comment (edgchen1) [reply onnxruntime/core/platform/windows/debug_alloc.cc]: I found `SYMBOL_INFO_PACKAGE` in the DbgHelp.h, which is a struct containing `SYMBOL_INFO` and a char buffer following it. using that instead.

Comment (yuslepukhin) [reply onnxruntime/core/platform/windows/debug_alloc.cc]: Is that buffer owned by the `SYMBOL_INFO_PACKAGE`?

Comment (edgchen1) [reply onnxruntime/core/platform/windows/debug_alloc.cc]: yes. here's the definition in DbgHelp.h:

```c++
typedef struct _SYMBOL_INFO_PACKAGE {
    SYMBOL_INFO si;
    CHAR        name[MAX_SYM_NAME + 1];
} SYMBOL_INFO_PACKAGE, *PSYMBOL_INFO_PACKAGE;
```

**Review by snnn — APPROVED** [review]

**Comment by snnn** [comment]
This PR has been included in the `rel-1.22.0` branch. Removing the `release:1.22.0` label.
