### PR TITLE
Remove non-constant input check from ConvActivationFusion

### LINKED ISSUE #24473: ORT aborts when loading the attached model
### Describe the issue

[resnet18.zip](https://github.com/user-attachments/files/19819823/resnet18.zip)

When loading the model, inference session aborts without an informative error message.

### To reproduce

```py
import onnxruntime as ort

ort.InferenceSession("resnet18.onnx")
```

yeilds

```
/opt/rh/gcc-toolset-14/root/usr/include/c++/14/bits/stl_vector.h:1149: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = onnxruntime::NodeArg*; _Alloc = std::allocator<onnxruntime::NodeArg*>; const_reference = onnxruntime::NodeArg* const&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 1, 'python' terminated by signal SIGABRT (Abort)
```

### Urgency

_No response_

### Platform

Linux

### OS Version

ubuntu

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.21.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

_No response_

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

An additional check for non-constant inputs was added to ConvActivationFusion in #20282. This was to avoid fusing an Add in a Conv+Add+Relu that has another non-constant input.

https://github.com/microsoft/onnxruntime/blob/6c8cb6a6d1993f84fcf4008f468a071c0b73aad3/onnxruntime/core/optimizer/conv_activation_fusion.cc#L26-L39

However, this check fails to account for implicit inputs and will read past the end of a node's explicit input defs if any implicit inputs are present.

Moreover, this check is no longer necessary after #19470 removed Conv+Add+Relu fusion from ConvActivationFusion.

This change removes the check and some other unused code.

### Motivation and Context

Fix #24473.

### CODE REVIEW

File: onnxruntime/core/optimizer/conv_activation_fusion.cc [hunk 1]
```diff
@@ -19,24 +19,12 @@ namespace {
 
 #if !defined(ORT_MINIMAL_BUILD)
 namespace selectors {
+
 const Node* GetLoneConsumerNode(const GraphViewer& graph_viewer, const Node& node) {
   if (!optimizer_utils::CheckOutputEdges(graph_viewer.GetGraph(), node, 1)) {
     return nullptr;
   }
```
Comment (skottmckay) [inline onnxruntime/core/optimizer/conv_activation_fusion.cc:26]: Not sure this is enough but that would be an issue with CheckOutputEdges.

````
bool CheckOutputEdges(const Graph& graph, const Node& node, size_t expected_output_edges) {
  if (graph.NodeProducesGraphOutput(node)) {
    return false;
  }

  return node.GetOutputEdgesCount() == expected_output_edges;
}
```

If the output edge is to an implicit input (which it was in this case) I think all bets are off and it has to be treated as unknown how many actual edges there are. You can't fuse with something in a subgraph either.  

Most likely that combination is rare if we're looking to fuse, hence this hasn't blown up before. But I think CheckOutputEdges might need to also check that no edges go to implicit inputs and return false if any do.

**Review by skottmckay — APPROVED** [review]
