### PR TITLE
fix WebAssembly single thread build

### LINKED ISSUE #24924: [Web] Fail to build static Wasm library without multi-thread support
### Describe the issue

Fail to build static Wasm library without multi-thread support. The single-thread static build support is useful for projects that need to static-link with ORT Web but are not able to enable multi-thread.

### To reproduce

Follow the ORT Web build instructions, https://onnxruntime.ai/docs/build/web.html, try to build a static ORT Wasm static library without multi-thread support

Execute the following commend-line:
```shell
$ ./build.sh --config Release --build_wasm_static_lib  --enable_wasm_simd --skip_tests --disable_wasm_exception_catching --disable_rtti
```

Build fails with the following error message:
```shell
[ 30%] Building CXX object CMakeFiles/onnxruntime_mlas.dir/home/nhu/code/onnxruntime/onnxruntime/core/mlas/lib/compute.cpp.o
/home/nhu/code/onnxruntime/onnxruntime/core/mlas/lib/compute.cpp:982:45: error: no member named 'Negate' in 'onnxruntime::MLFloat16'
  982 |         MLAS_FP16 NegativeMaximum = Maximum.Negate();
      |                                     ~~~~~~~ ^
/home/nhu/code/onnxruntime/onnxruntime/core/mlas/lib/compute.cpp:983:47: error: no member named 'IsNegative' in 'onnxruntime::MLFloat16'
  983 |         if (SmoothSoftmax && !NegativeMaximum.IsNegative()) {
      |                               ~~~~~~~~~~~~~~~ ^
/home/nhu/code/onnxruntime/onnxruntime/core/mlas/lib/compute.cpp:984:42: error: no member named 'FromBits' in 'onnxruntime::MLFloat16'
  984 |             NegativeMaximum = MLAS_FP16::FromBits(0);
      |                               ~~~~~~~~~~~^
3 errors generated.
gmake[2]: *** [CMakeFiles/onnxruntime_mlas.dir/build.make:332: CMakeFiles/onnxruntime_mlas.dir/home/nhu/code/onnxruntime/onnxruntime/core/mlas/lib/compute.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:975: CMakeFiles/onnxruntime_mlas.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "/home/nhu/code/onnxruntime/tools/ci_build/build.py", line 2624, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nhu/code/onnxruntime/tools/ci_build/build.py", line 2526, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/nhu/code/onnxruntime/tools/ci_build/build.py", line 1345, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/nhu/code/onnxruntime/tools/ci_build/build.py", line 147, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nhu/code/onnxruntime/tools/python/util/run.py", line 50, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/home/nhu/code/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2.
```

### Urgency

_No response_

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

89a2ff9259a3e566fd98577aff7204e72ec19439

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

### PR DESCRIPTION
**Pull request by fs-eire**
### Description

Fix WebAssembly single thread build, and add a CI job.

Fixes #24924

### CODE REVIEW

**Review by guschmue — DISMISSED** [review]

**Review by hariharans29 — APPROVED** [review]

File: onnxruntime/core/mlas/lib/mlasi.h [hunk 1]
```diff
@@ -261,6 +261,22 @@ struct MLFloat16 {
...
+        return Abs().val > kPositiveInfinityBits;
+    }
+    bool IsNegative() const noexcept {
+        return static_cast<int16_t>(val) < 0;
+    }
+    MLFloat16 Negate() const {
+        return MLFloat16(IsNaN() ? val : static_cast<uint16_t>(val ^ kSignMask));
+    }
+    static constexpr uint16_t kSignMask = 0x8000U;
+    static constexpr uint16_t kPositiveInfinityBits = 0x7F80U;
```
Comment (hariharans29) [inline onnxruntime/core/mlas/lib/mlasi.h]: Isn't this the bit pattern for BFloat16 positive infinity ? (I think Co-pilot has a similar comment about positive infinity bit pattern not being the expected value)

**Review by hariharans29 — COMMENTED** [review]
Resetting vote

**Review by hariharans29 — CHANGES_REQUESTED** [review]
Reseting vote

**Review by hariharans29 — APPROVED** [review]
