### PR TITLE
[Web] Magic import comment missing for Vite (/* @vite-ignore */)

### LINKED ISSUE #25918: [Web] Magic import comment missing for Vite (/* @vite-ignore */)
### Describe the issue

Building an Angular project, using Vite, will log the following warning:
<details>

```
11:56:11 am [vite] (client) warning:
C:/Users/mcost/Documents/Preci/Projects/FrontendLibs/.angular/cache/19.2.15/debugfrontend/vite/deps/onnxruntime-web_all.js
17729|      return (yield import(
17730|        /*webpackIgnore:true*/
17731|        n
     |        ^
17732|      )).default;
17733|    }), fy = (ly(), qn(uy)).default, yy = () => __async(null, null, function* () {
The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

Plugin: vite:import-analysis
```
</details>

`/*webpackIgnore:true*/` is already included for webpack here: https://github.com/microsoft/onnxruntime/blob/5746ba9d3b7b5eaf3a5c64fd24974f3649d71b34/js/web/script/build.ts#L384

It seems like `@vite-ignore` can also be added there. I will create a pull request.

### To reproduce

- Create vite project that creates ONNX ORT session (`onnxruntime-web/all` specifically for me)
- Start vite dev server

### Urgency

No - logged warnings only.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.22.0

### Execution Provider

'webgpu' (WebGPU)

### PR DESCRIPTION
**Pull request by mcost45**
### Description
This is a small change that includes the insertion of the `/* @vite-ignore */` magic comment within the `build.ts` `postProcess` function, alongside `/* webpackIgnore:true */`, for dynamic imports.

`/* @vite-ignore */` suppresses a Vite warning:

> The above dynamic import cannot be analyzed by Vite. See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

, and does not change other behaviour. Note that it must be included as a separate, distinct comment to match the [regexp](https://github.com/vitejs/vite/blob/bcc31449c0c4f852ccb1eedda1842bc7ded23d01/packages/vite/src/node/plugins/importAnalysis.ts#L88).

### Motivation and Context
Resolves #25918. The Vite magic comment should be included because the dynamic imports are intended 'to be left as-is', and the warning cannot otherwise be disabled by an end-user (myself in an Angular project).

### CODE REVIEW

**Comment by mcost45** [comment]
@microsoft-github-policy-service agree

File: js/web/script/build.ts [hunk 1]
```diff
@@ -502,12 +505,12 @@ async function validate() {
...
-      // all files should contain the magic comment to ignore dynamic import calls.
+      // all files should contain the webpack magic comment to ignore dynamic import calls.
       //
       if (!file.includes('.webgl.') && !file.includes('.bundle.')) {
         const contentToSearch = isMinified ? '/*webpackIgnore:true*/' : '/* webpackIgnore: true */';
         if (!content.includes(contentToSearch)) {
-          throw new Error(`Validation failed: "${file}" does not contain magic comment.`);
+          throw new Error(`Validation failed: "${file}" does not contain webpack magic comment.`);
         }
       }
```
Comment (fs-eire) [inline js/web/script/build.ts:508]: please also add a check for vite ignore comment

**Comment by fs-eire** [comment]
please also modify implementation of function `dynamicImportDefault` in js\web\lib\wasm\wasm-utils-import.ts

**Comment by mcost45** [comment]
Thanks @fs-eire, I have made the requested changes.

**Comment by fs-eire** [comment]
please fix the build failure by running `npm run format` and update the formatted file.

**Comment by mcost45** [comment]
@fs-eire formatting was applied.

**Comment by mcost45** [comment]
Hi @fs-eire, I was just wondering if there's anything else I can do, or what would the next steps look like?

**Comment by fs-eire** [comment]
sorry for the late response - looks like the code need to update to latest main branch so that required pipelines can be triggered

**Comment by mcost45** [comment]
Thanks @fs-eire, I just rebased on latest
