### PR TITLE
Handle nodes with subgraphs in ORT function handling implementation

### LINKED ISSUE #1964: Error parsing onnx::range inputs
**Describe the bug**
I have an ONNX model exported as below:

graph(%0 : Float(),
      %1 : Float(),
      %2 : Float()):
  %3 : Tensor = onnx::Cast[to=1](%2), scope: ArangeModel
  %4 : FloatTensor = onnx::Range(%0, %1, %3), scope: ArangeModel
  %5 : Float(7) = onnx::Cast[to=1](%4), scope: ArangeModel 
  return (%5)

The ONNX model does match the specs for Range fundtion. All inputs are of the same type.
I see the following error when running the model.

onnxruntime::FunctionImpl::FunctionImpl(const onnxruntime::Graph&, const NodeIndex&, const onnx::FunctionProto*) status.IsOK() was false. Resolve subgraph failed:This is an invalid model. Error in Node:0x5579ee8c0630_1 : Nodes in a graph must be topologically sorted, however input 'delta' of node:

prev
deltacurrent"Add
 is not output of any previous nodes.

Looks like ORT does not have a kernel implementation for Range yet, and this error is caused when parsing the set of alternative subnodes.

**Urgency**
We wanted to address this issue before kernel implementation for Range is in. Once we have the kernel, we cannot hit the same group of ops to reproduce this issue. 

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- ONNX Runtime version: ort-nightly 0.5.0.dev917
- Python version: 3.7

**To Reproduce**
Try loading and running the onnx model:
https://microsoft-my.sharepoint.com/:f:/p/neraoof/EgIIYkQ7N2xMlrneJJg3qfEBRrZSOoWMm4OFsM2Pf46uFA?e=Fw0aVo

**Additional context**
Just wanted to note that this issue is only caused since the ORT doesn't have a kernel implementation for Range yet. Implementing the kernel will only fix the symptoms here, but we want to look into any potential bugs parsing the set of ops we're hitting currently 
(why is there an error parsing inputs to "Add").

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: The function body handling logic is currently not capable of handling nodes with subgraphs. Thus far, ONNX never had a node with a function body that contained a node with a subgraph. From opset-11, `Range` has a `Loop` node which has a `body` attribute (subgraph) whose inputs/outputs needs the same updating logic applied to the current nodes in the function body.

Even though we will ultimately use a kernel for Range, currently ORT has a step during `Load()` to validate a function body by building the corresponding subgraph associated with it (even if it ultimately does not use it at `Run()` time). Whether this validation step is required is debatable, but given that the validation exists, this gap will prevent models with `Range` nodes in them from loading  

**Motivation and Context**
Resolves #1964

### CODE REVIEW

File: onnxruntime/core/graph/function.cc [hunk 1]
```diff
@@ -83,15 +83,72 @@ void IOTypeConstraintHelper(const ONNX_NAMESPACE::FunctionProto* onnx_func_proto
   }
 }
 
+// This method updates the names of inputs/outputs of nodes in subgraphs
+// within nodes in an op that has a FunctioBody.
```
Comment (skottmckay) [inline onnxruntime/core/graph/function.cc]: >FunctioBody [](start = 36, length = 11)

FunctionBody

**Comment by hariharans29** [comment]
CC: @neginraoof

File: onnxruntime/core/graph/function.cc (hunk 1 above)
Comment (hariharans29) [reply onnxruntime/core/graph/function.cc]: Fixed.

File: onnxruntime/core/graph/function.cc [hunk 2]
```diff
@@ -242,11 +303,9 @@ FunctionImpl::FunctionImpl(const onnxruntime::Graph& graph,
       auto iter = input_name_idx_map.find(tensor_name);
       if (iter != input_name_idx_map.end()) {
         // Preserving NodeArg and input/output names
-        ONNX_NAMESPACE::NodeProto temp_node_proto;
-        node_in_parent_graph->ToProto(temp_node_proto);
-        const onnxruntime::NodeArg* node_arg = parent_graph_->GetNodeArg(temp_node_proto.input().Get(input_name_idx_map[tensor_name]));
+        const onnxruntime::NodeArg* node_arg = parent_graph_->GetNodeArg(function_op_node_proto.input().Get(input_name_idx_map[tensor_name]));
```
Comment (skottmckay) [inline onnxruntime/core/graph/function.cc]: >input_name_idx_map[tensor_name] [](start = 108, length = 31)

Could use *iter instead of doing another lookup.

File: onnxruntime/core/graph/function.cc [hunk 3]
```diff
@@ -83,15 +83,72 @@ void IOTypeConstraintHelper(const ONNX_NAMESPACE::FunctionProto* onnx_func_proto
...
+      }
+    }
+
+    for (auto& attr : subgraph_node.attribute()) {
+      if (attr.has_f()) {
+        ORT_THROW("A node with a function body within a subgraph within another function body is currently not supported in ORT");
+      }
+      // Recurse into any subgraphs in the current subgraph node being processed
+      if (attr.has_g()) {
+        update_subgraph_nodes_within_function_nodes(*const_cast<ONNX_NAMESPACE::AttributeProto&>(attr).mutable_g(),
```
Comment (skottmckay) [inline onnxruntime/core/graph/function.cc]: >*const_cast<ONNX_NAMESPACE::AttributeProto&>( [](start = 52, length = 45)

It would be more truthful to use non-const things in the 'for' loops given you are actually modifying the proto if you hit this (i.e. for (auto& attr : subgraph_node.mutable_attribute()) instead of const_cast (which should in general be avoided).

File: onnxruntime/core/graph/function.cc (hunk 2 above)
Comment (hariharans29) [reply onnxruntime/core/graph/function.cc]: Hmm I fixed the same issue in a couple of other places - will fix this too

File: onnxruntime/core/graph/function.cc (hunk 3 above)
Comment (hariharans29) [reply onnxruntime/core/graph/function.cc]: It doesn't matter what we use in the for loop, I think. When we call attribute(), it returns back const stuff. I think the functionality (could be by design) is limited to get non-const mutable stuff back. Let me explore

File: onnxruntime/test/ir/onnx_model_test.cc [hunk 4]
```diff
@@ -162,5 +162,16 @@ TEST(ONNXModelsTest, TestIRv4NonInputInitializers) {
...
+
+// test a model that has an op with a FunctionBody and one of the nodes within the FunctionBody has a subgraph in it.
+// The test model has is an opset-11 op with a 'Range' node.
+// 'Range' has a FunctionBody and has a 'Loop' node with a subgraph.
+// Graph::Resolve to succeed when processing the subgraph pertaining to the overall FunctionBody.
+TEST(ONNXModelsTest, TestIRv4NonInputInitializers) {
+  std::shared_ptr<Model> model;
+  ASSERT_TRUE(Model::Load("testdata/model_containing_op_with_function_body.onnx", model).IsOK());
+  EXPECT_TRUE(model->MainGraph().Resolve().IsOK());
+}
```
Comment (skottmckay) [inline onnxruntime/test/ir/onnx_model_test.cc]: nit: it's nicer to output the status if this fails
  auto status = model->MainGraph().Resolve();
  EXPECT_TRUE(status.IsOK()) << status;

We probably should have a EXPECT_STATUS_OK macro that does that though for convenience

File: onnxruntime/core/graph/function.cc (hunk 2 above)
Comment (hariharans29) [reply onnxruntime/core/graph/function.cc]: Fixed.

File: onnxruntime/test/ir/onnx_model_test.cc (hunk 4 above)
Comment (hariharans29) [reply onnxruntime/test/ir/onnx_model_test.cc]: Fixed.

File: onnxruntime/core/graph/function.cc (hunk 3 above)
Comment (hariharans29) [reply onnxruntime/core/graph/function.cc]: Fixed.

File: onnxruntime/core/graph/function.cc [hunk 5]
```diff
@@ -133,46 +194,48 @@ FunctionImpl::FunctionImpl(const onnxruntime::Graph& graph,
...
   ORT_ENFORCE(status.IsOK(), status.ErrorMessage());
 }
 
 FunctionImpl::FunctionImpl(const onnxruntime::Graph& graph,
                            const onnxruntime::NodeIndex& node_index,
-                           const ONNX_NAMESPACE::FunctionProto* onnx_func_proto)
+                           const ONNX_NAMESPACE::FunctionProto& onnx_func_proto)
     : parent_graph_(&graph) {
+  // make a copy of the FunctionProto
   onnx_func_proto_ = onnx_func_proto;
```
Comment (skottmckay) [inline onnxruntime/core/graph/function.cc]: Would be good to say why this is important.

**Comment by skottmckay** [comment]
Is there a test that repros the issue with two Range nodes when the proto doesn't get copied? May want to include that to protect against future regressions.

**Comment by hariharans29** [comment]
> Is there a test that repros the issue with two Range nodes when the proto doesn't get copied? May want to include that to protect against future regressions.

The test model that is checked-in is exactly that (with 2 Range nodes). It will break without the copy logic.

File: onnxruntime/core/graph/function.cc (hunk 5 above)
Comment (hariharans29) [reply onnxruntime/core/graph/function.cc]: Per my understanding, all ops with a FunctionBody seem to share the same FunctionBody struct within a model. Hence, mutating one causes issues when there are multiple of the same ops in the graph. I think this is the root cause. Do you agree ?

Comment (hariharans29) [reply onnxruntime/core/graph/function.cc]: Added.
