### PR TITLE
Fix #612, TfidfVectorizer handles empty matrices as an input

### LINKED ISSUE #612: TfidfVectorizer fails with empty strings
**Describe the bug**
I'm trying to write a converter for TfIdfVectorizer when analyser=='char'. I use the regular expression to split a sentance into characters with '.' (does not work) but '[^\\n]' works. With the first one, I get the following error:

INVALID_ARGUMENT : Input shape must have either [C] or [B,C] dimensions where C > 0 and B > 0

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): master branch from github
- ONNX Runtime version: master branch from github
- Python version: 3.7

**To Reproduce**
- clone https://github.com/xadupre/sklearn-onnx/tree/tfc
- run test test_model_tfidf_vectorizer11_dot in tests/test_SklearnTfidfVectorizerConverterChar.py

**Expected behavior**
onnxruntime should return outputs.

### PR DESCRIPTION
**Pull request by xadupre**

### CODE REVIEW

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc [hunk 1]
```diff
@@ -455,28 +455,33 @@ Status TfIdfVectorizer::ComputeImpl(OpKernelContext* ctx) const {
     C = input_dims[0];
     if (C < 1) {
```
Comment (yuslepukhin) [inline onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: >(C < 1)  [](start = 7, length = 8)

Should it be < 0?

File: onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc [hunk 2]
```diff
@@ -293,6 +293,29 @@ TEST(TfIdfVectorizerTest, Int32_TF_UniAndBigrams_Skip5) {
   test.Run(OpTester::ExpectResult::kExpectSuccess);
 }
 
+TEST(TfIdfVectorizerTest, Int32_TF_UniAndBigrams_Skip5Empty) {
```
Comment (yuslepukhin) [inline onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc]: >TEST(TfIdfVectorizer [](start = 0, length = 20)

Need a test with input shape [0] (one dimension)

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc (hunk 1 above)
Comment (xadupre) [reply onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: I did not change it because I did not need to. In my case, I distinguish between empty input with shape {0} and empty input with shape {B, 0} with B > 0. Shape {B,0} with B > 0 is produced by the previous operator when it cannot compute any output for every input observation but it keeps the number of processed observations. The first one (shape={0}) means there was no data to begin with, the first dimension usually denotes the number of observations to process. Shape {0} could be unexpectdly produced by a previous operator if it removes observations (like a filter). I think if we allow this case, we might have to allow it in every operator.

Comment (yuslepukhin) [reply onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: The code is not readable now, plus, frequencies are allocated using artificial dimension of b_dim = 1 in that case. So you want to redo the code in a different way.

---
In reply to: [268783844](https://github.com/Microsoft/onnxruntime/pull/702#discussion_r268783844) [](ancestors = 268783844)

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc [hunk 3]
```diff
@@ -455,28 +455,33 @@ Status TfIdfVectorizer::ComputeImpl(OpKernelContext* ctx) const {
...
-
   // Frequency holder allocate [B..output_size_]
   // and init all to zero
   std::vector<uint32_t> frequencies;
   frequencies.resize(b_dim * impl.output_size_, 0);
 
+  if (input_shape.Size() == 0) {
+    OutputResult(ctx, B, frequencies);
+    return Status::OK();
+  }
```
Comment (yuslepukhin) [inline onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: Let's move this section UP before the frequencies and output the desired shape w/o using OutputResult(). OutputResult() is for processing a non-empty input which may result in empty output.

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc (hunk 1 above)
Comment (wschin) [reply onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: @Xavier, I feel supporting input shape [0] is reasonable. What if user just have to have a vector/count representation of a single document? I guess [0] is a valid possibility in that case.

---
In reply to: [268789799](https://github.com/Microsoft/onnxruntime/pull/702#discussion_r268789799) [](ancestors = 268789799,268783844)

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc [hunk 4]
```diff
@@ -455,28 +455,33 @@ Status TfIdfVectorizer::ComputeImpl(OpKernelContext* ctx) const {
...
       return Status(common::ONNXRUNTIME, common::INVALID_ARGUMENT,
-                    "Input shape must have either [C] or [B,C] dimensions where C > 0 and B > 0");
+                    "Input shape must have either [C] or [B,C] dimensions where C >= 0 and B > 0");
     }
   } else if (input_dims.size() == 2) {
     B = input_dims[0];
     C = input_dims[1];
     b_dim = B;
-    if (B < 1 || C < 1) {
+    if (B < 1 || C < 0) {
```
Comment (wschin) [inline onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: >B < 1 [](start = 8, length = 5)

Should it be `B > 0` plus `C == 0`?

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc [hunk 5]
```diff
@@ -455,28 +455,33 @@ Status TfIdfVectorizer::ComputeImpl(OpKernelContext* ctx) const {
...
   }
 
-  assert((b_dim * C) == total_items);
-
   // Frequency holder allocate [B..output_size_]
   // and init all to zero
   std::vector<uint32_t> frequencies;
   frequencies.resize(b_dim * impl.output_size_, 0);
 
+  if (input_shape.Size() == 0) {
```
Comment (wschin) [inline onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: Could we have some comments?

File: onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc (hunk 2 above)
Comment (xadupre) [reply onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc]: done

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc (hunk 5 above)
Comment (xadupre) [reply onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: done

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc (hunk 1 above)
Comment (xadupre) [reply onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: You can see the current behaviour in the unit test (look for substring empty).

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc [hunk 6]
```diff
@@ -453,30 +453,36 @@ Status TfIdfVectorizer::ComputeImpl(OpKernelContext* ctx) const {
...
+    // TfidfVectorizer may receive an empty input when it follows a Tokenizer
+    // (for example for a string containing only stopwords).
+    // The operator returns an output with null values of shape
```
Comment (wschin) [inline onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: Not sure if my understanding is correct, so I try polishing this comment a bit. Feel free to ignore.
```suggestion
    // TfidfVectorizer returns a zero tensor of shape
```

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc [hunk 7]
```diff
@@ -453,30 +453,36 @@ Status TfIdfVectorizer::ComputeImpl(OpKernelContext* ctx) const {
...
+    // {b_dim, output_size} when b_dim is the number of received observations
+    // and output_size the number of distinct tokens.
```
Comment (wschin) [inline onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]:
```suggestion
    // and output_size is the maximum value in ngram_indexes attribute plus 1.
```

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc [hunk 8]
```diff
@@ -453,30 +453,36 @@ Status TfIdfVectorizer::ComputeImpl(OpKernelContext* ctx) const {
...
   // Frequency holder allocate [B..output_size_]
   // and init all to zero
   std::vector<uint32_t> frequencies;
   frequencies.resize(b_dim * impl.output_size_, 0);
 
+  if (input_shape.Size() == 0) {
+    // TfidfVectorizer may receive an empty input when it follows a Tokenizer
+    // (for example for a string containing only stopwords).
+    // The operator returns an output with null values of shape
+    // {b_dim, output_size} when b_dim is the number of received observations
```
Comment (wschin) [inline onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: Sounds like input is always a 2-D tensor?

File: onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc [hunk 9]
```diff
@@ -70,6 +70,95 @@ TEST(TfIdfVectorizerTest, Int32_TF_onlyBigrams_Skip0) {
...
+
+  std::vector<int64_t> dims{0};
+  std::vector<int32_t> input = {};
+  test.AddInput<int32_t>("T", dims, input);
+
+  std::vector<int64_t> out_dims{0};
+  std::vector<float> output = {};
+  test.AddOutput<float>("Y", out_dims, output);
+
+  test.Run(OpTester::ExpectResult::kExpectFailure);
```
Comment (wschin) [inline onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc]: Do we also have a test (it may fail) with input shape [0, 1]? If no, please help adding one. Thanks.

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc (hunk 8 above)
Comment (xadupre) [reply onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: yes

File: onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc (hunk 7 above)
Comment (xadupre) [reply onnxruntime/core/providers/cpu/nn/tfidfvectorizer.cc]: done

File: onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc (hunk 9 above)
Comment (xadupre) [reply onnxruntime/test/providers/cpu/nn/tfidfvectorizer_test.cc]: done
