### PR TITLE
[Java] JNI refactor for OrtJniUtil

### LINKED ISSUE #11451: JAVA API does not handle exceptions correctly - causing crash or potential memory leak
**Describe the bug**
I found this bug when I try to create a React Native app targeting Android. The current Java API does not handle exceptions correctly: If an input tensor with wrong shape is passed to `OrtRun()`, the design behavior is to throw an exception of type `OrtException`(Java), but instead it crashes silently.

After debugging into the JNI implementation, I found this code line:
https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/ai_onnxruntime_OrtSession.c#L288

This is the actual call to C-API of OrtRun(). The call is wrapped in a helper function `checkOrtStatus()`. And this is where the problem occurred.

Looking at the implementation of `checkOrtStatus()`, it calls `throwOrtException()`:

https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/OrtJniUtil.c#L1032-L1045

https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/OrtJniUtil.c#L990-L999

Here is the explanation of the problem:

The `env->Throw()` sets status of Java environment, but does not return or throw in C/C++ context. It always continue to execute the rest code in the function. This causes the behavior of function `checkOrtStatus()` behaves differently to macros like `ORT_ENFORCE()` or `ORT_API_RETURN_IF_ERROR`, which guarantees further code will not be executed (via either return or throw C++ exceptions/abort()).

Line 300 will have undefined behavior if the `OrtRun()` fails.
https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/ai_onnxruntime_OrtSession.c#L288-L304

I have a workaround to mitigate this issue for my usage. However this is not a complete fix for this issue. A complete fix should carefully check after every ORT API calls and make sure errors being handled correctly.

@craigacp

**Urgency**
If users don't generate any non-zero OrtStatus in all the API calls to ORT, they will not be impacted. Otherwise there is risk for potential memory leak or crash.

**System information**
- OS Platform and Distribution: Windows 10 21H2 (19044.1645)
- Java: 11

**To Reproduce**
- This branch contains the code to reproduce the issue: https://github.com/fs-eire/ort-rn-hello-world/tree/fs-eire/wrong-dimension

### PR DESCRIPTION
**Pull request by Craigacp**
**Description**:

Following on from #12013, #12281 and #12496 this PR fixes the JNI error handling in OrtJniUtil. The refactor of all the JNI code should be complete now. I'll revise the sparse tensor PR (#10653) after this has been merged as it touches many of the same parts of the code.

This change is independent of https://github.com/microsoft/onnxruntime/pull/12496.

**Motivation and Context**
- Why is this change required? What problem does it solve? Improves error handling in the Java<->native bridge.
- If it fixes an open issue, please link to the issue here. This change and #12496 should fix #11451.

### CODE REVIEW

**Comment by fs-eire** [comment]
after a sequence of changes, the exception handling is getting correct. however, before closing the issue we need to add some test cases ( which intentionally trigger exceptions ) and we need to check if the exception handling is working as expected. As we are doing changes in different PRs (https://github.com/microsoft/onnxruntime/pull/12013, https://github.com/microsoft/onnxruntime/pull/12281, https://github.com/microsoft/onnxruntime/pull/12496 and this one). You can do it separately. but we need the tests to make sure the code changes work and also to ensure it is not broken by future changes.

**Comment by Craigacp** [comment]
> after a sequence of changes, the exception handling is getting correct. however, before closing the issue we need to add some test cases ( which intentionally trigger exceptions ) and we need to check if the exception handling is working as expected. As we are doing changes in different PRs (#12013, #12281, #12496 and this one). You can do it separately. but we need the tests to make sure the code changes work and also to ensure it is not broken by future changes.

I would do if I could replicate the issue in Java, but I can't. When I call `session.run` with a tensor with the incorrect shape I get the expected exception back and the JVM continues running. I think it's something about how Android implements the JNI spec, but I don't have an Android environment to test it in.

There are already tests which supply the wrong type or number of inputs into `session.run` and check that the appropriate exception is thrown.

I ran a quick test in jshell using v1.12.1 and for the following program:
```java
import ai.onnxruntime.*;
var env = OrtEnvironment.getEnvironment();
var session = env.createSession("<path-to-an-mnist-cnn-model>");
float[] input = new float[56];
var tensor = OnnxTensor.createTensor(env,input);
var outputs = session.run(Map.of("input_image",tensor));
```
I get the expected exception:
```
|  Exception ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Invalid rank for input: input_image Got: 1 Expected: 4 Please fix either the inputs or the model.
|        at OrtSession.run (Native Method)
|        at OrtSession.run (OrtSession.java:295)
|        at OrtSession.run (OrtSession.java:238)
|        at OrtSession.run (OrtSession.java:207)
```
and if I change the tensor so it's the right rank, but still has 56 elements rather than 784 I get:
```
|  Exception ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Got invalid dimensions for input: input_image for the following indices
 index: 1 Got: 2 Expected: 1
 index: 2 Got: 4 Expected: 28
 index: 3 Got: 7 Expected: 28
 Please fix either the inputs or the model.
|        at OrtSession.run (Native Method)
|        at OrtSession.run (OrtSession.java:295)
|        at OrtSession.run (OrtSession.java:238)
|        at OrtSession.run (OrtSession.java:207)
```
again, as expected.

**Comment by fs-eire** [comment]
> When I call `session.run` with a tensor with the incorrect shape I get the expected exception back and the JVM continues running. I think it's something about how Android implements the JNI spec, but I don't have an Android environment to test it in.

Could you please help to add test cases in react_native\android\src\androidTest\java\ai\onnxruntime\reactnative\OnnxruntimeModuleTest.java ? If you don't have the Android environment, we can leverage the CI to test it.

**Comment by Craigacp** [comment]
> > When I call `session.run` with a tensor with the incorrect shape I get the expected exception back and the JVM continues running. I think it's something about how Android implements the JNI spec, but I don't have an Android environment to test it in.
> 
> Could you please help to add test cases in react_native\android\src\androidTest\java\ai\onnxruntime\reactnative\OnnxruntimeModuleTest.java ? If you don't have the Android environment, we can leverage the CI to test it.

Sure. The Java code in there looks a little odd, is there some guidance on which bits of the JDK I can expect to work? It looks like it's using different `Map` and `List` implementations.

**Comment by fs-eire** [comment]
> > > When I call `session.run` with a tensor with the incorrect shape I get the expected exception back and the JVM continues running. I think it's something about how Android implements the JNI spec, but I don't have an Android environment to test it in.
> > 
> > 
> > Could you please help to add test cases in react_native\android\src\androidTest\java\ai\onnxruntime\reactnative\OnnxruntimeModuleTest.java ? If you don't have the Android environment, we can leverage the CI to test it.
> 
> Sure. The Java code in there looks a little odd, is there some guidance on which bits of the JDK I can expect to work? It looks like it's using different `Map` and `List` implementations.

There are some types import from React Native data bridge:
```java
import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.JavaOnlyArray;
import com.facebook.react.bridge.JavaOnlyMap;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
```

Those are defined in react native for inter-op between Java and JavaScript.
https://github.com/facebook/react-native/tree/main/ReactAndroid/src/main/java/com/facebook/react/bridge

I am using OpenJDK 11 + Android Studio Bumblebee

**Comment by Craigacp** [comment]
I made a PR with some new tests for the react-native portion #12659.

**Comment by Craigacp** [comment]
@yuslepukhin please could you review this PR? It's the last one to finish off the JNI refactor.

File: java/src/main/java/ai/onnxruntime/MapInfo.java [hunk 1]
```diff
@@ -42,6 +44,21 @@ public class MapInfo implements ValueInfo {
...
+   */
+  MapInfo(int size, int keyTypeInt, int valueTypeInt) {
+    this.size = size;
+    this.keyType = OnnxJavaType.mapFromOnnxTensorType(OnnxTensorType.mapFromInt(keyTypeInt));
+    this.valueType = OnnxJavaType.mapFromOnnxTensorType(OnnxTensorType.mapFromInt(valueTypeInt));
+  }
+
   @Override
   public String toString() {
     String initial = size == -1 ? "MapInfo(size=UNKNOWN" : "MapInfo(size=" + size;
```
Comment (yuslepukhin) [inline java/src/main/java/ai/onnxruntime/MapInfo.java:64]: >size == -1 [](http://example.com/codeflow?start=21&length=10)

How is the user to interpret the size of -1? Like I read size and it is -1, what am I going to do?

**Comment by yuslepukhin** [comment]
>   public final boolean sequenceOfMaps;

Generally, ONNX gives a recursive definition of it. It can be a sequence of sequences etc.

---
Refers to: java/src/main/java/ai/onnxruntime/SequenceInfo.java:13 in 15a1044. [](commit_id = 15a104400795e7ad61f9fd3e404a72dad922dca1, deletion_comment = False)

File: java/src/main/java/ai/onnxruntime/MapInfo.java (hunk 1 above)
Comment (Craigacp) [reply java/src/main/java/ai/onnxruntime/MapInfo.java:64]: It's -1 when the info is generated by `session.getOutputInfo` as we don't know the size of the map without executing the model. At all other times the size is set to whatever the map size is.

Comment (yuslepukhin) [reply java/src/main/java/ai/onnxruntime/MapInfo.java:64]: Well, it is a piece of the metadata. ONNX definition does not include any length, it simply does not exist.

Comment (Craigacp) [reply java/src/main/java/ai/onnxruntime/MapInfo.java:64]: Sure, but this class is two things, the first is a description of the model's output that we know a priori, and the second is the description of a specific ONNX map object. In the latter case I think it's useful to report the size in the toString.

File: java/src/main/java/ai/onnxruntime/TensorInfo.java [hunk 2]
```diff
@@ -120,6 +120,20 @@ public static OnnxTensorType mapFromJavaType(OnnxJavaType type) {
...
+  /**
+   * Constructs a TensorInfo with the specified shape and native type int.
+   *
+   * <p>Called from JNI.
+   *
+   * @param shape The tensor shape.
+   * @param typeInt The native type int.
+   */
+  TensorInfo(long[] shape, int typeInt) {
+    this.shape = shape;
```
Comment (yuslepukhin) [inline java/src/main/java/ai/onnxruntime/TensorInfo.java:132]: >  this.shape = shape; [](http://example.com/codeflow?start=2&length=21)

Also metadata does not really include a literal shape. It may have symbolic values. Real numeric shape is inferred at runtime and as such may not be a part of the info.
[https://github.com/onnx/onnx/blob/main/onnx/onnx-ml.proto#L648](https://github.com/onnx/onnx/blob/main/onnx/onnx-ml.proto#L648)

File: java/src/main/native/OrtJniUtil.h [hunk 3]
```diff
@@ -43,22 +43,20 @@
...
 
-jobject createEmptyMapInfo(JNIEnv *jniEnv);
-jobject createEmptySequenceInfo(JNIEnv *jniEnv);
+jobject convertToSequenceInfo(JNIEnv *jniEnv, const OrtApi * api, const OrtSequenceTypeInfo * info);
 
-size_t copyJavaToPrimitiveArray(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, jarray input);
+int64_t copyJavaToPrimitiveArray(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, jarray input);
 
-size_t copyJavaToTensor(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, size_t tensorSize, size_t dimensionsRemaining, jarray input);
+int64_t copyJavaToTensor(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, size_t tensorSize, size_t dimensionsRemaining, jarray input);
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.h:51]: >uint8_t* tensor [](http://example.com/codeflow?start=77&length=15)

it should const uint8_t* to so the compiler can enforce the source data is not modified.

File: java/src/main/native/OrtJniUtil.c [hunk 4]
```diff
@@ -220,225 +221,207 @@ jfloat convertHalfToFloat(uint16_t half) {
 }
 
 jobject convertToValueInfo(JNIEnv *jniEnv, const OrtApi * api, OrtTypeInfo * info) {
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:223]: >OrtTypeInfo * info [](http://example.com/codeflow?start=63&length=18)

Should this be a const qualified so it is not modified and it is clear to be an input parameter?

Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:223]: Sure.

File: java/src/main/native/OrtJniUtil.h (hunk 3 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.h:51]: Ok.

File: java/src/main/java/ai/onnxruntime/TensorInfo.java (hunk 2 above)
Comment (Craigacp) [reply java/src/main/java/ai/onnxruntime/TensorInfo.java:132]: See this comment https://github.com/microsoft/onnxruntime/pull/12516#discussion_r960031262. I could split them into two separate classes for each use case, but that seems wasteful as the information is mostly duplicated, or I could try and push the size information into the ONNX value classes themselves. But both of those are a more substantial refactor as it'll touch all the Java side stuff too, and I'm not convinced of the value of that.

Comment (Craigacp) [reply java/src/main/java/ai/onnxruntime/TensorInfo.java:132]: This way it roughly mirrors the TypeInfo class and the information that contains.

File: java/src/main/native/OrtJniUtil.c [hunk 5]
```diff
@@ -220,225 +221,207 @@ jfloat convertHalfToFloat(uint16_t half) {
...
+  size_t numDim = 0;
+  code = checkOrtStatus(jniEnv, api, api->GetDimensionsCount(info, &numDim));
+  if (code != ORT_OK) {
+    return NULL;
+  }
+  //printf("numDim %d\n",numDim);
+  int64_t* dimensions = (int64_t*) malloc(sizeof(int64_t)*numDim);
+  code = checkOrtStatus(jniEnv, api, api->GetDimensions(info, dimensions, numDim));
+  if (code != ORT_OK) {
+    return NULL;
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:284]: >return NULL; [](http://example.com/codeflow?start=4&length=12)

dimensions are leaked.
One way to handle this is to declare a fixed array on the stack. Our max shape is actually 5. You can also make it 10, it does not matter for such small things. This way no need to free it.

File: java/src/main/native/OrtJniUtil.c [hunk 6]
```diff
@@ -220,225 +221,207 @@ jfloat convertHalfToFloat(uint16_t half) {
...
+  // tensor types, map<string,float> and map<long,float>
+  OrtTypeInfo* elementTypeInfo = NULL;
+  OrtErrorCode code = checkOrtStatus(jniEnv, api, api->GetSequenceElementType(info, &elementTypeInfo));
+  if (code != ORT_OK) {
+    return NULL;
+  }
+  ONNXType type;
+  code = checkOrtStatus(jniEnv, api, api->GetOnnxTypeFromTypeInfo(elementTypeInfo, &type));
+  if (code != ORT_OK) {
+    return NULL;
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:366]: > return NULL; [](http://example.com/codeflow?start=3&length=13)

elementTypeInfo leaking?

File: java/src/main/native/OrtJniUtil.h (hunk 3 above)
Comment (yuslepukhin) [reply java/src/main/native/OrtJniUtil.h:51]: I take this one back. tensor is the destination. Could you, please, place this parameter last?

File: java/src/main/native/OrtJniUtil.c [hunk 7]
```diff
@@ -504,12 +487,12 @@ size_t copyJavaToPrimitiveArray(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
             throwOrtException(jniEnv, convertErrorCode(ORT_INVALID_ARGUMENT), "Invalid tensor element type.");
-            return 0;
+            return -1;
         }
     }
 }
 
-size_t copyJavaToTensor(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, size_t tensorSize,
+int64_t copyJavaToTensor(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, size_t tensorSize,
                         size_t dimensionsRemaining, jarray input) {
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:496]: I will need docs before I can review this function.

File: java/src/main/native/OrtJniUtil.c [hunk 8]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+      // If we failed to copy an array then break and return.
+      if (consumed == -1) {
+        return -1;
+      }
     }
+    return sizeConsumed;
+  }
 }
 
 jobject createStringFromStringTensor(JNIEnv *jniEnv, const OrtApi * api, OrtAllocator* allocator, OrtValue* tensor) {
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:622]: >OrtValue* tenso [](http://example.com/codeflow?start=98&length=15)

Is this an input parameter?

File: java/src/main/java/ai/onnxruntime/TensorInfo.java (hunk 2 above)
Comment (yuslepukhin) [reply java/src/main/java/ai/onnxruntime/TensorInfo.java:132]: That's the issue. I can not mirror that. The proto shape may include symbolic entries (strings) and it may potentially have a dimension entry that is empty. Such shapes denote the rank, but may not have an information on the dimension. This way we can match all shapes of the same rank.

File: java/src/main/native/OrtJniUtil.h [hunk 9]
```diff
@@ -43,22 +43,20 @@
...
 
-size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, jarray output);
+int64_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, jarray output);
 
-size_t copyTensorToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, size_t tensorSize, size_t dimensionsRemaining, jarray output);
+int64_t copyTensorToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint8_t* tensor, size_t tensorSize, size_t dimensionsRemaining, jarray output);
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.h:56]: It might be valuable to note that these functions assume ORT data is always in CPU allocated memory.

File: java/src/main/native/OrtJniUtil.c [hunk 10]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+  OrtErrorCode code = checkOrtStatus(jniEnv, api, api->GetStringTensorDataLength(tensor, &totalStringLength));
+  if (code != ORT_OK) {
+    return NULL;
+  }
 
+  // Create the character and offset buffers, character is one larger to allow zero termination.
+  char * characterBuffer = NULL;
+  code = checkOrtStatus(jniEnv, api, api->AllocatorAlloc(allocator, sizeof(char)*(totalStringLength+1), (void**)&characterBuffer));
+  if (code != ORT_OK) {
+    return NULL;
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:635]: Just like in other cases, we can replace with malloc/free for simpler code and greater clarify. The allocator parameter is not really necessary since we always operate with CPU based memory.

File: java/src/main/native/OrtJniUtil.c [hunk 11]
```diff
@@ -518,22 +501,27 @@ size_t copyJavaToTensor(JNIEnv *jniEnv, ONNXTensorElementDataType onnxType, uint
...
+            jarray childArr = (jarray) (*jniEnv)->GetObjectArrayElement(jniEnv, inputObjArr, i);
+            int64_t consumed = copyJavaToTensor(jniEnv, onnxType, tensor + sizeConsumed, tensorSize - sizeConsumed, dimensionsRemaining - 1, childArr);
+            sizeConsumed += consumed;
             // Cleanup reference to childArr so it doesn't prevent GC.
-            (*jniEnv)->DeleteLocalRef(jniEnv,childArr);
+            (*jniEnv)->DeleteLocalRef(jniEnv, childArr);
+            // If we failed to copy an array then break and return.
+            if (consumed == -1) {
+              return -1;
+            }
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:515]: Should we throw here?

File: java/src/main/native/OrtJniUtil.c [hunk 12]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+    for (int32_t i = 0; i < dimLength; i++) {
+      jarray childArr = (jarray) (*jniEnv)->GetObjectArrayElement(jniEnv, outputObjArr, i);
+      int64_t consumed = copyTensorToJava(jniEnv, onnxType, tensor + sizeConsumed, tensorSize - sizeConsumed, dimensionsRemaining - 1, childArr);
+      sizeConsumed += consumed;
+      // Cleanup reference to childArr so it doesn't prevent GC.
+      (*jniEnv)->DeleteLocalRef(jniEnv, childArr);
+      // If we failed to copy an array then break and return.
+      if (consumed == -1) {
+        return -1;
+      }
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:616]: Should we throw here?

File: java/src/main/native/OrtJniUtil.c [hunk 13]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+    OrtErrorCode code = checkOrtStatus(jniEnv, api, api->GetStringTensorDataLength(tensor, &totalStringLength));
+    if (code != ORT_OK) {
+        return code;
+    }
 
     // Create the character and offset buffers
-    char * characterBuffer;
-    checkOrtStatus(jniEnv,api,api->AllocatorAlloc(allocator,sizeof(char)*(totalStringLength+length),(void**)&characterBuffer));
+    char * characterBuffer = NULL;
+    code = checkOrtStatus(jniEnv, api, api->AllocatorAlloc(allocator, sizeof(char)*(totalStringLength+length), (void**)&characterBuffer));
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:674]: >, api->AllocatorAlloc(allocator, sizeof(char)*(totalStringLength+length) [](http://example.com/codeflow?start=37&length=72)

Let's replace it with malloc/free

File: java/src/main/native/OrtJniUtil.c [hunk 14]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+                if (curSize > bufferSize) {
+                    code = checkOrtStatus(jniEnv, api, api->AllocatorFree(allocator, tempBuffer));
+                    if (code != ORT_OK) {
+                        goto string_tensor_cleanup;
+                    }
+                    code = checkOrtStatus(jniEnv, api, api->AllocatorAlloc(allocator, curSize, (void**)&tempBuffer));
+                    bufferSize = curSize;
+                }
+                if (tempBuffer == NULL) {
+                    throwOrtException(jniEnv, 1, "Not enough memory");
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:704]: This should have been already checked/reported by checkOrtStatus above? Also tempBuffer is  allocated only conditionally.
Should we move this check closer to line 700.

File: java/src/main/native/OrtJniUtil.c [hunk 15]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+            size_t bufferSize = 0;
+            for (size_t i = 0; i < length; i++) {
+                size_t curSize = (offsets[i+1] - offsets[i]) + 1;
+                if (curSize > bufferSize) {
+                    code = checkOrtStatus(jniEnv, api, api->AllocatorFree(allocator, tempBuffer));
+                    if (code != ORT_OK) {
+                        goto string_tensor_cleanup;
+                    }
+                    code = checkOrtStatus(jniEnv, api, api->AllocatorAlloc(allocator, curSize, (void**)&tempBuffer));
+                    bufferSize = curSize;
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:701]: > bufferSize = curSize; [](http://example.com/codeflow?start=19&length=22)

This should only be set on success of the allocation.

File: java/src/main/native/OrtJniUtil.c [hunk 16]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+    if (code != ORT_OK) {
+        return code;
+    }
     // length + 1 as we need to write out the final offset
-    size_t * offsets;
-    checkOrtStatus(jniEnv,api,api->AllocatorAlloc(allocator,sizeof(size_t)*(length+1),(void**)&offsets));
+    size_t * offsets = NULL;
+    code = checkOrtStatus(jniEnv, api, api->AllocatorAlloc(allocator, sizeof(size_t)*(length+1), (void**)&offsets));
+    if (code != ORT_OK) {
+        checkOrtStatus(jniEnv,api,api->AllocatorFree(allocator,characterBuffer));
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:682]: >checkOrtStatus(jniEnv,api,api->AllocatorFree(allocator,characterBuffer)); [](http://example.com/codeflow?start=8&length=73)

This swallows the allocation error exception which is more interesting than potential deallocation error.

File: java/src/main/native/OrtJniUtil.c [hunk 17]
```diff
@@ -600,427 +588,473 @@ size_t copyPrimitiveArrayToJava(JNIEnv *jniEnv, ONNXTensorElementDataType onnxTy
...
+  OrtErrorCode code = checkOrtStatus(jniEnv, api, api->GetTensorTypeAndShape(tensor, &info));
+  if (code != ORT_OK) {
+    return NULL;
+  }
 
-    // Release the info object
+  // Construct the TensorInfo object
+  jobject tensorInfo = convertToTensorInfo(jniEnv, api, info);
+  if (tensorInfo == NULL) {
     api->ReleaseTensorTypeAndShapeInfo(info);
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:858]: > api->ReleaseTensorTypeAndShapeInfo(info); [](http://example.com/codeflow?start=3&length=42)

This seems to be release in both cases error and success. Perhaps, we can release it before check for null.

**Review by yuslepukhin — CHANGES_REQUESTED** [review]
:clock1:

File: java/src/main/java/ai/onnxruntime/TensorInfo.java (hunk 2 above)
Comment (Craigacp) [reply java/src/main/java/ai/onnxruntime/TensorInfo.java:132]: Ok, but that's a different refactor to this one, as I'll need to allow support for named dimensions in this object. At the moment I think they are just returned as -1 in the input/output info, as that's what `GetDimensions` returns.

File: java/src/main/native/OrtJniUtil.c (hunk 6 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:366]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 5 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:284]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 11 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:515]: `copyJavaToPrimitiveArray` has already thrown if we get -1 here, so we're just unwinding the stack.

File: java/src/main/native/OrtJniUtil.c (hunk 12 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:616]: Same as above, `copyPrimitiveArrayToJava` has already thrown if we have a -1 here.

File: java/src/main/native/OrtJniUtil.c (hunk 10 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:635]: Sure.

File: java/src/main/native/OrtJniUtil.c (hunk 13 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:674]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 16 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:682]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 15 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:701]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 14 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:704]: I rearranged it. It's a little messy as the first allocation is unconditional but we don't know how big it is until we get into the loop so it looks conditional. It looks a bit cleaner now.

File: java/src/main/native/OrtJniUtil.c (hunk 17 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:858]: Fixed.

File: java/src/main/native/OrtJniUtil.h (hunk 9 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.h:56]: Yeah, so when I asked about that originally I was told that any `OrtValue` visible through the C API would be in CPU memory. I think that's changed now, but I'm not sure how to check what address space any given `OrtValue` is in.

File: java/src/main/native/OrtJniUtil.h (hunk 3 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.h:51]: Done

File: java/src/main/native/OrtJniUtil.c [hunk 18]
```diff
@@ -213,814 +214,833 @@ typedef union FP32 {
...
             return consumedSize;
         }
         case ONNX_TENSOR_ELEMENT_DATA_TYPE_COMPLEX64:   // complex with float32 real and imaginary components
         case ONNX_TENSOR_ELEMENT_DATA_TYPE_COMPLEX128:  // complex with float64 real and imaginary components
         case ONNX_TENSOR_ELEMENT_DATA_TYPE_BFLOAT16:    // Non-IEEE floating-point format based on IEEE754 single-precision
         case ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED:
         default: {
-            throwOrtException(jniEnv, convertErrorCode(ORT_NOT_IMPLEMENTED), "Invalid tensor element type.");
-            return 0;
+            throwOrtException(jniEnv, convertErrorCode(ORT_NOT_IMPLEMENTED), "Invalid inputTensor element type.");
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:589]: >type."); [](http://example.com/codeflow?start=106&length=8)

It would be helpful in support cases to include the actual invalid type.

File: java/src/main/native/OrtJniUtil.c [hunk 19]
```diff
@@ -213,814 +214,833 @@ typedef union FP32 {
...
+      // If we failed to copy an array then break and return.
+      if (consumed == -1) {
+        return -1;
+      }
     }
+    return sizeConsumed;
+  }
 }
 
 jobject createStringFromStringTensor(JNIEnv *jniEnv, const OrtApi * api, OrtAllocator* allocator, OrtValue* tensor) {
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:621]: >OrtAllocator* allocator [](http://example.com/codeflow?start=73&length=23)

This becomes unused parameter?

File: java/src/main/native/OrtJniUtil.c [hunk 20]
```diff
@@ -213,814 +214,833 @@ typedef union FP32 {
...
+string_tensor_cleanup:
+  if (tempBuffer != NULL) {
+    free((void*)tempBuffer);
+  }
+  free((void*)offsets);
+  free((void*)characterBuffer);
+  return code;
 }
 
 jobjectArray createStringArrayFromTensor(JNIEnv *jniEnv, const OrtApi * api, OrtAllocator* allocator, OrtValue* tensor) {
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:714]: >allocator [](http://example.com/codeflow?start=91&length=9)

No longer needed ?

File: java/src/main/native/OrtJniUtil.c [hunk 21]
```diff
@@ -213,814 +214,833 @@ typedef union FP32 {
...
-    size_t totalStringLength;
-    checkOrtStatus(jniEnv,api,api->GetStringTensorDataLength(tensor,&totalStringLength));
-
-    // Create the character and offset buffers
-    char * characterBuffer;
-    checkOrtStatus(jniEnv,api,api->AllocatorAlloc(allocator,sizeof(char)*(totalStringLength+length),(void**)&characterBuffer));
-    // length + 1 as we need to write out the final offset
-    size_t * offsets;
-    checkOrtStatus(jniEnv,api,api->AllocatorAlloc(allocator,sizeof(size_t)*(length+1),(void**)&offsets));
+OrtErrorCode copyStringTensorToArray(JNIEnv *jniEnv, const OrtApi * api, OrtAllocator* allocator, OrtValue* tensor, size_t length, jobjectArray outputArray) {
```
Comment (yuslepukhin) [inline java/src/main/native/OrtJniUtil.c:654]: >allocator [](http://example.com/codeflow?start=87&length=9)

Not needed

File: java/src/main/native/OrtJniUtil.c (hunk 18 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:589]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 19 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:621]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 20 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:714]: Fixed.

File: java/src/main/native/OrtJniUtil.c (hunk 21 above)
Comment (Craigacp) [reply java/src/main/native/OrtJniUtil.c:654]: Fixed.

**Comment by yuslepukhin** [comment]
>   OrtAllocator* allocator = (OrtAllocator*)allocatorHandle;

I can see that now this change rips in multiple layers, even though it was a utility function implementation detail. I suggest remove line 19 and comment out allocatorHandle name like this `jlong /* allocatorHandle */` so we do not remove it altogether, perhaps it might be useful in the future.

---
Refers to: java/src/main/native/ai_onnxruntime_OnnxMap.c:19 in 76734a5. [](commit_id = 76734a56b9972c5914e9036f2c5aa7b2c5847870, deletion_comment = False)

**Comment by yuslepukhin** [comment]
>   OrtAllocator* allocator = (OrtAllocator*)allocatorHandle;

Same as above

---
Refers to: java/src/main/native/ai_onnxruntime_OnnxMap.c:69 in 76734a5. [](commit_id = 76734a56b9972c5914e9036f2c5aa7b2c5847870, deletion_comment = False)

**Comment by yuslepukhin** [comment]
>   OrtAllocator* allocator = (OrtAllocator*)allocatorHandle;

remove and comment out the parameter

---
Refers to: java/src/main/native/ai_onnxruntime_OnnxSequence.c:19 in 76734a5. [](commit_id = 76734a56b9972c5914e9036f2c5aa7b2c5847870, deletion_comment = False)

**Review by yuslepukhin — DISMISSED** [review]

**Comment by Craigacp** [comment]
I can replicate that Windows failure locally, I get an error out of the JVM saying `The block at <hex-address> was not allocated by _aligned routines, use free()`. It's only the sequence of maps tests which fail in this way, so I'll have a look through the changes from this PR and figure it out.

**Comment by yuslepukhin** [comment]
> I can replicate that Windows failure locally, I get an error out of the JVM saying `The block at <hex-address> was not allocated by _aligned routines, use free()`. It's only the sequence of maps tests which fail in this way, so I'll have a look through the changes from this PR and figure it out.

Our default CPU allocator uses aligned `alloc` and `free`. Can it be that something that was allocated by `malloc` is being deallocated by aligned free?

**Comment by Craigacp** [comment]
> > I can replicate that Windows failure locally, I get an error out of the JVM saying `The block at <hex-address> was not allocated by _aligned routines, use free()`. It's only the sequence of maps tests which fail in this way, so I'll have a look through the changes from this PR and figure it out.
> 
> Our default CPU allocator uses aligned `alloc` and `free`. Can it be that something that was allocated by `malloc` is being deallocated by aligned free?

Found it. In two places I was using `AllocatorFree` instead of `ReleaseValue` to free `OrtValue`s. Which apparently runs just fine on clang & gcc, but Windows/MSVC does not like.

**Comment by yuslepukhin** [comment]
> > > I can replicate that Windows failure locally, I get an error out of the JVM saying `The block at <hex-address> was not allocated by _aligned routines, use free()`. It's only the sequence of maps tests which fail in this way, so I'll have a look through the changes from this PR and figure it out.
> > 
> > 
> > Our default CPU allocator uses aligned `alloc` and `free`. Can it be that something that was allocated by `malloc` is being deallocated by aligned free?
> 
> Found it. In two places I was using `AllocatorFree` instead of `ReleaseValue` to free `OrtValue`s. Which apparently runs just fine on clang & gcc, but Windows/MSVC does not like.

It would be wrong everywhere. One needs to destroy the objects first and only then deallocate memory. Simply deallocating memory for `OrtValue` does not deallocate tensor memory which can be huge. `ReleaseValue` is a destructor, not memory management.

**Comment by Craigacp** [comment]
> > > > I can replicate that Windows failure locally, I get an error out of the JVM saying `The block at <hex-address> was not allocated by _aligned routines, use free()`. It's only the sequence of maps tests which fail in this way, so I'll have a look through the changes from this PR and figure it out.
> > > 
> > > 
> > > Our default CPU allocator uses aligned `alloc` and `free`. Can it be that something that was allocated by `malloc` is being deallocated by aligned free?
> > 
> > 
> > Found it. In two places I was using `AllocatorFree` instead of `ReleaseValue` to free `OrtValue`s. Which apparently runs just fine on clang & gcc, but Windows/MSVC does not like.
> 
> It would be wrong everywhere. One needs to destroy the objects first and only then deallocate memory. Simply deallocating memory for `OrtValue` does not deallocate tensor memory which can be huge. `ReleaseValue` is a destructor, not memory management. On top of that, OrtValues are allocated from system memory, not from the ORT Allocators pool which can lead to memory corruption. We are lucky that Windows caught on a technicality.

I agree it was wrong everywhere, I'm surprised it didn't crash on the other platforms too. I've checked through the code and I don't think I'm using it incorrectly elsewhere.

**Comment by Craigacp** [comment]
That TensorRT test failure looks independent of all the changes in this PR, it's in the core library tests rather than any of the Java ones.

**Comment by yuslepukhin** [comment]
> That TensorRT test failure looks independent of all the changes in this PR, it's in the core library tests rather than any of the Java ones.

I will see to it.

**Review by yuslepukhin — APPROVED** [review]
:shipit:
