### PR TITLE
Fix output shape computation in ConvTranspose op

### LINKED ISSUE #2518: Unexpected Shape with ConvTranspose with Dilation !=1
**Describe the bug**
ConvTranspose has unexpected output shape when dilation !=1.

In the documentation:
output_shape[i] = stride[i] * (input_size[i] - 1) + output_padding[i] + ((kernel_shape[i] - 1) * dilations[i] + 1) - pads[start_i] - pads[end_i]

With :
input_size = (1, 1, 50, 50)
dilations = (3,1)
group = 1
kernel_shape = (3, 5)
pads = (4, 2, 4, 2)
strides = (2, 1)
output_padding = (0, 0)

The output shape is : (1, 3, 95, 50)
But from the above formula, with i = 0 : 
output_shape = 2 * (50 - 1) + 0 + ((3 - 1) * 3 + 1) - 4 - 4 = 97 and not 95.

So the expected output shape is : (1, 3, 97, 50)

I attached a repro to this issue.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: ort-nightly 11/29
- Python version: 3.7.1

[convtranspose.zip](https://github.com/microsoft/onnxruntime/files/3913495/convtranspose.zip)

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: The current logic to compute the output shape in the ConvTranspose op deviates from the prescribed logic in the official spec. This triggers an incorrect shape to be calculated for some specific combinations of kernel_size, input_dim, dilation, and stride. The change makes use of the prescribed logic to compute the output shape.

**Motivation and Context**
Resolve #2518

### CODE REVIEW

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h [hunk 1]
```diff
@@ -188,7 +188,7 @@ struct ConvTransposeAttributes : public ConvAttributes {
     if (*out_size != -1) {
       ORT_ENFORCE(*out_size >= 0);
       // total padding size
-      int64_t paddings = std::max<int64_t>(0, (in_size - 1) * stride + kernel + dilation - 1 + adj - *out_size);
+      int64_t paddings = std::max<int64_t>(0, (in_size - 1) * stride + adj + (kernel - 1) * dilation + 1 - *out_size);
```
Comment (hariharans29) [inline onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h]: Refer spec - https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvTranspose

File: onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h [hunk 2]
```diff
@@ -210,14 +210,14 @@ struct ConvTransposeAttributes : public ConvAttributes {
         case AutoPadType::SAME_LOWER:
           *pad_head = 0;
           *pad_tail = 0;
-          *out_size = (in_size - 1) * stride + kernel + dilation - 1 + adj;
```
Comment (hariharans29) [inline onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h]: Refer spec - https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvTranspose

File: onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc [hunk 3]
```diff
@@ -533,5 +532,25 @@ TEST(ConvTransposeTest, ConvTranspose_DefaultStridesAndDilations) {
   TestConvTransposeOp(attrs, {X, W}, {X_shape, W_shape}, expected_vals, Y_shape);
 }
 
+TEST(ConvTransposeTest, ConvTranspose_1D_NonDefaultStridesAndDilations) {
+  ConvTransposeOpAttributes attrs = {
```
Comment (hariharans29) [inline onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc]: This combination of values triggers incorrect shape to be calculated. With the exisitng logic output shape will be {1, 1, 8} which is incorrect. The right shape is {1, 1, 12}. This aligns with ONNX shape inference (verified by making all inputs initializers to trigger shape inferencing)

File: onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc [hunk 4]
```diff
@@ -533,5 +532,25 @@ TEST(ConvTransposeTest, ConvTranspose_DefaultStridesAndDilations) {
...
+      vector<int64_t>{4},     // kernel_shape
```
Comment (hariharans29) [inline onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc]: @lara-hdr - I couldn't use your test directly as the input shape in that test was 1, 1, 50, 50 and it is going to be hard to store 2500 values in the same unit file. I crafted a smaller sized input exhibiting the same phenomenon.

File: onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc (hunk 3 above)
Comment (fdwr) [reply onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc]: Since this new test case is under `providers/cpu/`, I presume it only tests the CPU provider? If so, that's sad it would be nice to validate this bug against other providers too, like DirectML :). Ideally, I think whenever we fix a bug, it would be nice to add a test mini-model into the ONNX backend. 

On a related note, WinML's ONNX conformance tests execute both CPU and GPU. I should check with Brian Martin to see if/when WinML is planning to migrate those 2'000 additional test cases over into GitHub.

Comment (hariharans29) [reply onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc]: I think the other EPs are tested too. EPs will have to be explicitly removed for the unit test.

For this op, only TensorRT is being excluded for a reson as stated in the comment - 

  test.Run(expect_result, err_str, excluded_provider_types);  // Disable TensorRT because weight as input is not supported

**Comment by yuslepukhin** [comment]
> using namespace std;

Please, remove

---
Refers to: onnxruntime/test/providers/cpu/nn/conv_transpose_op_test.cc:6 in 51d376a. [](commit_id = 51d376a02cb0e27d2df1cd13c74e1575f056218d, deletion_comment = False)

**Comment by hariharans29** [comment]
Requesting a review - 

Tagging @skottmckay  @snnn
