### PR TITLE
Cancel transpose optimizer for resize

### LINKED ISSUE #9857: The ONNX graph converted from tf.image.crop_and_resize() function will fail to be inferenced by latest version of ORT.
**Describe the bug**
Clone the latest code of master branch and install it in local machine. The ONNXRUNTIME version should be 1.10.0. Try to execute the example script provided in this issue which is trying to inference an ONNX file generated by converting tf.image.crop_and_resize() op to ONNX via tf2onnx, it throws an exception: Segmentation fault

If we install the onnxruntime 1.9.0, this issue is gone.

**Urgency**
This might be an issue blocking the latest release.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):    source
- ONNX Runtime version:   1.10.0
- Python version:  3.8

**To Reproduce**
- Download the attached zip file [crop_resize_issue.zip](https://github.com/microsoft/onnxruntime/files/7597104/crop_resize_issue.zip).
- Unzip it and execute the command "python crop_resize_issue.py" under this folder.

**Expected behavior**
It should display Pass without any exceptions.

### PR DESCRIPTION
**Pull request by RandySheriffH**
Fix #9857.
Crash occurs [here](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.cc#L566).
The model referred in the issue has:
```
[NHWC]->transpose->resize[NCHW]->transpose->[NHWC]
```
By this [PR](https://github.com/microsoft/onnxruntime/pull/9607), it optimizes to:
```
[NHWC]->resize[NHWC]->[NHWC]
```
Logically, the optimization is impeccable. 
However, upsample op called from within resize op has been hard-coded to only support NCHW [...](https://github.com/microsoft/onnxruntime/blob/1e9e57df3efddc2fc41540e79149e670ac5304c6/onnxruntime/core/providers/cpu/tensor/upsample.cc#L1130)

```
      const int64_t batch_size = is_2D ? 1 : dims[0];
      const int64_t num_channels = is_2D ? 1 : dims[1];
      const int64_t input_height = is_2D ? dims[0] : dims[2];
      const int64_t input_width = is_2D ? dims[1] : dims[3];
      const int64_t output_height = is_2D ? output_dims[0] : output_dims[2];
      const int64_t output_width = is_2D ? output_dims[1] : output_dims[3];
```
When fed with NHWC, the op will mistake H as C, W as H and C as W, which finally traps ort with invalid memory access.

### CODE REVIEW

**Comment by pranavsharma** [comment]
> However, upsample op called from within resize op has been hard-coded to only support NCHW
Resize works with NCHW and calls upsample that also works with NCHW. What's wrong with this?

**Comment by pranavsharma** [comment]
Can you add a test case?

**Comment by RandySheriffH** [comment]
> Can you add a test case?

UT added.

File: onnxruntime/test/optimizer/transpose_optimizer_test.cc [hunk 1]
```diff
@@ -291,210 +291,6 @@ TEST(TransposeOptimizerTests, TestPadNonconst) {
                     /*opset_version*/ 11);
 }
 
-TEST(TransposeOptimizerTests, TestResize) {
```
Comment (pranavsharma) [inline onnxruntime/test/optimizer/transpose_optimizer_test.cc:294]: Why are other unit tests being deleted?

Comment (RandySheriffH) [reply onnxruntime/test/optimizer/transpose_optimizer_test.cc:294]: They are cases testing the optimizer to be removed here.

File: onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc [hunk 2]
```diff
@@ -942,36 +942,6 @@ void PermuteInput(api::GraphRef& graph, api::NodeRef& node, size_t i, const std:
   node.SetInput(i, gather_output);
 }
 
-static bool HandleResize(HandlerArgs& args) {
-  auto inputs = args.node.Inputs();
```
Comment (skottmckay) [inline onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc:946]: The transpose optimizer is intended for use with multiple EPs, so a limitation of the ORT CPU EP implementation ideally shouldn't be handled by removing all support for transposing Resize.

Can the ORT upsample logic implicitly determine if it's NHWC by checking the scales and the dim values? not sure if there's any scenario where the value of C would be larger than H or W and the scale for the C dim would assumably always be 1.

If that's not possible and there's no simple way to special case Resize for now, it would be better to keep the code and unit tests and comment them out so that the functionality can be easily re-instated when we have a better solution.

Comment (RandySheriffH) [reply onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc:946]: The CPU implementation should be refactored to allow for blindly addressing either NHWC or NCHW, but now let's just comment the handler for release.

File: onnxruntime/test/shared_lib/test_inference.cc [hunk 3]
```diff
@@ -1883,5 +1885,40 @@ TEST(CApiTest, TestPerSessionCustomThreadPoolHooks) {
   ASSERT_TRUE(custom_join_hook_called == (thread_count - 1) << 1);
 }
 
+TEST(CApiTest, crop_and_resize) {
+  std::vector<float> input_value_0;
```
Comment (skottmckay) [inline onnxruntime/test/shared_lib/test_inference.cc:1889]: Please add a comment capturing what exactly this is testing and why.

File: onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc (hunk 2 above)
Comment (pranavsharma) [reply onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc:946]: This is holding up the release. @skottmckay if this change is not blocking any customer I'm inclined to go with the commenting option.

File: onnxruntime/test/shared_lib/test_inference.cc (hunk 3 above)
Comment (RandySheriffH) [reply onnxruntime/test/shared_lib/test_inference.cc:1891]: Done.

File: onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc (hunk 2 above)
Comment (RandySheriffH) [reply onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc]: Commented.

**Review by skottmckay — APPROVED** [review]
:shipit:

**Review by pranavsharma — APPROVED** [review]

**Review by yihonglyu — CHANGES_REQUESTED** [review]
I run this fix under onnxruntime_perf_test with the argument
```
-r 1 -I -u "crop_and_resize.nhwc.onnx" -o 99 "crop_and_resize.onnx"
```
but it still fails
```
Run failed:PerformanceRunner::RunOneIteration caught exception: Non-zero status code returned while running Loop node. Name:'output' Status Message: Non-zero status code returned while running Squeeze node. Name:'Squeeze__48' Status Message: C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core/providers/cpu/tensor/squeeze.h:53 onnxruntime::SqueezeBase::ComputeOutputShape input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 0. shape={0,3,20,20}
Stacktrace:
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\providers\cpu\tensor\squeeze.h(87): onnxruntime::Squeeze::Compute
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\sequential_executor.cc(323): onnxruntime::SequentialExecutor::Execute
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(602): onnxruntime::utils::ExecuteGraphImpl
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(735): onnxruntime::utils::ExecuteSubgraph
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\providers\cpu\controlflow\loop.cc(499): onnxruntime::LoopImpl::Execute
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\providers\cpu\controlflow\loop.cc(363): onnxruntime::Loop::Compute
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\sequential_executor.cc(323): onnxruntime::SequentialExecutor::Execute
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(602): onnxruntime::utils::ExecuteGraphImpl
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(660): onnxruntime::utils::ExecuteGraph
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\session\inference_session.cc(1848): onnxruntime::InferenceSession::Run
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\session\onnxruntime_c_api.cc(785): OrtApis::Run
C:\Users\yilyu\source\repos\onnxruntime\include\onnxruntime\core\session\onnxruntime_cxx_inline.h(568): Ort::Session::Run
C:\Users\yilyu\source\repos\onnxruntime\include\onnxruntime\core\session\onnxruntime_cxx_inline.h(560): Ort::Session::Run
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\ort_test_session.cc(22): onnxruntime::perftest::OnnxRuntimeTestSession::Run
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\performance_runner.h(66): onnxruntime::perftest::PerformanceRunner::RunOneIteration<1>
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\performance_runner.cc(109): onnxruntime::perftest::PerformanceRunner::Run
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\main.cc(46): real_main
C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\main.cc(64): wmain
d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(91): invoke_main
d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh
d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(331): __scrt_common_main
d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp(17): wmainCRTStartup
???: BaseThreadInitThunk
???: RtlUserThreadStart
```

**Comment by yihonglyu** [comment]
Check again, wait a second ...

**Comment by RandySheriffH** [comment]
> I run this fix under onnxruntime_perf_test with the argument
> 
> ```
> -r 1 -I -u "crop_and_resize.nhwc.onnx" -o 99 "crop_and_resize.onnx"
> ```
> 
> but it still fails
> 
> ```
> Run failed:PerformanceRunner::RunOneIteration caught exception: Non-zero status code returned while running Loop node. Name:'output' Status Message: Non-zero status code returned while running Squeeze node. Name:'Squeeze__48' Status Message: C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core/providers/cpu/tensor/squeeze.h:53 onnxruntime::SqueezeBase::ComputeOutputShape input_shape[i] == 1 was false. Dimension of input 0 must be 1 instead of 0. shape={0,3,20,20}
> Stacktrace:
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\providers\cpu\tensor\squeeze.h(87): onnxruntime::Squeeze::Compute
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\sequential_executor.cc(323): onnxruntime::SequentialExecutor::Execute
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(602): onnxruntime::utils::ExecuteGraphImpl
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(735): onnxruntime::utils::ExecuteSubgraph
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\providers\cpu\controlflow\loop.cc(499): onnxruntime::LoopImpl::Execute
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\providers\cpu\controlflow\loop.cc(363): onnxruntime::Loop::Compute
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\sequential_executor.cc(323): onnxruntime::SequentialExecutor::Execute
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(602): onnxruntime::utils::ExecuteGraphImpl
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\framework\utils.cc(660): onnxruntime::utils::ExecuteGraph
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\session\inference_session.cc(1848): onnxruntime::InferenceSession::Run
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\core\session\onnxruntime_c_api.cc(785): OrtApis::Run
> C:\Users\yilyu\source\repos\onnxruntime\include\onnxruntime\core\session\onnxruntime_cxx_inline.h(568): Ort::Session::Run
> C:\Users\yilyu\source\repos\onnxruntime\include\onnxruntime\core\session\onnxruntime_cxx_inline.h(560): Ort::Session::Run
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\ort_test_session.cc(22): onnxruntime::perftest::OnnxRuntimeTestSession::Run
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\performance_runner.h(66): onnxruntime::perftest::PerformanceRunner::RunOneIteration<1>
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\performance_runner.cc(109): onnxruntime::perftest::PerformanceRunner::Run
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\main.cc(46): real_main
> C:\Users\yilyu\source\repos\onnxruntime\onnxruntime\test\perftest\main.cc(64): wmain
> d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(91): invoke_main
> d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh
> d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(331): __scrt_common_main
> d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp(17): wmainCRTStartup
> ???: BaseThreadInitThunk
> ???: RtlUserThreadStart
> ```

Looks like a different issue, mind check your input?
We have the model covered in test_inference.cc file.

**Review by yihonglyu — APPROVED** [review]

**Comment by skottmckay** [comment]
> Crash occurs [here](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.cc#L566).

Side question: What's the reason why this crashes? Whilst I'd expect invalid results due to the implicit assumption the format is NCHW, shouldn't the code still run? If the input is {1, 20, 20, 3} instead of {1, 3, 20, 20} I would have expected it to just loop 20 times for the second dim, and process a 20x3 set of values in each loop iteration. In theory an image with 20 channels that is 20x3 should be possible shouldn't it?

**Comment by yihonglyu** [comment]
> > Crash occurs [here](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.cc#L566).
> 
> Side question: What's the reason why this crashes? Whilst I'd expect invalid results due to the implicit assumption the format is NCHW, shouldn't the code still run? If the input is {1, 20, 20, 3} instead of {1, 3, 20, 20} I would have expected it to just loop 20 times for the second dim, and process a 20x3 set of values in each loop iteration. In theory an image with 20 channels that is 20x3 should be possible shouldn't it?
> 
> Not sure if it's due to SetupUpsampleBilinear [assuming](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.cc#L418-L419) the scales for the first 2 dimensions are 1, but [this](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.h#L293) check seems to allow an NHWC format image.

The check was enabled by me. I should extend upsample to support NHWC as well so we can enable transpose optimizer for resize.

**Comment by RandySheriffH** [comment]
> > Crash occurs [here](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.cc#L566).
> 
> Side question: What's the reason why this crashes? Whilst I'd expect invalid results due to the implicit assumption the format is NCHW, shouldn't the code still run? If the input is {1, 20, 20, 3} instead of {1, 3, 20, 20} I would have expected it to just loop 20 times for the second dim, and process a 20x3 set of values in each loop iteration. In theory an image with 20 channels that is 20x3 should be possible shouldn't it?
> 
> Not sure if it's due to SetupUpsampleBilinear [assuming](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.cc#L418-L419) the scales for the first 2 dimensions are 1, but [this](https://github.com/microsoft/onnxruntime/blob/a3ebc5e08290b4000e8509d21819d7f486e23a14/onnxruntime/core/providers/cpu/tensor/upsample.h#L293) check seems to allow an NHWC format image.

Yes and no - apparently there are some logics sticking to NCHW causing an invalid offset of output space, by more investigation for sure we could locate the part - but even can fix it, we still should not allow the transforming of Resize when the overall computation assumes input shape as NCHW.
