### PR TITLE
Fix MatMulBnFusion to exclude cases when tensors are not 2D tensors

### LINKED ISSUE #22512: onnxruntime optimizers fails
### Describe the issue

The attached model succeeds when onnxruntime optimization are disabled, and fails when all of them are.

```
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 491, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (MatMulBnFusion_Gemm) Op (Gemm) [ShapeInferenceError] First input does not have rank 2
```
[model_levit_128-onnx_dynamo-ir-d0rt0.zip](https://github.com/user-attachments/files/17445480/model_levit_128-onnx_dynamo-ir-d0rt0.zip)

### To reproduce

```python
import onnxruntime
onnxruntime.InferenceSession("<model.onnx>", providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
```

### Urgency

_No response_

### Platform

Linux

### OS Version

ubuntu-22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

7880342e5e50159f59b9f9c0bd0a74ecc1542549

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

### PR DESCRIPTION
**Pull request by xadupre**
### Description
Fixes #22512, MatMul, Add can be fused into a single Gemm even if tensors dimensions are > 2. The PR excludes that cases.

### Motivation and Context
ORT crashes on valid models due to that unexpected fusion.

### CODE REVIEW

File: onnxruntime/core/optimizer/matmul_bn_fusion.cc [hunk 1]
```diff
@@ -165,6 +181,8 @@ Status MatmulBNFusion::Apply(Graph& graph, Node& matmul_node, RewriteRuleEffect&
       bias_tensor->dims_size() != 1 ||
       mean_tensor->dims_size() != 1 ||
       var_tensor->dims_size() != 1 ||
+      // matmul_a_tensor->dims_size() != 2 ||
```
Comment (tianleiwu) [inline onnxruntime/core/optimizer/matmul_bn_fusion.cc:184]: nit: This comment line is confusing since matmul_a_tensor is not declared.

**Review by tianleiwu — DISMISSED** [review]

File: onnxruntime/core/optimizer/matmul_bn_fusion.cc (hunk 1 above)
Comment (xadupre) [reply onnxruntime/core/optimizer/matmul_bn_fusion.cc]: removed

**Review by tianleiwu — APPROVED** [review]
