### PR TITLE
Simplify CPU allocator arena usage helper function, fix unit tests that check old ifdefs.

### LINKED ISSUE #22873: [AIX] CPUAllocatorTest failure
### Describe the issue

I think, with https://github.com/microsoft/onnxruntime/pull/22460 changes,  in AIX below test failures are introduced.
In 1.20.0 branch and older branch,  alloc_type value is 0 , but in main branch it's getting updated as 1 causing test failure.
is there any env settings/compiler defines for env to fix this ?

```

0) root @ aixoss1-lp6: /home/buildusr/onnxruntime/build/Linux/Release
# ./onnxruntime_test_all "--gtest_filter=TensorTest.EmptyTensorTest"
Note: Google Test filter = TensorTest.EmptyTensorTest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TensorTest
[ RUN      ] TensorTest.EmptyTensorTest
/home/buildusr/onnxruntime/onnxruntime/test/framework/tensor_test.cc:144: Failure
Expected equality of these values:
  location.alloc_type
    Which is: 1
  OrtAllocatorType::OrtDeviceAllocator
    Which is: 0

[  FAILED  ] TensorTest.EmptyTensorTest (0 ms)
[----------] 1 test from TensorTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TensorTest.EmptyTensorTest

 1 FAILED TEST

(1) root @ aixoss1-lp6: /home/buildusr/onnxruntime/build/Linux/Release
# ./onnxruntime_test_all "--gtest_filter=AllocatorTest.CPUAllocatorTest"
Note: Google Test filter = AllocatorTest.CPUAllocatorTest
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AllocatorTest
[ RUN      ] AllocatorTest.CPUAllocatorTest
/home/buildusr/onnxruntime/onnxruntime/test/framework/allocator_test.cc:22: Failure
Expected equality of these values:
  cpu_arena->Info().alloc_type
    Which is: 1
  OrtAllocatorType::OrtDeviceAllocator
    Which is: 0

[  FAILED  ] AllocatorTest.CPUAllocatorTest (0 ms)
[----------] 1 test from AllocatorTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AllocatorTest.CPUAllocatorTest

 1 FAILED TEST
```

### Urgency

_No response_

### Target platform

AIX

### Build script

https://onnxruntime.ai/docs/build/inferencing.html is having build steps.

### Error / output

it's mention in describe section.

### Visual Studio Version

_No response_

### GCC / Compiler Version

10.3

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

Simplify CPU allocator arena usage helper function, fix unit tests that check old ifdefs.

### Motivation and Context

Fix #22873.

### CODE REVIEW

File: onnxruntime/test/framework/tensor_test.cc [hunk 1]
```diff
@@ -137,12 +138,10 @@ TEST(TensorTest, EmptyTensorTest) {
   ASSERT_STREQ(location.name, CPU);
   EXPECT_EQ(location.id, 0);
 
-  // arena is disabled for CPUExecutionProvider on x86 and JEMalloc
-#if (defined(__amd64__) || defined(_M_AMD64) || defined(__aarch64__) || defined(__loongarch__) || defined(_M_ARM64)) && !defined(USE_JEMALLOC) && !defined(USE_MIMALLOC) && !defined(ABSL_HAVE_ADDRESS_SANITIZER)
-  EXPECT_EQ(location.alloc_type, OrtAllocatorType::OrtArenaAllocator);
```
Comment (snnn) [inline onnxruntime/test/framework/tensor_test.cc:142]: Here I disabled ArenaAllocator when ABSL_HAVE_ADDRESS_SANITIZER is true because otherwise the allocator can mask memory usage problems.

Comment (edgchen1) [reply onnxruntime/test/framework/tensor_test.cc:142]: yes, `DoesCpuAllocatorSupportArenaUsage()` also checks `ABSL_HAVE_ADDRESS_SANITIZER`. I was trying to put all these checks in one place originally but missed some in the unit tests.

**Review by tianleiwu — APPROVED** [review]
