### PR TITLE
Fix constant folding of node assigned to CUDA

### LINKED ISSUE #2474: An ONNX model that worked in 0.5.1 now fails in 1.0.0
**Describe the bug**

I recently upgraded my ONNX Runtime from 0.5.1 to 1.0.0 after changing my C code to adapt to the new API I then found out that my previous ONNX model does no longer run in 1.0.0. My ONNX model uses OpSet-Level 9. It is a PyTorch1.3 ONNX export of a HRNet-backbone landmark detection model. 

When loading the ONNX model in ONNXRuntime 1.0 I'll get an Exception:

op_kernel.cc:21 onnxruntime::OpKernelContext::OpKernelContext kernel != nullptr was false. OpKernel was null

it loaded fine in 0.5.1

### PR DESCRIPTION
**Pull request by skottmckay**
**Description**: 
Constant folding bug fix/improvements
  - Handle constant folding for node that is assigned to a non cpu EP
  - Check for errors in optimizer execution frame setup
  - Improve CUDA partitioning to look for initializers in parent graphs, and to only look for constant initializers (a non-const initializer may be overridden by a graph input)
  - Add unit test

**Motivation and Context**
Fix #2474

### CODE REVIEW

File: onnxruntime/core/optimizer/constant_folding.cc [hunk 1]
```diff
@@ -36,9 +47,19 @@ Status ConstantFolding::ApplyImpl(Graph& graph, bool& modified, int graph_level,
       continue;
     }
 
+    // override the EP while setting up OptimizerExecutionFrame::Info so that it will use the CPU kernel for Compute.
+    if (!cpu_ep) {
+      node->SetExecutionProviderType(kCpuExecutionProvider);
```
Comment (hariharans29) [inline onnxruntime/core/optimizer/constant_folding.cc]: Should this action and the toggle back to the original EP on line 60 be logged ?

Comment (skottmckay) [reply onnxruntime/core/optimizer/constant_folding.cc]: I don't think so. It's a very temporary thing that is undone. Not sure what a user would do with the information that it happened. If constructing the Info fails we bail out completely as it throws and the initialization fails (returning an error message saying why constructing Info failed).
