### PR TITLE
Fix race condition in CUDA, ROCm, and TensorRT EP GetKernelRegistry() implementations.

### LINKED ISSUE #10179: Multiple ONNX models with individual threads using CUDA EP result in random crashes
**Describe the bug**
I recently encountered an issue after updating my onnx version from 1.7 (CUDA 11.0) to 1.83 (CUDA 11.0) or 1.10 (CUDA 11.4).
At random my program crashes when loading multiple onnx models using individual threads. This didn't happen with v1.7.

The error message is: _Failed to add kernel for MemcpyFromHost: Conflict with existing kernel def hash_ (kernel_registry.cc line 305)

**Urgency**
Not urgent, since v1.7 is still running fine.

**System information**
- OS Platform and Distribution: Win 10
- ONNX Runtime installed from (source or binary): Source compiled - I had to change the target name to onnxruntime_CC, since Windows sometimes brings their own onnxruntime lib without cuda.
- ONNX Runtime version: v1.8.2 with cuda 11.0 and v1.10 with cuda 11.4
- Python version: -
- Visual Studio version (if applicable): Visual Studio 2017 (v141)
- GCC/Compiler version (if compiling from source): Visual Studio 2019 (v142)
- CUDA/cuDNN version: 11.0 and 11.4
- GPU model and memory: 2080Ti and 3070Ti

**To Reproduce**
- See below for example program and onnx model attached.
- [ExampleModel](https://github.com/microsoft/onnxruntime/files/7806744/example.zip)

```
#include <iostream>
#include <string>
#include <thread>

#include <onnxruntime_cxx_api.h>

void load_graph(std::wstring file)
{
  Ort::Session *m_session;
  Ort::Env m_env;
  Ort::SessionOptions sessionOptions;

  Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0));
  m_env = Ort::Env(ORT_LOGGING_LEVEL_ERROR, "Inference");
  m_session = new Ort::Session(m_env, file.c_str(), sessionOptions);
  std::cout << "Load graph." << std::endl;
}

int main(int argc, char* argv[])
{
  try
  {
    std::wstring new_graph_file_name = L"D:\\example.onnx";
    std::thread first (load_graph, new_graph_file_name);
    std::thread second (load_graph, new_graph_file_name);
    std::thread third (load_graph, new_graph_file_name);
    load_graph(new_graph_file_name);
    first.join();
    second.join();
    third.join();
  }
  catch (const std::exception& e)
  {
    std::cout << "Caught exception: " << e.what() << std::endl;
    return 1;
  }
  catch (...)
  {
    std::cout << "Fatal error: Caught unknown exception!" << std::endl;
    return 1;
  }
  std::cout << "Everything fine!" << std::endl;
  return 0;
}
```

**Expected behavior**
Difficult to reproduce, but if you start this program multiple times (approx 1 in 10) it should crash at some point.

**Screenshots**
grafik

### PR DESCRIPTION
**Pull request by edgchen1**
**Description**
Make GetKernelRegistry() kernel registry initialization thread-safe.

**Motivation and Context**
Fix #10179

### CODE REVIEW

File: onnxruntime/core/providers/rocm/rocm_execution_provider.cc [hunk 1]
```diff
@@ -1208,841 +1209,841 @@ KernelCreateInfo BuildKernelCreateInfo<void>() {
 
 static Status RegisterRocmKernels(KernelRegistry& kernel_registry) {
   static const BuildKernelCreateInfoFn function_table[] = {
-    BuildKernelCreateInfo<void>,  //default entry to avoid the list become empty after ops-reducing
```
Comment (edgchen1) [inline onnxruntime/core/providers/rocm/rocm_execution_provider.cc]: lots of formatting changes in this file, can ignore whitespace when viewing diff

File: onnxruntime/core/common/shared_ptr_thread_safe_wrapper.h [hunk 2]
```diff
@@ -0,0 +1,46 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License.
+
```
Comment (snnn) [inline onnxruntime/core/common/shared_ptr_thread_safe_wrapper.h:3]: Or you may follow CPU EP's implementation. That one is thread-safe.

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc [hunk 3]
```diff
@@ -2073,22 +2074,20 @@ static Status RegisterCudaKernels(KernelRegistry& kernel_registry) {
...
 }  // namespace cuda
 
-static std::shared_ptr<onnxruntime::KernelRegistry> s_kernel_registry;
+static std::shared_ptr<KernelRegistry> CreateCudaKernelRegistry() {
+  std::shared_ptr<KernelRegistry> registry = KernelRegistry::Create();
+  ORT_THROW_IF_ERROR(cuda::RegisterCudaKernels(*registry));
+  return registry;
+}
+
+static SharedPtrThreadSafeWrapper<KernelRegistry> s_kernel_registry{&CreateCudaKernelRegistry};
```
Comment (snnn) [inline onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: I would suggest not having global initializers. If you change it to function local, things will be much simpler.

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc [hunk 4]
```diff
@@ -2073,22 +2074,20 @@ static Status RegisterCudaKernels(KernelRegistry& kernel_registry) {
...
 
 void Shutdown_DeleteRegistry() {
-  s_kernel_registry.reset();
+  s_kernel_registry.Reset();
```
Comment (snnn) [inline onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2086]: Whenever we have a function like this, we need to think: what if people forgot to call this function, will the program crash? Is such a manual release really needed?

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc (hunk 3 above)
Comment (edgchen1) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: Function local static would be nice, but it needs to be reset by another function. @RyanUnderhill knows more about why.

File: onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc [hunk 5]
```diff
@@ -376,22 +377,20 @@ static Status RegisterTensorrtKernels(KernelRegistry& kernel_registry) {
   return Status::OK();
 }
 
-static std::shared_ptr<KernelRegistry> s_kernel_registry;
+static std::shared_ptr<KernelRegistry> CreateTensorrtKernelRegistry() {
```
Comment (snnn) [inline onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:380]: It could throw. But you won't want to see any exception was thrown before the main function started.  That's why in CPU EP's implementation, it also returns a onnxruntime::Status.

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc (hunk 4 above)
Comment (RyanUnderhill) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2086]: In this case it will crash, it's why I added the 'DeleteOnUnload' for thread locals, but it's not super lightweight for all types.

If we have a new type that simply encapsulates the intent and will prevent errors (like asserting it's empty on destruction) we could add to prevent errors. Just in case it doesn't crash on exit, as it's undefined behavior currently.

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc (hunk 3 above)
Comment (snnn) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: Even it is function local, you still can call Reset() manually. Function local delays initiation to run time.

File: onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc (hunk 5 above)
Comment (edgchen1) [reply onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:380]: The CPU EP's GetKernelRegistry() may also throw.
https://github.com/microsoft/onnxruntime/blob/7b5464ed7bdd4eda5ea33977c008538b08da9025/onnxruntime/core/providers/cpu/cpu_execution_provider.cc#L2059

The CreateXKernelRegistry() functions added here are static to the .cc files and only called by the EP's GetKernelRegistry().

If GetKernelRegistry() is called prior to main, then there could be a problem with the exception.

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc (hunk 3 above)
Comment (edgchen1) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: I guess you mean doing something like:
```c++
static std::shared_ptr<KernelRegistry>& CudaKernelRegistry() {
  static std::shared_ptr<KernelRegistry> registry = ...
  return registry;
}

std::shared_ptr<KernelRegistry> CUDAExecutionProvider::GetKernelRegistry() const {
  return CudaKernelRegistry();
}

void Shutdown_DeleteRegistry() {
  CudaKernelRegistry().reset();
}
```

But that has different behavior when calls to GetKernelRegistry() and Shutdown_DeleteRegistry() are interleaved. E.g., GetKernelRegistry() will return an empty shared_ptr after Shutdown_DeleteRegistry() is called.

Comment (snnn) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: I think we don't really need to ref count it. Shutdown_DeleteRegistry should only be called once when the DLL is unloading. And, nobody should call GetKernelRegistry() again. Nobody would call Shutdown_DeleteRegistry  manually. It is an internal function that only serve the needs of Ryan's provider bridge code.

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc (hunk 4 above)
Comment (snnn) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2086]: Would you please elaborate more? What if we init the registry when a CUDA EP is created the first time and destroy it when the DLL is unloading? In other words, if someone load the DLL, create a CUDA EP, then destroy the EP and re-create it again. Does Shutdown_DeleteRegistry need be called when the first EP was EOL? In some sense, the refcount is zero at the time point.

Comment (snnn) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2086]: Had a discussion offline.  I think a function local static variable should solve the most issues. Once a shared_ptr is initialized(not null), it is thread-safe. So we only need to:
1. Make sure the initialization is safe. C++11 thread local can help.
2. The Reset() function is called when the DLL is unloading.

File: onnxruntime/test/shared_lib/test_inference.cc [hunk 6]
```diff
@@ -1978,3 +1978,36 @@ TEST(CApiTest, crop_and_resize) {
...
+  constexpr int num_threads = 4;
+  constexpr int num_iterations = 10;
+
+  for (int i = 0; i < num_iterations; ++i) {
+    std::vector<std::thread> threads(num_threads);
+    for (auto& thread : threads) {
+      thread = std::thread{load_model_thread_fn};
+    }
+
+    for (auto& thread : threads) {
```
Comment (yuslepukhin) [inline onnxruntime/test/shared_lib/test_inference.cc:2008]: I am concerned that in the even of the test failure, we won't get a good diagnostics since we are going to destroy unjoined and undetached threads.

Comment (edgchen1) [reply onnxruntime/test/shared_lib/test_inference.cc:2008]: I tried to catch exceptions in the thread function before, but it turns out that wasn't the only way it was failing. For example, sometimes debug assertions from the standard library would be hit which also stop the process. I didn't make any further attempt to fail gracefully. Do you have any suggestions?

**Review by snnn — APPROVED** [review]

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc [hunk 7]
```diff
@@ -2073,22 +2073,23 @@ static Status RegisterCudaKernels(KernelRegistry& kernel_registry) {
...
-  if (!s_kernel_registry) {
-    s_kernel_registry = KernelRegistry::Create();
-    auto status = cuda::RegisterCudaKernels(*s_kernel_registry);
-    if (!status.IsOK())
-      s_kernel_registry.reset();
-    ORT_THROW_IF_ERROR(status);
-  }
-
-  return s_kernel_registry;
+  return CudaKernelRegistry();
```
Comment (pranavsharma) [inline onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2092]: Is there any advantage of having an additional helper function here?

Comment (edgchen1) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2092]: Here, the helper's result (shared_ptr&) is copied. But the helper returns a reference so its shared_ptr can be reset by Shutdown_DeleteRegistry().

Comment (pranavsharma) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2092]: Ah, didn't see the reference.

**Review by pranavsharma — DISMISSED** [review]

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc (hunk 3 above)
Comment (edgchen1) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc]: In the Java tests, apparently GetKernelRegistry() gets called after Shutdown_DeleteRegistry() and that causes a test failure. So I'll go back to the original approach.

Comment (edgchen1) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: Hi @Craigacp, the Java API seems to support creating and destroying an ORT environment multiple times within a process (e.g., in unit tests), but according to some other folks on the ORT team, we only expect one environment to be created and destroyed once in actual scenarios. Some of the previous comments in this thread have this assumption.

I wanted to understand why the Java API works this way and if it is indeed necessary to create and destroy an ORT environment multiple times within one process. For comparison, in the C# API, the environment class is a singleton without the explicit reference count.
https://github.com/microsoft/onnxruntime/blob/d52d3c00520a10075e3bc75fe90db5b4c83ee557/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.shared.cs#L71-L76

Comment (Craigacp) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: It works that way because while I understood there was supposed to only be at most one environment at any given time, I didn't realise that there could only be a single one in any given process. Given there are user controlled options which need to be set on environment construction I can't automatically create a singleton instance in the static initializer block for the `OrtEnvironment` class, as that wouldn't allow users to setup things like thread pools or logging, which is why we ended up with the current approach. I can refactor the code so the environment isn't closeable and rely on a shutdown hook to close it, but then there's no way for a user to signal that they are finished with ORT and it can release it's resources. The shutdown hook isn't guaranteed to execute before the JVM goes away, but I don't know if that matters much.

How does the C# code shutdown the environment? Is it done when the runtime terminates or can the user signal this? Also, how does it deal with the environment construction options like thread pools and logging?

Comment (edgchen1) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2083]: > It works that way because while I understood there was supposed to only be at most one environment at any given time, I didn't realise that there could only be a single one in any given process until you said it just now. Given there are user controlled options which need to be set on environment construction I can't automatically create a singleton instance in the static initializer block for the `OrtEnvironment` class, as that wouldn't allow users to setup things like thread pools or logging, which is why we ended up with the current approach. I can refactor the code so the environment isn't closeable and rely on a shutdown hook to close it, but then there's no way for a user to signal that they are finished with ORT and it can release its resources. The shutdown hook isn't guaranteed to execute before the JVM goes away, but I don't know if that matters much.

@pranavsharma What do you think?

> How does the C# code shutdown the environment? Is it done when the runtime terminates or can the user signal this? Also, how does it deal with the environment construction options like thread pools and logging?

I think the C# ORT environment will be shutdown when the runtime terminates. The creation/shutdown is tied to a lazily initialized, static class variable.

https://github.com/microsoft/onnxruntime/blob/d52d3c00520a10075e3bc75fe90db5b4c83ee557/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.shared.cs#L51
https://github.com/microsoft/onnxruntime/blob/d52d3c00520a10075e3bc75fe90db5b4c83ee557/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.shared.cs#L57
https://github.com/microsoft/onnxruntime/blob/d52d3c00520a10075e3bc75fe90db5b4c83ee557/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.shared.cs#L175

As for environment configuration, that looks to be unsupported (currently hardcoded).
https://github.com/microsoft/onnxruntime/blob/d52d3c00520a10075e3bc75fe90db5b4c83ee557/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.shared.cs#L54

**Comment by snnn** [comment]
How is it going?

File: onnxruntime/core/providers/cuda/cuda_execution_provider.cc (hunk 3 above)
Comment (pranavsharma) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2067]: @Craigacp We can match the same behavior as C# for Java as well. Which part won't be a singleton like C#? C# does _not_ allow the user to configure it on instantiation.

Comment (Craigacp) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2067]: I'd prefer not to remove useful functionality like configuring a threadpool and setting the logging level. Switching it over to a singleton will mean the environment is constructed at an unpredictable time (as it's based on class initialization) and there's no potential for a user to close it to free up resources while keeping the JVM alive. A shutdown hook will clean up the environment most of the time (apart from when the JVM gets SIGKILLed or similar) and we'd need that for the singleton anyway. Allowing user controlled construction avoids the first problem while giving more flexibility.

What kind of things live inside the environment object? Is it worth allowing users to close it explicitly if they are finished with ORT, under the assumption that it throws some kind of exception if they try to make another one in the same process?

Comment (Craigacp) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2067]: I've filed #10670 which switches the environment over so that only one can be created in the lifetime of the JVM (unless the user starts messing with class loaders), and its closed by a JVM shutdown hook. I left the close method in place for compatibility though it is now a no-op. If we want the environment to be closeable to release resources then I'll need to do some more refactoring as the current close idiom will be very confusing.

Comment (pranavsharma) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2067]: In terms of resources the most important one that the Environment contains is the threadpool and that too only if you create the env with the global threadpool option. See [here](https://github.com/microsoft/onnxruntime/blob/4e9e01cb3c008335a2471c27dbdf7dd5d12e4224/include/onnxruntime/core/session/environment.h#L90-L94). Besides this there are global registrations for various schemas that can't be undone.

The OrtEnv obj exposed in the C API wraps the internal Environment class. Each time you request an OrtEnv object the refcount is [incremented for the same instance](https://github.com/microsoft/onnxruntime/blob/4e9e01cb3c008335a2471c27dbdf7dd5d12e4224/onnxruntime/core/session/ort_env.cc#L81) in the process. We do provide a [Release method](https://github.com/microsoft/onnxruntime/blob/4e9e01cb3c008335a2471c27dbdf7dd5d12e4224/onnxruntime/core/session/ort_env.cc#L85-L95) that decrements the refcount and finally gets rid of the instance allowing another instance to be created in the same process. The OrtEnv destructor [unloads the shared libs](https://github.com/microsoft/onnxruntime/blob/4e9e01cb3c008335a2471c27dbdf7dd5d12e4224/onnxruntime/core/session/ort_env.cc#L38-L43).

Comment (Craigacp) [reply onnxruntime/core/providers/cuda/cuda_execution_provider.cc:2067]: I used to have a similar refcount in the Java side and it would hand out the same Java reference to the native OrtEnv, but it would call the destructor when the count gets to zero and allow users to build a fresh environment after that, which is the source of the trouble. It doesn't look like there are too many resources held by it, so it's probably ok without an explicit close.

**Review by snnn — APPROVED** [review]
