### PR TITLE
Stop proceeding with constant folding if a CPU kernel is not found found

### LINKED ISSUE #3735: Loading float16 model fails
When constructing `Ort::Session` with a float16 ONNX model I get the following error
```
Exception during initialization: C:\...\onnxruntime\onnxruntime\core\optimizer\optimizer_execution_frame.cc:73 onnxruntime::OptimizerExecutionFrame::Info::Info [ONNXRuntimeError] : 1 : FAIL : Failed to find kernel for Sub
```

**System information**
- OS: Windows 10
- ONNX Runtime build from source (6b3b4fe43e38c3c3f6f09dcad39988c804310b52)
- Visual Studio version 2019
- CUDA 10.2, cuDNN 7.6.5
- GPU model and memory: NVIDIA GeForce RTX 2080 Ti 11GB

### PR DESCRIPTION
**Pull request by hariharans29**
Constant folding assumes that every node in the graph will have a CPU kernel which is strictly not true as we only support a subset of types in some CPU kernels. In those cases, we cannot constant fold and stop.

Fix #3735

### CODE REVIEW

File: onnxruntime/core/optimizer/constant_folding.cc [hunk 1]
```diff
@@ -51,8 +54,28 @@ Status ConstantFolding::ApplyImpl(Graph& graph, bool& modified, int graph_level,
...
+    if (!cpu_kernel_found_for_node) {
+      LOGS(logger, WARNING) << "Could not find a CPU kernel and hence "
+                            << "can't constant fold " << node->OpType() << " node '" << node->Name() << "'";
+
+      // Revert the EP change. We won't be proceeding with constant folding for this node.
+      if (!cpu_ep) {
+        node->SetExecutionProviderType(ep_type);
+      }
+
+      // Move on to the next candidate node
```
Comment (skottmckay) [inline onnxruntime/core/optimizer/constant_folding.cc:73]: Can the check for a kernel move above where we first override the node's EP so we don't need to undo that here?

File: onnxruntime/core/optimizer/constant_folding.cc [hunk 2]
```diff
@@ -51,8 +54,28 @@ Status ConstantFolding::ApplyImpl(Graph& graph, bool& modified, int graph_level,
       node->SetExecutionProviderType(kCpuExecutionProvider);
     }
 
+    // Check whether the CPU EP has a kernel for this node. Stop proceeding if it doesn't.
+    std::unique_ptr<CPUExecutionProvider> cpu_execution_provider =
+        onnxruntime::make_unique<CPUExecutionProvider>(CPUExecutionProviderInfo());
+
+    auto cpu_kernel_found_for_node =
+        KernelRegistry::HasImplementationOf(*cpu_execution_provider->GetKernelRegistry(), *node, kCpuExecutionProvider);
+
```
Comment (skottmckay) [inline onnxruntime/core/optimizer/constant_folding.cc:63]: Could we maybe restructure OptimizerExecutionFrame::Info::Info instead to separate out the kernel creation step so it can return an error so we don't need extra logic here?

Comment (hariharans29) [reply onnxruntime/core/optimizer/constant_folding.cc:63]: Then the call site requires an additional call to invoke kernel creation and check for the status and besides this way, it is more in tune with the theme in constant folding where we decide whether this node is a candidate for folding or not. Such a theme does not exist in OptimizerExecutionFrame::Info

File: onnxruntime/core/optimizer/constant_folding.cc (hunk 1 above)
Comment (hariharans29) [reply onnxruntime/core/optimizer/constant_folding.cc:73]: When I checked the logic of HasImplementationOf(), it seemed like the node's EP (if set) is what will be matched with the kernel defs held by the kernel registry, so we have to mutate it to CPU EP or unset it and depend on the passed in provider_type. Either approach requires reverting a mutation.

File: onnxruntime/core/optimizer/constant_folding.cc (hunk 2 above)
Comment (skottmckay) [reply onnxruntime/core/optimizer/constant_folding.cc:63]: Isn't it more re-usable to do this inside OptimizerExecutionFrame::Info as its role (at least currently) involves creating the kernels for nodes it's given? Otherwise any user of that must first check if TryCreateKernel will fail prior to asking OptimizerExecutionFrame::Info to create the kernels.

That also avoids duplicating checks here that happen inside of TryCreateKernel.

Comment (hariharans29) [reply onnxruntime/core/optimizer/constant_folding.cc:63]: So do we expose a new method that returns a Status and pretty much does everything in Info's ctor ?

Comment (hariharans29) [reply onnxruntime/core/optimizer/constant_folding.cc]: Refactored
