### PR TITLE
[CoreML EP] Enable inputs with dynamic shape

### LINKED ISSUE #14212: [Performance] Why is dynamic shape not supported with the CoreML provider, while CoreML 2+ supports it ?
### Describe the issue

When I try to run an ONNX model with a dynamic shape (even on a single axis) on the CoreML backend of ORT 1.13.1, on a recent machine (macbook air M1 with macOS 12.5), I get the following warning:
`[W:onnxruntime:, helper.cc:61 IsInputSupported] Dynamic shape is not supported for now, for input:input`

And as a result the ONNX runs on the CPU instead of CoreML.

Why can't ORT runs ONNX models with dynamic shape on the CoreML backend ?
According to https://apple.github.io/coremltools/mlmodel/Format/Model.html CoreML supports dynamic shapes since version 2, which was released with macOS 10.14, more than 4 years ago.

### To reproduce

Use ORT 1.13.1 macos arm64 on a C++ project running in arm64 mode.
Try to infer an ONNX model with at least one axis dynamic, and the warning will show up and the model inference will fallback to CPU.

### Urgency

_No response_

### Platform

Mac

### OS Version

12.5

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

CoreML

### Execution Provider Library Version

_No response_

### Model File

_No response_

### Is this a quantized model?

No

### PR DESCRIPTION
**Pull request by edgchen1**
### Description

Enable node inputs with dynamic shape to be handled by the CoreML EP.

### Motivation and Context

Enable more models to run using the CoreML EP.

Fix #14212.

### CODE REVIEW

File: onnxruntime/core/providers/coreml/builders/impl/gemm_op_builder.cc [hunk 1]
```diff
@@ -146,6 +146,7 @@ bool GemmOpBuilder::IsOpSupportedImpl(const Node& node, const OpBuilderInputPara
       return false;
     }
 
+    // TODO is it ok if the shape is dynamic and empty?
```
Comment (edgchen1) [inline onnxruntime/core/providers/coreml/builders/impl/gemm_op_builder.cc:149]: note: disabling dynamic shapes with zero elements for now by erroring out at runtime

File: onnxruntime/core/providers/coreml/coreml_execution_provider.cc [hunk 2]
```diff
@@ -165,8 +180,30 @@ common::Status CoreMLExecutionProvider::Compile(const std::vector<FusedNodeAndGr
...
+        std::unordered_map<std::string, coreml::OnnxTensorInfo> outputs;
         outputs.reserve(model_outputs.size());
+
+        coreml::GetOutputTensorMutableRawDataFn get_output_tensor_mutable_raw_data_fn =
+            [&ctx, &model_outputs](
+                const std::string& name,
+                int32_t requested_onnx_tensor_element_type,
+                gsl::span<const int64_t> static_shape) -> void* {
+          const auto model_output_it = std::find(model_outputs.begin(), model_outputs.end(), name);
+          ORT_ENFORCE(model_output_it != model_outputs.end(), "Failed to find CoreML model output name:", name);
```
Comment (edgchen1) [inline onnxruntime/core/providers/coreml/coreml_execution_provider.cc:192]:
```suggestion
          ORT_ENFORCE(model_output_it != model_outputs.end(), "Failed to find CoreML model output name: ", name);
```

File: onnxruntime/core/providers/coreml/model/model.mm [hunk 3]
```diff
@@ -1,37 +1,104 @@
...
+                   ORT_ENFORCE(inferred_dim == -1 || inferred_dim == coreml_static_dim,
+                               "CoreML static output shape (", Shape2String(coreml_static_shape),
+                               ") and inferred shape (", Shape2String(inferred_shape),
+                               ") have an inconsistent static dimensions (", coreml_static_dim, " vs. ",
+                               inferred_dim, ").");
+
+                   return inferred_dim != -1 ? inferred_dim : coreml_static_dim;
+                 });
+
+  // TODO change to VERBOSE log level
```
Comment (edgchen1) [inline onnxruntime/core/providers/coreml/model/model.mm:79]: update log level

File: onnxruntime/core/providers/coreml/model/model.mm [hunk 4]
```diff
@@ -200,100 +269,115 @@ - (void)dealloc {
...
+        return result;
+      }();
+
+      const auto static_output_shape = GetStaticOutputShape(output_tensor_info.shape, coreml_static_output_shape,
+                                                            *logger_);
+
+      void* output_buffer = get_output_tensor_mutable_raw_data_fn(output_name, output_tensor_info.data_type,
+                                                                  static_output_shape);
+
+      if (const size_t num_elements = data.count; num_elements > 0) {
```
Comment (edgchen1) [inline onnxruntime/core/providers/coreml/model/model.mm:328]: verify `data.count` matches size computed from `static_output_shape`

File: onnxruntime/core/providers/coreml/shape_utils.cc [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+
+std::string Shape2String(gsl::span<const int64_t> shape) {
+  std::ostringstream os;
+  os << "[ ";
+  for (const auto dim : shape) {
+    os << dim << " ";
+  }
+  os << "]";
+  return os.str();
+}
```
Comment (skottmckay) [inline onnxruntime/core/providers/coreml/shape_utils.cc:74]: nit: can we make the formatting of the shape string consistent with how we format TensorShape. TensorShape::ToString would produce `{0,2}`.

File: onnxruntime/test/testdata/mobilenet_v3_small_excerpt_gen.py [hunk 6]
```diff
@@ -0,0 +1,119 @@
+"""
+Run this script to recreate the original onnx model.
+Example usage:
+python mobilenet_v3_small_excerpt_gen.py out_model_path.onnx
```
Comment (skottmckay) [inline onnxruntime/test/testdata/mobilenet_v3_small_excerpt_gen.py:4]: nit: might be useful to mention you ran onnx2py on the full model and stripped things down to the desired nodes in case someone wants to generate an excerpt from a different model.

File: onnxruntime/core/providers/coreml/shape_utils.cc (hunk 5 above)
Comment (edgchen1) [reply onnxruntime/core/providers/coreml/shape_utils.cc]: sure. FWIW, it was copied from NNAPI EP's Shape2String() so that's another one to make consistent later

File: onnxruntime/core/providers/coreml/builders/impl/activation_op_builder.cc [hunk 7]
```diff
@@ -125,7 +127,7 @@ bool IsPReluOpSupported(const Node& node, const OpBuilderInputParams& input_para
 
   // X input rank must be 3 or 4
   std::vector<int64_t> x_shape;
-  if (!GetShape(*input_defs[0], x_shape, logger)) {
+  if (!GetStaticShape(*input_defs[0], x_shape, logger)) {
```
[the remark this answers is not in the document]
Comment (edgchen1) [reply onnxruntime/core/providers/coreml/builders/impl/activation_op_builder.cc]: I think we can just check that the 'C' dimension is not dynamic. updated to do that.

File: onnxruntime/core/providers/coreml/shape_utils.cc [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+#include "core/framework/tensorprotoutils.h"
+
+namespace onnxruntime::coreml {
+
+namespace {
+bool GetShapeImpl(const NodeArg& node_arg, std::vector<int64_t>& shape_out, const logging::Logger& logger,
+                  bool allow_dynamic_shape) {
+  const auto* shape_proto = node_arg.Shape();
+  if (!shape_proto) {
+    LOGS(logger, WARNING) << "NodeArg [" << node_arg.Name() << "] has no shape info";
```
[the remark this answers is not in the document]
Comment (edgchen1) [reply onnxruntime/core/providers/coreml/shape_utils.cc]: changed log level to VERBOSE

File: include/onnxruntime/core/providers/coreml/coreml_provider_factory.h [hunk 9]
```diff
@@ -24,9 +24,13 @@ enum COREMLFlags {
   // Please note, enable this option does not guarantee the entire model to be executed using ANE only
   COREML_FLAG_ONLY_ENABLE_DEVICE_WITH_ANE = 0x004,
 
-  // Keep COREML_FLAG_MAX at the end of the enum definition
+  // Only allow CoreML EP to take nodes with inputs with static shapes. By default it will also allow inputs with
+  // dynamic shapes. However, the performance may be negatively impacted if inputs have dynamic shapes.
```
[the remark this answers is not in the document]
Comment (edgchen1) [reply include/onnxruntime/core/providers/coreml/coreml_provider_factory.h:28]: from what I've observed, it is not necessarily the case that ANE won't be used if there are dynamic input shapes. it probably depends on the particular layers in the model.

File: onnxruntime/core/providers/coreml/model/model.mm (hunk 3 above)
Comment (edgchen1) [reply onnxruntime/core/providers/coreml/model/model.mm:78]: not always - I only noticed the extra leading 1's when the input shape was dynamic.

File: onnxruntime/core/providers/cpu/tensor/reshape_helper.h [hunk 10]
```diff
@@ -11,6 +11,10 @@ namespace onnxruntime {
 class ReshapeHelper {
  public:
   ReshapeHelper(const TensorShape& input_shape, TensorShapeVector& requested_shape, bool allow_zero = false) {
+    const auto input_shape_size = input_shape.Size();
```
Comment (YUNQIUGUO) [inline onnxruntime/core/providers/cpu/tensor/reshape_helper.h:14]: nit: thought `.Size()` is the product of input_shape elements, so didn't quite follow at first about just checking `input_shape_size` != -1 equates to ensure that there's no -1 dimensions in input_shape.

maybe might be good to annotate that the .Size() returns -1 when found a negative element in tensorshape?

File: onnxruntime/test/testdata/mobilenet_v3_small_excerpt_gen.py (hunk 6 above)
Comment (skottmckay) [reply onnxruntime/test/testdata/mobilenet_v3_small_excerpt_gen.py:4]: and now I've learnt something. wasn't aware of onnx.untils.extract model.

**Review by skottmckay — APPROVED** [review]

**Review by YUNQIUGUO — APPROVED** [review]
thanks for cleaning up the code. ( noticed a couple places here and there.

looks good to me.:)

File: onnxruntime/core/providers/coreml/builders/impl/reshape_op_builder.cc [hunk 11]
```diff
@@ -60,7 +60,7 @@ Status ReshapeOpBuilder::AddToModelBuilderImpl(ModelBuilder& model_builder,
   const auto size = target_shape_tensor.dims()[0];
   TensorShapeVector target_shape{raw_target_shape, raw_target_shape + size};
   std::vector<int64_t> input_shape;
-  ORT_RETURN_IF_NOT(GetShape(*input_defs[0], input_shape, logger), "Cannot get shape");
+  ORT_RETURN_IF_NOT(GetStaticShape(*input_defs[0], input_shape, logger), "Cannot get shape");
```
[the remark this answers is not in the document]
Comment (edgchen1) [reply onnxruntime/core/providers/coreml/builders/impl/reshape_op_builder.cc:63]: if we need a static shape, use `GetStaticShape()`. if we need a shape and it can be static or dynamic, use `GetShape()`.

File: onnxruntime/core/providers/coreml/shape_utils.cc [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+bool GetStaticShape(const NodeArg& node_arg, std::vector<int64_t>& shape, const logging::Logger& logger) {
+  return GetShapeImpl(node_arg, shape, logger, /* allow_dynamic_shape */ false);
+}
+
+bool IsStaticShape(gsl::span<const int64_t> shape) {
+  return std::find(shape.begin(), shape.end(), int64_t{-1}) == shape.end();
+}
+
+bool DoesShapeSpecifyZeroElements(gsl::span<const int64_t> shape) {
+  return std::find(shape.begin(), shape.end(), int64_t{0}) != shape.end();
```
[the remark this answers is not in the document]
Comment (edgchen1) [reply onnxruntime/core/providers/coreml/shape_utils.cc:57]: it could, but that requires computing the shape which is usually more expensive.

File: onnxruntime/core/providers/coreml/model/model.mm (hunk 3 above)
Comment (edgchen1) [reply onnxruntime/core/providers/coreml/model/model.mm]: FYI, I asked about it here. hopefully someone will respond.

https://developer.apple.com/forums/thread/734985
