### PR TITLE
Fix std::chrono/date conflict for mac builds with C++20

### LINKED ISSUE #21033: v1.17.0 + requires macOS deployment target >= than 13.3 due to C++ 20
### Describe the issue

It seems that moving to C++20 for macOS builds has bumped the minimum macOS that the library can run on. I didn't see this mentioned in the release notes. macOS 13.3 is not that old.

https://stackoverflow.com/questions/76932735/unable-to-use-to-chars-with-clang-on-macos

```
In file included from /onnxruntime/onnxruntime/include/onnxruntime/core/common/common.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/chrono:800:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__chrono/formatter.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__chrono/ostream.h:30:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__format/format_functions.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:73:32: error: 'to_chars' is unavailable: introduced in macOS 13.3
  to_chars_result __r = _VSTD::to_chars(__first, __last, __value, __fmt, __precision);
  ```

### To reproduce

try and compile explicitly setting a lower deployment target with --apple_deploy_target

### Urgency

_No response_

### Platform

Mac

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

_No response_

### PR DESCRIPTION
**Pull request by skottmckay**
### Description

Fix usage of c++ std::chrono::operator<< in mac builds for wider range of xcode/targets.

### Motivation and Context

Resolve #21033

### CODE REVIEW

**Comment by snnn** [comment]
We may also consider using absl::date, then we can totally get rid of the third-party date library, regardless C++ standard version. 
For example:
```
// Construct an absl::Time from the system clock.
absl::Time t1 = absl::Now();

// When formatting a time, a time zone should be passed.
absl::TimeZone utc =  absl::UTCTimeZone();
std::cout << absl::FormatTime(t1, utc);
```

**Comment by skottmckay** [comment]
What's the difference between absl::date and the date library from Howard Hinnant that we use? Both are third-party aren't they? 

I would have assumed the latter is closer to what is in the C++20 standard given Howard Hinnant is on the C++ standards committee.

**Comment by snnn** [comment]
Howard Hinnant is out of maintenance. On the other hand, absl::date is not deprecated, and it is already in the list of ORT's dependencies.  Anyway we only use it in very a few places. The change would be local.

File: include/onnxruntime/core/common/logging/logging.h [hunk 1]
```diff
@@ -58,15 +58,42 @@ namespace logging {
...
 using Timestamp = std::chrono::time_point<std::chrono::system_clock>;
 
-// TODO: When other compilers support std::chrono::operator<<, update this.
-// TODO: Check support for other compilers' version before enable C++20 for other compilers.
-// Xcode added support for C++20's std::chrono::operator<< in SDK version 14.4.
-#if __cplusplus >= 202002L && __MAC_OS_X_VERSION_MAX_ALLOWED >= 140400L
+// C++20 has operator<< in std::chrono for Timestamp type but mac builds need additional checks
+// to ensure usage is valid.
+// TODO: As we enable C++20 on other platforms we may need similar checks.
+#define _USE_CXX20_STD_CHRONO __cplusplus >= 202002L
```
Comment (snnn) [inline include/onnxruntime/core/common/logging/logging.h:64]: nit: the macro name looks like a compiler internal macro.

**Review by snnn — APPROVED** [review]

File: include/onnxruntime/core/common/logging/logging.h (hunk 1 above)
Comment (skottmckay) [reply include/onnxruntime/core/common/logging/logging.h:64]: It's a temporary define which is undef'd as soon as used. Is there a better format to use?

**Comment by skottmckay** [comment]
> Howard Hinnant is out of maintenance. On the other hand, absl::date is not deprecated, and it is already in the list of ORT's dependencies. Anyway we only use it in very a few places. The change would be local.

I assume that's because it was added to the C++20 standard: https://github.com/HowardHinnant/date#standardization

Ideally we'd only use one date library. If there's other functionality from absl::date we need I'm fine with that being the choice (assuming no significant binary size impact). But if this is all short term and we expect the C++20 features to remove the need for a third part date library I'd leave things as-is for now.

File: include/onnxruntime/core/common/logging/logging.h (hunk 1 above)
Comment (snnn) [reply include/onnxruntime/core/common/logging/logging.h:64]: I think `ONNXRUNTIME_SOMETHING` would be better, in case a compiler or std library suddenly use this name.  Anyway, it is not a big deal. Now it is fine.

Comment (edgchen1) [reply include/onnxruntime/core/common/logging/logging.h:64]: technically, identifiers starting with '_' and then an upper-case letter are reserved.

https://en.cppreference.com/w/cpp/language/identifiers

**Review by snnn — APPROVED** [review]

**Review by snnn — APPROVED** [review]

**Review by snnn — APPROVED** [review]

**Review by snnn — APPROVED** [review]

File: onnxruntime/core/platform/apple/logging/apple_log_sink.mm [hunk 2]
```diff
@@ -15,7 +15,9 @@
 void AppleLogSink::SendImpl(const Timestamp& timestamp, const std::string& logger_id, const Capture& message) {
```
Comment (snnn) [inline onnxruntime/core/platform/apple/logging/apple_log_sink.mm:15]: The file still includes the third-party "date.h" header file, even when timestamp_ns refers to std::chrono
