### PR TITLE
Check shape of C is valid for GEMM when fusing MatMul with Add

### LINKED ISSUE #3764: ORT throws GEMM error, but there's no GEMM operator in  model
**Describe the bug**

Attached a model with 3 ops: MatMul, Mul and Add. It should run successfully, but ORT errors out with a message, referencing a `gemm_0` op that doesn't exist in the model.

Where is `gemm_0` coming from? Looks like it's generated on the fly, but that's not  correct because Gemm cannot handle these specific tensor shapes (whereas MatMul, Mul and Add should handle the shapes successfully).

[matmul.zip](https://github.com/microsoft/onnxruntime/files/4557884/matmul.zip)

```python
======== GRAPH ===========
graph tf2onnx (
  %input2:0[FLOAT, 1x4]
  %input1:0[FLOAT, 3x1]
  %input:0[FLOAT, 3x3]
) initializers (
  %Const_1:0[FLOAT, scalar]
) {
  %MatMul:0 = MatMul(%input:0, %input1:0)
  %Mul_1:0 = Mul(%Const_1:0, %input2:0)
  %output:0 = Add(%MatMul:0, %Mul_1:0)
  return %output:0
}
```
image

image

**Urgency**
Bug. A user issue is blocked.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): All OS
- ONNX Runtime installed from (source or binary): 1.2.0 from Pypi
- ONNX Runtime version: 1.2.0
- Python version: 3.7
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Unzip model, and load it using ORT (see screenshot)

**Expected behavior**
Should be able to add and multiply without error.

**Screenshots**
See above

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

### PR DESCRIPTION
**Pull request by skottmckay**
**Description**: 
Check that C is unidirectionally broadcast-able before fusing the MatMul with Add.
Add test.

**Motivation and Context**
Fixes #3764

### CODE REVIEW

File: onnxruntime/core/optimizer/matmul_add_fusion.cc [hunk 1]
```diff
@@ -69,25 +74,32 @@ Status MatMulAddFusion::ApplyImpl(Graph& graph, bool& modified, int graph_level,
...
+    const auto& M = matmul_output.Shape()->dim()[0];
+    const auto& N = matmul_output.Shape()->dim()[1];
+    auto dim_has_value_1 = [](const TensorShapeProto_Dimension& dim) {
+      return dim.has_dim_value() && dim.dim_value() == 1;
+    };
+
+    bool valid = ((bias_shape.dim_size() == 1 && bias_shape.dim()[0] == N) ||
+                  (bias_shape.dim_size() == 2 && dim_has_value_1(bias_shape.dim()[0]) && bias_shape.dim()[1] == N) ||
+                  (bias_shape.dim_size() == 2 && bias_shape.dim()[0] == M &&
+                   (dim_has_value_1(bias_shape.dim()[1]) || bias_shape.dim()[1] == N)));
```
Comment (jignparm) [inline onnxruntime/core/optimizer/matmul_add_fusion.cc:101]: Hi, I believe dim_size() can be > 2, since the output is either a 2-D matrix, or a N-D stacks of matrices, where the last 2 dims are  M, N.

So output shape can be  Z = (I, J, K, ...,M, N).
And legal bias_shape values would be  any rightmost substring of Z, with corresponding entries equal to Z or else 1.

e.g. 
(1, M , N)
(1, 1, M, N)
(1, K, 1, M, 1)

File: onnxruntime/core/optimizer/matmul_add_fusion.cc [hunk 2]
```diff
@@ -69,25 +74,32 @@ Status MatMulAddFusion::ApplyImpl(Graph& graph, bool& modified, int graph_level,
...
-      }
       gemm_input_defs.push_back(add_input_defs[0]);
     }
 
-    if (!graph.GetNodeOutputsInGraphOutputs(node).empty()) {
+    // valid bias_shapes are (N) or (1, N) or (M, 1) or (M, N) as
+    // GEMM only supports unidirectional broadcast on the bias input C
+    const auto& bias_shape = *gemm_input_defs.back()->Shape();
+    const auto& M = matmul_output.Shape()->dim()[0];
+    const auto& N = matmul_output.Shape()->dim()[1];
```
Comment (jignparm) [inline onnxruntime/core/optimizer/matmul_add_fusion.cc:93]: @skottmckay ,thanks for the quick PR!  

For the dim()[1] check above, just wondering if it's always safe? From the doc below, it seems like if we multiply  2 vectors of shape (1,N) * (N,1), we should end up with a scalar, which I'm guessing may not be stored with 2-D shape. Not sure what's our exact implementation of MatMul, but might be good idea to check in case dim()[1] does not exist.

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.matmul.html

File: onnxruntime/core/optimizer/matmul_add_fusion.cc (hunk 1 above)
Comment (skottmckay) [reply onnxruntime/core/optimizer/matmul_add_fusion.cc:101]: This applies doesn't it? https://github.com/onnx/onnx/blob/master/docs/Broadcasting.md#unidirectional-broadcasting

Comment (skottmckay) [reply onnxruntime/core/optimizer/matmul_add_fusion.cc:101]: FWIW this logic is copied from the test in GemmHelper that is used by the GEMM op, so any check here aligns with how ORT GEMM currently works (rightly or wrongly).

File: onnxruntime/core/optimizer/matmul_add_fusion.cc (hunk 2 above)
Comment (skottmckay) [reply onnxruntime/core/optimizer/matmul_add_fusion.cc:93]: It think it should be safe based on earlier checks in this method (line 72) that ensure both inputs are rank 2:

```
    if (2 != matmul_a_shape->dim_size() || 2 != matmul_b_shape->dim_size()) {
      // Gemm only support Matrix
      continue;
    }
```

and the MatMul ONNX shape inferencing where it uses dim 0 from the first input and dim 1 from the second when each is rank 2.

File: onnxruntime/core/optimizer/matmul_add_fusion.cc (hunk 1 above)
Comment (jignparm) [reply onnxruntime/core/optimizer/matmul_add_fusion.cc:101]: It looks like the GemmHelper checks will work for 2D matrices -- but probably give incorrect results for general N-D . The link you pasted  above looks correct to me however, since it's got higher dimensional examples and description.

Not sure why the GemmHelper is different from the documentation -- there might be some historical reason for it (which may or may not apply today).

One option is to  update the code/logic in both locations (to make everything work for N-D). 

Another option is to  keep the current 2D logic, and simply not do a op-fusion if shape > 2D, since we won't know if the shapes are truly compatible.,

File: onnxruntime/core/optimizer/matmul_add_fusion.cc (hunk 2 above)
Comment (jignparm) [reply onnxruntime/core/optimizer/matmul_add_fusion.cc:93]: Ok, great - line 72 was just above the fold

File: onnxruntime/core/optimizer/matmul_add_fusion.cc (hunk 1 above)
Comment (jignparm) [reply onnxruntime/core/optimizer/matmul_add_fusion.cc:101]: Based on line 72,  it seems like only 2D is supported -- in which case this logic looks Ok. 

Signing off.
