### PR TITLE
[js/web] do not use nodejs type 'Buffer' in web

### LINKED ISSUE #9757: `Buffer is not defined` when using WebGL runtime
**Describe the bug**
On line 11711 of ort.js (v1.9.0) `Buffer.from(...)` is called, but `Buffer` is not defined:

```js
if (attr instanceof onnx_proto_1.onnx.AttributeProto) {
    var utf8String = value;
    return Buffer.from(utf8String.buffer, utf8String.byteOffset, utf8String.byteLength).toString();
}
```

I thought that this `Buffer` might have been a Node.js polyfill, but I tried importing the [feross/buffer](https://josephrocca.github.io/anime-gan-v2-web/onnx.html) polyfill and it didn't work - seems that Node's `Buffer.from` only takes 2 arguments.

**Urgency**
Not urgent

**System information**
- ONNX Runtime Version: https://cdn.jsdelivr.net/npm/onnxruntime-web@1.9.0/dist/ort.js
- Tested on Firefox 94 and Chrome 95 (latest versions)

**To Reproduce**
Visit this page: https://josephrocca.github.io/anime-gan-v2-web/onnx.html (switch to the WebGL runtime and then click "start")

The github repo is here: https://github.com/josephrocca/anime-gan-v2-web

**Screenshots**
image

**Additional context**
It works fine with the wasm runtime. The [original model](https://github.com/josephrocca/anime-gan-v2-web/blob/main/anime-gan-v2.onnx) used some int64 values (and the WebGL backend [does not support int64](https://github.com/microsoft/onnxruntime/issues/9724)) so I converted it to int32 using [this script](https://github.com/aadhithya/onnx-typecast). That said, I doubt this is relevant. Seems more likely to just be a bundling issue, or something like that.

### PR DESCRIPTION
**Pull request by fs-eire**
**Description**: This change fixes #9757.

### CODE REVIEW

File: js/web/lib/onnxjs/util.ts [hunk 1]
```diff
@@ -1249,3 +1249,11 @@ export class PoolConvUtil {
 
 export const MIN_CLIP = -3.4028234663852886e+38;
 export const MAX_CLIP = 3.4028234663852886e+38;
+
+export function decodeUtf8String(buffer: Uint8Array): string {
+  if (typeof Buffer !== 'undefined' && Buffer.from) {
+    return Buffer.from(buffer.buffer, buffer.byteOffset, buffer.byteLength).toString();
```
Comment (hariharans29) [inline js/web/lib/onnxjs/util.ts:1255]: Is there something that is available in both Node.js and browsers ? Do we need an if...else here to handle the platforms that `Buffer` might be missing ?

File: js/web/lib/onnxjs/attribute.ts [hunk 2]
```diff
@@ -181,8 +181,7 @@ export class Attribute {
       // format strings attributes are returned as string[], so no conversion is needed.
       if (attr instanceof onnx.AttributeProto) {
         const utf8Strings = value as Uint8Array[];
-        return utf8Strings.map(
-            utf8String => Buffer.from(utf8String.buffer, utf8String.byteOffset, utf8String.byteLength).toString());
+        return utf8Strings.map(decodeUtf8String);
```
Comment (hariharans29) [inline js/web/lib/onnxjs/attribute.ts:184]: Do we not have a model that uses a string attribute in web testing ? It seems like if we had and Buffer is not supported on browsers, this issue would have been caught. If we don't have such a model, can we add one ?

File: js/web/lib/onnxjs/util.ts (hunk 1 above)
Comment (fs-eire) [reply js/web/lib/onnxjs/util.ts:1255]: For test (ort.dev.js), we have nodejs polyfill for web. but we prefer the TextDecoder from standard WebAPI (https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder)

Comment (fs-eire) [reply js/web/lib/onnxjs/util.ts:1255]: Will update to use TextDecoder in both Nodejs and Web since it is universal availale

File: js/web/lib/onnxjs/attribute.ts (hunk 2 above)
Comment (fs-eire) [reply js/web/lib/onnxjs/attribute.ts:184]: I removed polyfill for 'Buffer' for test (with some changes in test code to support the change).

**Review by hariharans29 — APPROVED** [review]
