### PR TITLE
Resolve GH issue 12706

### LINKED ISSUE #12706: CUDA onnxruntime-gpu=1.12.1 inference result differs from onnxruntime-gpu=1.11.0
**Describe the bug**

1.12.1 inference result differs from 1.11.0
The bug only with CUDA.
Works fine on CPU and DML.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win 10
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.12.1
- Python version: 3.7
- CUDA/cuDNN version: 11.5
- GPU model and memory: RTX 3090

**To Reproduce**

dl https://github.com/iperov/DeepFaceLive/releases/download/trash/onnxruntime-1-12-1-bug.zip
unzip
run repro.py with onnxruntime-gpu==1.11.0 you will see the pic
onnxruntime1 11 0

run repro.py with onnxruntime-gpu==1.12.1 you will see different pic
onnxruntime 1 12 1

**Expected behavior**
Expected same inference result as on 1.11.0

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: 
Only the CPU Resize kernel handlles NHWC input. Adjust the Transpose optimizer's Resize handler accordingly. Without this, the CUDA Resize kernel runs the NCHW logic on NHWC input and produces garbage output. 

**Motivation and Context**
Fix regression in 1.12 (Resolve #12706)
Relevant PR - https://github.com/microsoft/onnxruntime/pull/10824

### CODE REVIEW

File: onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc [hunk 1]
```diff
@@ -968,6 +968,13 @@ static void PermuteInput(api::GraphRef& graph, api::NodeRef& node, size_t i, con
 }
 
 static bool HandleResize(HandlerArgs& args) {
+  // TODO: Only the CPU Resize kernel handles NHWC input.
+  // Adjust this restriction once the other EPs' Resize
+  // kernel(s) supports NHWC input.
+  if (args.node.GetExecutionProviderType() != "CPUExecutionProvider") {
+    return false;
```
Comment (hariharans29) [inline onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc:975]: Needs some more thought as the TransposeOptimizer is a L1 optimizer and there is no partitioning info at this point. But, we do need to handle the CUDA EP case as the CUDA Resize kernel is implemented assuming the provided input is NCHW.
CC:@ [yihonglyu](https://github.com/yihonglyu). Any comment ? This causes a regression for CUDA EP users in 1.12.

**Review by yufenglee — APPROVED** [review]

File: onnxruntime/test/optimizer/transpose_optimizer_test.cc [hunk 2]
```diff
@@ -294,6 +294,17 @@ TEST(TransposeOptimizerTests, TestPadNonconst) {
...
+// Resize can't be supported in ORT builds with CUDA enabled.
+// TODO: Enable this once the CUDA Resize kernel is implemented
+// "generically" (i.e.) aligning with the generic nature of the
+// ONNX spec.
+// See https://github.com/microsoft/onnxruntime/pull/10824 for
+// a similar fix applied to the CPU Resize kernel.
+// Per tests included in #10824, the ROCM EP also generates
+// incorrect results when this handler is used, so the Resize
+// handler is not enabled even for those builds.
+#if !defined(USE_CUDA) && !defined(USE_ROCM)
```
Comment (yihonglyu) [inline onnxruntime/test/optimizer/transpose_optimizer_test.cc:307]: Is it possible to give a warning or skip instead just comment out the tests for CUDA or ROCM?

Comment (hariharans29) [reply onnxruntime/test/optimizer/transpose_optimizer_test.cc:307]: Given that the resize handler is not part of such builds (CUDA or ROCM), we will have to skip it (can't even continue with warning). But I am curious what value will it ahead instead of this ? Can you elaborate please ?

File: onnxruntime/test/optimizer/transpose_optimizer_test.cc [hunk 3]
```diff
@@ -498,6 +509,7 @@
                     /*opset_version*/ 13);
 }
 
+#endif
 TEST(TransposeOptimizerTests, TestAdd) {
```
Comment (skottmckay) [inline onnxruntime/test/optimizer/transpose_optimizer_test.cc:513]: nit: `#endif // !defined(USE_CUDA) && !defined(USE_ROCM)` would be nicer

**Review by skottmckay — APPROVED** [review]
:shipit:

File: onnxruntime/test/optimizer/transpose_optimizer_test.cc (hunk 3 above)
Comment (hariharans29) [reply onnxruntime/test/optimizer/transpose_optimizer_test.cc:513]: Thanks. I will include the change in another PR to avoid running all the CIs again.
