### PR TITLE
[Fix #11447] Use correct type for tensor shape vectors

### LINKED ISSUE #11447: Wrong type used in ACL provider's pool.cc
**Describe the bug**

[Line 50 of core/providers/acl/nn/pool.cc](https://github.com/microsoft/onnxruntime/blob/3f3c5fcd682cbc3f6682bbe3c79a68769c187002/onnxruntime/core/providers/acl/nn/pool.cc#L50) currently reads:

```c++
std::vector<int64_t> output_dims = pool_attrs.SetOutputSize(x_shape, x_shape[1], &pads);
```

`pool_attrs` is of type `onnxruntime::PoolAttributes` and its `SetOutputSize` method [defined here](https://github.com/microsoft/onnxruntime/blob/3f3c5fcd682cbc3f6682bbe3c79a68769c187002/onnxruntime/core/providers/cpu/nn/pool_attributes.h#L98) returns `TensorShapeVector` which is a `std::vector<int64_t>` only when [abseil is disabled](https://github.com/microsoft/onnxruntime/blob/3f3c5fcd682cbc3f6682bbe3c79a68769c187002/include/onnxruntime/core/framework/tensor_shape.h#L46). The same issue appears multiple times in this file.

I'm currently building the ACL provider on a Jetson Nano (v1.11.0, but the issue is still there on the current master branch) and this file would break the build and throw errors because of the typing mismatch. Explicitly using `TensorShapeVector` or `auto` solves the issue and the build proceeds.

**To Reproduce**
Build the ACL provider with absl enabled

**Expected behavior**
It builds.

### PR DESCRIPTION
**Pull request by GPhilo**
**Description**: 

Fixes #11447 by using `auto` or explicitly `TensorShapeVector` where appropriate.

There are other points in the code where `std::vector`s are used in what looks like should be either a `TensorShape` or a `TensorShapeVector`, but as I don't have sufficient familiarty with the code, I did not add any fix beyond the necessary ones to make the code compile without errors.

### CODE REVIEW

File: onnxruntime/core/providers/acl/nn/pool.cc [hunk 1]
```diff
@@ -37,17 +37,17 @@ ACLNEPool PoolOperation(onnxruntime::OpKernelContext* context,
   const Tensor* X = context->Input<Tensor>(0);
   const TensorShape& x_shape = X->Shape();
 
-  std::vector<int64_t> pads = pool_attrs.pads;
-  std::vector<int64_t> strides = pool_attrs.strides;
-  std::vector<int64_t> kernel_shape = pool_attrs.kernel_shape;
+  auto pads = pool_attrs.pads;
```
Comment (snnn) [inline onnxruntime/core/providers/acl/nn/pool.cc:40]: Do you need to make a copy of the object? If not. it should be auto& or const auto&

**Comment by GPhilo** [comment]
I don't know if it's needed, though in the original code those were copies so I kept them as they were.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

File: onnxruntime/core/providers/acl/nn/pool.cc (hunk 1 above)
Comment (GPhilo) [reply onnxruntime/core/providers/acl/nn/pool.cc:40]: I don't know if it's needed, though in the original code those were copies so I kept them as they were.

**Comment by hariharans29** [comment]
@jywu-msft : Do you know who the code owner(s) for the ACL provider are for reviewing this ?

**Comment by jywu-msft** [comment]
> @jywu-msft : Do you know who the code owner(s) for the ACL provider are for reviewing this ?

there are no active maintainers currently.

File: onnxruntime/core/providers/acl/nn/pool.cc [hunk 2]
```diff
@@ -37,17 +37,17 @@ ACLNEPool PoolOperation(onnxruntime::OpKernelContext* context,
...
+  auto kernel_shape = pool_attrs.kernel_shape;
 
   if (pool_attrs.global_pooling) {
     const auto& input_dims = x_shape.GetDims();
     kernel_shape.assign(input_dims.begin() + 2, input_dims.end());
     pads.assign(kernel_shape.size(), 0);
   }
 
-  std::vector<int64_t> output_dims = pool_attrs.SetOutputSize(x_shape, x_shape[1], &pads);
+  auto output_dims = pool_attrs.SetOutputSize(x_shape, x_shape[1], &pads);
```
Comment (yuslepukhin) [inline onnxruntime/core/providers/acl/nn/pool.cc:50]: >output_dims [](http://example.com/codeflow?start=7&length=11)

Should be a const reference

**Comment by yuslepukhin** [comment]
>       std::vector<int64_t> aclStrides(2);

TensorShapeVector

---
Refers to: onnxruntime/core/providers/acl/nn/pool.cc:66 in c12d488. [](commit_id = c12d488483c6da4116e224e18fcbbefc4bcbf053, deletion_comment = False)

**Comment by yuslepukhin** [comment]
>       std::vector<int64_t> aclPads(4);

TensorShapeVector

---
Refers to: onnxruntime/core/providers/acl/nn/pool.cc:70 in c12d488. [](commit_id = c12d488483c6da4116e224e18fcbbefc4bcbf053, deletion_comment = False)

File: onnxruntime/core/providers/acl/nn/pool.cc (hunk 1 above)
Comment (yuslepukhin) [reply onnxruntime/core/providers/acl/nn/pool.cc:40]: You can just make them const auto& and see if it compiles

**Comment by yuslepukhin** [comment]
>       std::vector<int64_t> aclKernelShape(2);

TensorShapeVector

---
Refers to: onnxruntime/core/providers/acl/nn/pool.cc:94 in c12d488. [](commit_id = c12d488483c6da4116e224e18fcbbefc4bcbf053, deletion_comment = False)

File: onnxruntime/core/providers/acl/nn/pool.cc [hunk 3]
```diff
@@ -145,7 +145,7 @@ Status Pool<T, PoolType>::Compute(OpKernelContext* context) const {
 
   const Tensor* X = context->Input<Tensor>(0);
 
-  std::vector<int64_t> dilations(PoolBase::pool_attrs_.dilations);
+  TensorShapeVector dilations(PoolBase::pool_attrs_.dilations);
   std::vector<int64_t> aclDilations(2);
```
Comment (yuslepukhin) [inline onnxruntime/core/providers/acl/nn/pool.cc:149]: >std::vector<int64_t> [](http://example.com/codeflow?start=2&length=20)

InlinedVector

File: onnxruntime/core/providers/acl/nn/pool.cc [hunk 4]
```diff
@@ -191,7 +191,7 @@ template <typename T>
 Status MaxPoolV8<T>::Compute(OpKernelContext* context) const {
   const Tensor* X = context->Input<Tensor>(0);
 
-  std::vector<int64_t> dilations(PoolBase::pool_attrs_.dilations);
+  TensorShapeVector dilations(PoolBase::pool_attrs_.dilations);
   std::vector<int64_t> aclDilations(2);
```
Comment (yuslepukhin) [inline onnxruntime/core/providers/acl/nn/pool.cc:195]: >std::vector<int64_t> [](http://example.com/codeflow?start=2&length=20)

InlinedVector

**Comment by yuslepukhin** [comment]
Thank you for doing this.

File: onnxruntime/core/providers/acl/nn/pool.cc (hunk 1 above)
Comment (GPhilo) [reply onnxruntime/core/providers/acl/nn/pool.cc:40]: Doesn't compile, but I dont think that would be a good way to check if this is safe to do,as we could end up accidentally modifying the `pads` value of pool_attrs instead of working on a copy of it. As I said, I don't know wnough of how this actually work to know which is the right way, so I'll just stick to what the original semantics were and fix the typing issues

File: onnxruntime/core/providers/acl/nn/pool.cc (hunk 3 above)
Comment (GPhilo) [reply onnxruntime/core/providers/acl/nn/pool.cc:149]: Would this become `absl::InlinedVector<int64_t, 2> aclDilations;` then?

**Comment by GPhilo** [comment]
@yuslepukhin Implemented the changs that you suggested, please have a look (especially where I use absl::InlinedVector, as I don't know if the new code I wrote is exactly what you intended in your comment).

File: onnxruntime/core/providers/acl/nn/pool.cc [hunk 5]
```diff
@@ -91,7 +91,7 @@ ACLNEPool PoolOperation(onnxruntime::OpKernelContext* context,
       arm_compute::PadStrideInfo aclPadStride = arm_compute::PadStrideInfo(aclStrides[0], aclStrides[1],
                                                                            aclPads[0], aclPads[1], aclPads[2], aclPads[3], arm_compute::DimensionRoundingType::FLOOR);
 
-      std::vector<int64_t> aclKernelShape(2);
+      TensorShapeVector aclKernelShape(2);
```
[the remark this answers is not in the document]
Comment (yuslepukhin) [reply onnxruntime/core/providers/acl/nn/pool.cc:94]: It is evidently necessary.

File: onnxruntime/core/providers/acl/nn/pool.cc (hunk 3 above)
Comment (yuslepukhin) [reply onnxruntime/core/providers/acl/nn/pool.cc]: onnxruntime::InlinedVector<int64_t>

**Review by yuslepukhin — CHANGES_REQUESTED** [review]
:clock1:

File: onnxruntime/core/providers/acl/nn/pool.cc [hunk 6]
```diff
@@ -63,11 +63,11 @@ ACLNEPool PoolOperation(onnxruntime::OpKernelContext* context,
     if (pool_attrs.global_pooling) {
       layer->configure(tpool.in.get(), tpool.out.get(), arm_compute::PoolingLayerInfo(pool_type));
     } else {
-      std::vector<int64_t> aclStrides(2);
+      TensorShapeVector aclStrides(2);
       aclStrides[0] = (strides.size() == 2) ? strides[1] : 1;
       aclStrides[1] = strides[0];
 
-      std::vector<int64_t> aclPads(4);
+      absl::InlinedVector<int64_t, 4> aclPads;
```
[the remark this answers is not in the document]
Comment (GPhilo) [reply onnxruntime/core/providers/acl/nn/pool.cc:70]: Right, that of course makes sense.

File: onnxruntime/core/providers/acl/nn/pool.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (GPhilo) [reply onnxruntime/core/providers/acl/nn/pool.cc:94]: Yes, the question was due to the fact that InlinedVector already allocates the space, so I wasn't sure if the `(2)` had the same semantic a with `std::vector`, but after looking up absl::InlinedVector I understand better how this works.

File: onnxruntime/core/providers/acl/nn/pool.cc [hunk 7]
```diff
@@ -63,11 +64,11 @@ ACLNEPool PoolOperation(onnxruntime::OpKernelContext* context,
     if (pool_attrs.global_pooling) {
       layer->configure(tpool.in.get(), tpool.out.get(), arm_compute::PoolingLayerInfo(pool_type));
     } else {
-      std::vector<int64_t> aclStrides(2);
+      TensorShapeVector aclStrides(2);
       aclStrides[0] = (strides.size() == 2) ? strides[1] : 1;
       aclStrides[1] = strides[0];
 
-      std::vector<int64_t> aclPads(4);
+      InlinedVector<int64_t, 4> aclPads(4);
```
Comment (yuslepukhin) [inline onnxruntime/core/providers/acl/nn/pool.cc:71]: >, 4> [](http://example.com/codeflow?start=27&length=4)

Please, let InlinedVector to figure out the inlined size on its own. This would not compile if you replaced it back to std::vector.

Comment (GPhilo) [reply onnxruntime/core/providers/acl/nn/pool.cc]: Done. In a previous version I tried without it and it didn't compile, so I thought it had to be explicit, but I see now that I had a different error causing the build fail.

**Review by yuslepukhin — DISMISSED** [review]

**Comment by wangyunxiaa** [comment]
by the way, could you please have a look at this file about function PoolOperation, I build it on ubuntu18.04,with follwings commond 
`./build.sh --android --android_ndk_path=/models/software/android-ndk-r21e --config=MinSizeRel --minimal_build --disable_ml_ops --disable_exceptions --build_shared_lib --skip_tests --parallel`
I can get the android libonnxruntime.so,
but when I open acl I got error:
with acl build commond 
`./build.sh --android --android_ndk_path=/models/software/android-ndk-r21e --config=MinSizeRel --minimal_build --disable_abseil --use_acl=ACL_2002 --acl_home=/models/software/arm_compute-v20.02-bin-linux/ --acl_libs=/models/software/arm_compute-v20.02-bin-linux/lib/linux-arm64-v8a-neon --disable_ml_ops --disable_exceptions --build_shared_lib --skip_tests --parallel
`
```
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:184:21: error: no matching function for call to 'PoolOperation'
  ACLNEPool pPool = PoolOperation<T>(context, pool_type, PoolBase::pool_attrs_, it, insert);
                    ^~~~~~~~~~~~~~~~
/models/onnxruntime/onnxruntime/core/providers/acl/nn/pool.cc:220:21: error: no matching function for call to 'PoolOperation'
  ACLNEPool pPool = PoolOperation<T>(context, arm_compute::PoolingType::MAX, PoolBase::pool_attrs_, it, insert);
                    ^~~~~~~~~~~~~~~~
```

**Comment by snnn** [comment]
[GPhilo](https://github.com/GPhilo), could you please rebase this PR? I can't get the lint task pass without your help.

**Comment by GPhilo** [comment]
@snnn Done. I also noticed that the commits had the wrong user and email address, so I fixed that too while I was at it.

**Comment by yuslepukhin** [comment]
azp run Linux CPU CI Pipeline, Linux CPU Minimal Build E2E CI Pipeline, Linux CPU x64 NoContribops CI Pipeline, Linux GPU CI Pipeline, Linux GPU TensorRT CI Pipeline, Linux Nuphar CI Pipeline, Linux OpenVINO CI Pipeline, MacOS CI Pipeline

**Comment by yuslepukhin** [comment]
@GPhilo we just need to wait a bit so the CI build machines are updated to new images

**Review by snnn — APPROVED** [review]
