### PR TITLE
Extend holding onto the mutex in CUDA Conv

### LINKED ISSUE #3828: cuDNN error when running multi-thread evaluation
We have some code to call the same `InferenceSession` in multiple threads. And we randomly see the following crashes:

> Non-zero status code returned while running Conv node. Name:'onnx_op_2' Status Message: CUDNN error executing cudnnConvolutionForward(CudnnHandle(), &alpha, s_.x_tensor, x_data, s_.filter_desc, w_data, s_.conv_desc, s_.algo, workspace.get(), s_.workspace_bytes, &beta, s_.y_tensor, y_data)

> Non-zero status code returned while running Conv node. Name:'' Status Message: CUDNN error executing cudnnAddTensor(CudnnHandle(), &alpha, s_.b_tensor, b_data, &alpha, s_.y_tensor, y_data)

We figured out this is a thread-safety problem in CUDA covolution implementation. Here are the detail explanation:

In the compute function of Conv, a mutex guards the following block in `cuda/nn/conv.cc`:

https://github.com/microsoft/onnxruntime/blob/5dfc91db51c1c9fc63c046c8ff3dc682d9b7797d/onnxruntime/core/providers/cuda/nn/conv.cc#L55-L169

However, just below this block, there are calls to cuDNN API using the shared cuDNN state `s_`:

https://github.com/microsoft/onnxruntime/blob/5dfc91db51c1c9fc63c046c8ff3dc682d9b7797d/onnxruntime/core/providers/cuda/nn/conv.cc#L185

https://github.com/microsoft/onnxruntime/blob/5dfc91db51c1c9fc63c046c8ff3dc682d9b7797d/onnxruntime/core/providers/cuda/nn/conv.cc#L202

Therefore, when multi-thread evaluation hits `cudnnConvolutionForward` or `cudnnAddTensor` at the same time, the cuDNN call may fail when the shapes of tensors are different on different thread. Our solution for this is extend the mutex scope to include to two cuDNN calls.

### PR DESCRIPTION
**Pull request by hariharans29**
**Description**: Extend holding onto the mutex in CUDA Convolution until we are done with all CuDNN calls

**Motivation and Context**
Fix #3828

### CODE REVIEW

File: onnxruntime/core/providers/cuda/nn/conv.cc [hunk 1]
```diff
@@ -166,40 +166,40 @@ Status Conv<T>::ComputeInternal(OpKernelContext* context) const {
...
+                                                  &beta,
+                                                  s_.y_tensor,
+                                                  y_data));
+
+    if (has_bias) {
+      const Tensor* B = context->Input<Tensor>(2);
+      auto b_data = reinterpret_cast<const CudaT*>(B->template Data<T>());
+      CUDNN_RETURN_IF_ERROR(cudnnAddTensor(CudnnHandle(), &alpha, s_.b_tensor, b_data, &alpha, s_.y_tensor, y_data));
+    }
   }
```
Comment (hariharans29) [inline onnxruntime/core/providers/cuda/nn/conv.cc:203]: This brace moved down here is the only change

File: onnxruntime/core/providers/cuda/nn/conv.cc [hunk 2]
```diff
@@ -166,40 +166,40 @@ Status Conv<T>::ComputeInternal(OpKernelContext* context) const {
       s_.algo = perf.algo;
       s_.workspace_bytes = perf.memory;
     }
-  }
```
Comment (hariharans29) [inline onnxruntime/core/providers/cuda/nn/conv.cc:169]: Move this brace down until after all CuDNN calls and effectively hold onto the mutex until it is safe to be released
