### PR TITLE
[java] Allows the creation and extraction of zero length tensors

### LINKED ISSUE #7270: ai.onnxruntime.OrtException: This tensor is not representable in Java, it's too big
get `This tensor is not representable in Java, it's too big`, while inference fasterrcnn_resnet50_fpn model in onnx.

export_onnx.py (Python Source):
```
    model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    x = [torch.rand(3, 1970, 1080)]
    torch.onnx.export(model, x, "faster_rcnn.onnx", opset_version = 11)
```

build.gradle (Gradle Source):
```
    dependencies {
          implementation group: 'com.microsoft.onnxruntime', name: 'onnxruntime', version: '1.7.0'
    }
```

Pridiction.java (Java Source):
```
47| try(OrtSession session = env.createSession(modelPath.toFile().getAbsolutePath(), 
48|                    new OrtSession.SessionOptions())) {
49|
50|     OnnxTensor t1 = OnnxTensor.createTensor(env, sourceData, dimensions);
51|     OrtSession.Result result = session.run(Collections.singletonMap("image.1", t1));
52|
53|     for (int i = 0; i < result.size(); i++) {
54|         System.out.println(result.get(i).getValue());
55|     }
56|
57|     result.close();
58|     t1.close();
59| }
```

Exception while inference:
```
ai.onnxruntime.OrtException: This tensor is not representable in Java, it's too big - shape = [0, 4]
	at ai.onnxruntime.TensorInfo.makeCarrier(TensorInfo.java:171)
	at ai.onnxruntime.OnnxTensor.getValue(OnnxTensor.java:99)
	at onnx.predict.Pridiction.main(Pridiction.java:54)
```

Refered sites:
```
       1. https://www.onnxruntime.ai/docs/reference/api/java-api.html
       2. https://pytorch.org/vision/stable/models.html#faster-r-cnn
```

### PR DESCRIPTION
**Pull request by Craigacp**
### Description
Allows the creation of zero length tensors via the buffer path (the array path with zero length arrays still throws as the validation logic to check it's not ragged would require more intrusive revision), and allows the `tensor.getValue()` method to return a Java multidimensional array with a zero dimension. Also added a test for the creation and extraction behaviour.

### Motivation and Context
The Python interface can return zero length tensors (e.g. if object detection doesn't find any objects), and before this PR in Java calling `tensor.getValue()` throws an exception with a confusing error message. Fixes #7270 & #15107.

### CODE REVIEW

**Comment by Craigacp** [comment]
@yuslepukhin would you mind taking a look at this? It fixes a behaviour difference between Java & Python which people run into when deploying object recognition systems that don't find any objects in the supplied image.

**Comment by yuslepukhin** [comment]
> @yuslepukhin would you mind taking a look at this? It fixes a behaviour difference between Java & Python which people run into when deploying object recognition systems that don't find any objects in the supplied image.

I think you mean scalar tensors. They are not zero length. They do have empty shapes, however, the length is 1.

**Comment by Craigacp** [comment]
> > @yuslepukhin would you mind taking a look at this? It fixes a behaviour difference between Java & Python which people run into when deploying object recognition systems that don't find any objects in the supplied image.
> 
> I think you mean scalar tensors. They are not zero length. They do have empty shapes, however, the length is 1. Correct me if I am wrong.

No, those are already supported in the Java API. This specifically deals with the case where a tensor is used with a variable dimension that happens to be zero. For example if the output shape is`[num_objects, 4]` but the specific output tensor is of size `[0, 4]` because no objects were detected. The current behaviour in the Java API is to throw an exception with a confusing error message when `tensor.getValue()` is called, the new behaviour is to return a `float[0][4]` (or similar), which is closer to what Python does, which is return a numpy array with shape `[0,4]`.

File: java/src/main/java/ai/onnxruntime/OrtUtil.java [hunk 1]
```diff
@@ -41,9 +41,9 @@ public static int[] transformShape(long[] shape) {
     int[] newShape = new int[shape.length];
     for (int i = 0; i < shape.length; i++) {
       long curDim = shape[i];
-      if (curDim < 1 || curDim > Integer.MAX_VALUE) {
+      if (curDim < 0 || curDim > Integer.MAX_VALUE) {
```
Comment (yuslepukhin) [inline java/src/main/java/ai/onnxruntime/OrtUtil.java:44]: >urDim < 0 [](http://example.com/codeflow?start=11&length=9)

dimension that has a value of -1 indicates that this is a symbolic dimension that has a symbolic name in that position, but otherwise it is a valid dimension.

I think it would be beneficial to run onnx models with Java API and see any adjustments necessary.

Comment (Craigacp) [reply java/src/main/java/ai/onnxruntime/OrtUtil.java:44]: Yeah, we have tests for symbolic dimension behaviour - https://github.com/microsoft/onnxruntime/blob/main/java/src/test/java/ai/onnxruntime/InferenceTest.java#L576. Everything I've tested works, but the initial version of this code I wrote many years ago didn't cope with zero length tensors because I couldn't figure out why they would occur. This change is to rewrite some of that validation and allow them through.

**Review by yuslepukhin — APPROVED** [review]
Ship
