### PR TITLE
[build] fix macOS x86_64 cross-compile warning

### LINKED ISSUE #23180: [Build] error: array index 7 is past the end of the array (that has type '__m256[4]')
### Describe the issue

Build fails with version 1.20.1 while it succeeded with version 1.18.2:

```
In file included from /usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx512.cpp:25:
In file included from /usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx512_int8_blklen16.h:9:
In file included from /usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx512_int8_blklen32.h:8:
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:49: error: array index 4 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                 ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:57: error: array index 5 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                         ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:65: error: array index 6 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                                 ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:73: error: array index 7 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                                         ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
4 errors generated.
```

### Urgency

_No response_

### Target platform

FreeBSD 14.2

### Build script

cmake && gmake

### Error / output

Build fails:
```
In file included from /usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx512.cpp:25:
In file included from /usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx512_int8_blklen16.h:9:
In file included from /usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx512_int8_blklen32.h:8:
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:49: error: array index 4 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                 ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:57: error: array index 5 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                         ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:65: error: array index 6 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                                 ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:954:73: error: array index 7 is past the end of the array (that has type '__m256[4]') [-Werror,-Warray-bounds]
  954 |                 __m128 acc_1 = FoldAccumulators(acc[4], acc[5], acc[6], acc[7]);
      |                                                                         ^   ~
/usr/ports/misc/onnxruntime/work/onnxruntime-1.20.1/onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:822:13: note: array 'acc' declared here
  822 |             __m256 acc[NCols4];
      |             ^
4 errors generated.
```

### Visual Studio Version

_No response_

### GCC / Compiler Version

clang-18

### PR DESCRIPTION
**Pull request by fs-eire**
### Description

This pull request introduces a new compiler flag check for `-Warray-bounds` and addresses a Clang-specific warning in the `MlasQ4Int8TileGemmKernelBlkLen32Avx2` function.

The warning is generated in unreachable code, however it is still triggered the warning. Anyway add the change to make Clang happy.

Fixes #23180

### CODE REVIEW

File: onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h [hunk 1]
```diff
@@ -1660,7 +1660,24 @@ MlasQ4Int8TileGemmKernelBlkLen32Avx2(
 
             if constexpr (NCols4 == 8) {
                 __m128 acc_0 = FoldAccumulators(acc[0], acc[1], acc[2], acc[3]);
+
```
Comment (snnn) [inline onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:1663]: Or you rewrite the code to remove the if constexpr usages? I think the current code is a little bit complicated that clang does not know this branch cannot be reached.

**Review by snnn — DISMISSED** [review]

File: onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h (hunk 1 above)
Comment (fs-eire) [reply onnxruntime/core/mlas/lib/sqnbitgemm_kernel_avx2_int8_blklen32.h:1663]: The whole `MlasQ4Int8TileGemmKernelBlkLen32Avx2` function seems not used anywhere. I try to keep the code there for future reference.

**Comment by snnn** [comment]
There are several open Github issues related to this.  Please find them and reference them here.

**Review by snnn — APPROVED** [review]
