### PR TITLE
Fix C# handling of unicode strings

### LINKED ISSUE #2690: C# - Unicode characters in string input tensors not translated correctly
**Describe the bug**
An input string tensor,  containing unicode chars,  gets translated to an unexpected value.

**Urgency**
Bug

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows**
- ONNX Runtime installed from (source or binary): **V 1.0 from source**
- ONNX Runtime version: **1.0**
- Python version: **N/A**
- Visual Studio version (if applicable): **2017**
- GCC/Compiler version (if compiling from source): **N/A**
- CUDA/cuDNN version: **N/A** 
- GPU model and memory: **N/A**

**To Reproduce**

Modify the C# unit test (InferenceTest.cs) to include a unicode character as shown below and run the test. It will fail, indicating the returned output tensor does not match the input tensor.

```C#
        [Fact]
        private void TestModelInputSTRING()
        {
            // model takes 1x5 input of fixed type, echoes back
            string modelPath = Path.Combine(Directory.GetCurrentDirectory(), "test_types_STRING.pb");
            using (var session = new InferenceSession(modelPath))
            {
                var container = new List<NamedOnnxValue>();
                var tensorIn = new DenseTensor<string>(new string[] { "hello...\u017E", "ced", "def", "", "frozen" }, new int[] { 1, 5 });
                var nov = NamedOnnxValue.CreateFromTensor("input", tensorIn);
                container.Add(nov);
                using (var res = session.Run(container))
                {
                    var tensorOut = res.First().AsTensor<string>();
                    Assert.True(tensorOut.SequenceEqual(tensorIn));
                }
            }
        }
```

**Expected behavior**

In the unit test above, the output string tensor should match the input string tensor.

**Screenshots**

Setting a debugger breakpoint in the unit test above, the values of tensorIn do not match the values of tensorOut
image

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

### PR DESCRIPTION
**Pull request by jignparm**
**Description**: Fixes #2690: Add Unicode string tensor support for model inputs

**Motivation and Context**
- Fixes conversion of UTF-16 to UTF-8 characters for multi-byte characters.
- Includes fix for pinning managed memory prior to invoking OrtFillStringTensor()
- Update unit test to include Latin, Chinese, and other characters.

### CODE REVIEW

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs [hunk 1]
```diff
@@ -218,12 +218,22 @@ out nativeTensor
...
+                        var utf8str = UTF8Encoding.UTF8.GetBytes(tensorValue.GetValue(i) + "\0");
+                        pinnedHandles[i] = GCHandle.Alloc(utf8str, GCHandleType.Pinned);
+                        stringsInTensor[i] = pinnedHandles[i].AddrOfPinnedObject();
                     }
-                    NativeApiStatus.VerifySuccess(NativeMethods.OrtFillStringTensor(nativeTensor, stringsInTensor, (UIntPtr)tensorValue.Length));
+
+                    NativeApiStatus.VerifySuccess(NativeMethods.OrtFillStringTensor(nativeTensor, stringsInTensor, (UIntPtr)len));
+                    foreach (var handle in pinnedHandles)
+                    {
+                        handle.Free();
```
Comment (yuslepukhin) [inline csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: > handle.Free(); [](start = 23, length = 15)

Can this be handled in an exception safe manner via IDisposable?

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs [hunk 2]
```diff
@@ -218,12 +218,22 @@ out nativeTensor
...
 
                     // fill the native tensor, using GetValue(index) from the Tensor<string>
-                    string[] stringsInTensor = new string[tensorValue.Length];
+                    var len = tensorValue.Length;
+                    var stringsInTensor = new IntPtr[len];
+                    var pinnedHandles = new GCHandle[len];
                     for (int i = 0; i < tensorValue.Length; i++)
                     {
-                        stringsInTensor[i] = tensorValue.GetValue(i);
+                        var utf8str = UTF8Encoding.UTF8.GetBytes(tensorValue.GetValue(i) + "\0");
```
Comment (yuslepukhin) [inline csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: >UTF8Encoding.UTF8.GetByte [](start = 38, length = 25)

Where do I find the reverse conversion when the results come back from ORT?

File: csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs [hunk 3]
```diff
@@ -773,7 +773,12 @@ private void TestModelInputSTRING()
             using (var session = new InferenceSession(modelPath))
             {
                 var container = new List<NamedOnnxValue>();
-                var tensorIn = new DenseTensor<string>(new string[] { "abc", "ced", "def", "", "frozen" }, new int[] { 1, 5 });
+                var tensorIn = new DenseTensor<string>(new string[] {
+                 "ascii",
+                 "cyrillic\u0416\u0468",
+                 "latin\u017E\u1053",
+                 "chinese\u0187\u0175\u2EC7\u2ED5",
+                 "devangari\u0914\u0917" }, new int[] { 1, 5 });
```
Comment (yuslepukhin) [inline csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: Can you use the following strings here, so we get good coverage?
monday
Besançon
École élémentaire
Понедельник"
mit freundlichen grüßen
中文

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 2 above)
Comment (jignparm) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: The reverse operation is done in NativeOnnxTensorMemory.cs. See below for the exact location.

https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/NativeOnnxTensorMemory.cs#L104

**Comment by snnn** [comment]
Can you use this : https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings ?

UnmanagedType.LPUTF8Str
--

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 1 above)
Comment (jignparm) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: IDisposable is typically useful for managed objects that hold references to native resources (and hence can free the native resources in the Dispose() call). When ORT returns output tensor values, IDisposable objects are in fact used for this same reason.

However, we don't need to use the IDisposable interface for model inputs, since they are already in managed memory, and don't require any special handling (e.g. freeing native memory, closing out open files etc). 

In this block, we need to pin the arrays before the call to native ORT, and unpin right afterwards (GC will handle the objects correctly afterwards).

File: csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs (hunk 3 above)
Comment (jignparm) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: The model takes 5 test strings in a single tensor. However, we can run multiple tensors through it if needed.

What are the "\u0000" values for one or two of the strings you mentioned above? I can replace a couple of the test strings with the recommended values if I know the numerical offsets of the chars.

**Comment by jignparm** [comment]
> Can you use this : https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings ?
> 
> ####UnmanagedType.LPUTF8Str


For .Net Standard projects, `UnmanagedType.LPUTF8Str`  does not look like it's available . It is available for .Net Framework projects however.

The list of marshal-able string types in .Net Standard are below. From the list, there doesn't seem to be a suitable one for UTF8 conversion.

```
        //
        // Summary:
        //     A single byte, null-terminated ANSI character string. You can use this member
        //     on the System.String and System.Text.StringBuilder data types.
        LPStr = 20,
        //
        // Summary:
        //     A 2-byte, null-terminated Unicode character string.
        LPWStr = 21,
        //
        // Summary:
        //     A platform-dependent character string: ANSI on Windows 98, and Unicode on Windows
        //     NT and Windows XP. This value is supported only for platform invoke and not for
        //     COM interop, because exporting a string of type LPTStr is not supported.
        LPTStr = 22,
        //
        // Summary:
        //     Used for in-line, fixed-length character arrays that appear within a structure.
        //     The character type used with System.Runtime.InteropServices.UnmanagedType.ByValTStr
        //     is determined by the System.Runtime.InteropServices.CharSet argument of the System.Runtime.InteropServices.StructLayoutAttribute
        //     attribute applied to the containing structure. Always use the System.Runtime.InteropServices.MarshalAsAttribute.SizeConst
        //     field to indicate the size of the array.
        ByValTStr = 23,
        //
        // Summary:
        //     A value that enables Visual Basic to change a string in unmanaged code and have
        //     the results reflected in managed code. This value is only supported for platform
        //     invoke.
        VBByRefStr = 34,
        //
        // Summary:
        //     An ANSI character string that is a length-prefixed single byte. You can use this
        //     member on the System.String data type.
        AnsiBStr = 35,
       //
        // Summary:
        //     A Windows Runtime string. You can use this member on the System.String data type.
        HString = 47
```

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 2 above)
Comment (yuslepukhin) [inline csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: >"\0" [](start = 91, length = 4)

This is a a double byte zero, can we add a single byte?

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 1 above)
Comment (yuslepukhin) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: Let's talk offline and see what happens when pinned memory is not released on exception. Pinner memory means it is subject to memory management and will stay this way and leak.

---
In reply to: [359646557](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r359646557) [](ancestors = 359646557)

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 2 above)
Comment (yuslepukhin) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: I looked at the code and I believe the conversion is not handled properly that way either.

---
In reply to: [359645025](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r359645025) [](ancestors = 359645025)

File: csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs (hunk 3 above)
Comment (yuslepukhin) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: You do not need to. Just declare normal C# UTF-16 strings and put those chars into it. They should come back the same on the other end.

---
In reply to: [359648568](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r359648568) [](ancestors = 359648568)

Comment (yuslepukhin) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: >>> print(s)
Besançon
>>> s.encode('utf-8')
b'Besan\xc3\xa7on'
>>>

---
In reply to: [359648568](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r359648568) [](ancestors = 359648568)

Comment (yuslepukhin) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: >>> s = "École élémentaire"
>>> s.encode('utf-16')
b'\xff\xfe\xc9\x00c\x00o\x00l\x00e\x00 \x00\xe9\x00l\x00\xe9\x00m\x00e\x00n\x00t\x00a\x00i\x00r\x00e\x00'

---
In reply to: [360150921](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r360150921) [](ancestors = 360150921,359648568)

Comment (yuslepukhin) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: >>> s.encode('utf-16')
b'\xff\xfe\x1f\x04>\x04=\x045\x044\x045\x04;\x04L\x04=\x048\x04:\x04'

---
In reply to: [360161808](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r360161808) [](ancestors = 360161808,360150921,359648568)

Comment (yuslepukhin) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: >>> s = "grüßen"
>>> s.encode('utf-16')
b'\xff\xfeg\x00r\x00\xfc\x00\xdf\x00e\x00n\x00'

---
In reply to: [360162236](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r360162236) [](ancestors = 360162236,360161808,360150921,359648568)

Comment (jignparm) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: Added more tests (in readable character format).

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 2 above)
Comment (jignparm) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: The zero has to be in UTF-16 to start off with, before can call GetBytes(), so double byte seems OK.

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs [hunk 4]
```diff
@@ -218,12 +218,28 @@ out nativeTensor
...
+                        }
+
+                        NativeApiStatus.VerifySuccess(NativeMethods.OrtFillStringTensor(nativeTensor, stringsInTensor, (UIntPtr)len));
+                    }
+                    finally
+                    {
+                        foreach (var handle in pinnedHandles)
+                        {
+                            handle.Free();
+                        }
```
Comment (yuslepukhin) [inline csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: You need to check if the handle is not null since the exception can throw before all of them are created

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs [hunk 5]
```diff
@@ -218,12 +218,28 @@ out nativeTensor
...
                     {
-                        stringsInTensor[i] = tensorValue.GetValue(i);
+                        for (int i = 0; i < tensorValue.Length; i++)
+                        {
+                            var utf8str = UTF8Encoding.UTF8.GetBytes(tensorValue.GetValue(i) + "\0");
+                            pinnedHandles[i] = GCHandle.Alloc(utf8str, GCHandleType.Pinned);
+                            stringsInTensor[i] = pinnedHandles[i].AddrOfPinnedObject();
+                        }
+
+                        NativeApiStatus.VerifySuccess(NativeMethods.OrtFillStringTensor(nativeTensor, stringsInTensor, (UIntPtr)len));
```
Comment (hariharans29) [inline csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: Should any exception be caught and logged ?

File: csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs (hunk 3 above)
Comment (yuslepukhin) [reply csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs]: As long as it works. I think the default encoding for Studio files is UTF-8. Let's make sure the compiler converts it to UTF-16 at the compile time.

---
In reply to: [360188384](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r360188384) [](ancestors = 360188384)

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 5 above)
Comment (yuslepukhin) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: It is caught below

---
In reply to: [360191590](https://github.com/microsoft/onnxruntime/pull/2697#discussion_r360191590) [](ancestors = 360191590)

Comment (hariharans29) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: It goes into finally whether there is an exception or not. My question was more along the lines of - is a catch necessary before the finally (to log any abnormal occurrence) ?

Comment (hariharans29) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: Missed the upper level catch. Got it now.

File: csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs (hunk 4 above)
Comment (jignparm) [reply csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs]: GChandle is a struct object (not class object), so an array of structs should never be null in C#.

However, added a check to see if's been allocated before calling free.
