### PR TITLE
Generalize noop_with_empty_axes handling across all Reduce operators

### LINKED ISSUE #25095: All the reduce ops cause an error with None axis and noop_with_empty_axes=1
### Describe the issue

Test 1 works but Test 2 causes an error.
- **Test 1:** empty axis list [ ] and noop_with_empty_axes=1
  - This correctly returns the input data unchanged.
- **Test 2:** empty axis list None and noop_with_empty_axes=1
  - This should return the input data unchanged but causes an error.

**In summary:**
| Axes list | noop_with_empty_axes | Behavior | Correct behavior |
|----------:|:----:|:-------------------------------------------:|:-------------------------------------------:|
| `[ ]`       | `1` | Returns the input **unchanged** | |
| `[ ]`       | `0` | Reduces **all** dimensions         | |
| `None` | `1` | Raises a **runtime error**            | Returns the input **unchanged** |
| `None` | `0` | Reduces **all** dimensions          | |

# Implementation
The official [ONNX spec](https://onnx.ai/onnx/operators/onnx__ReduceL1.html) ambiguously describes "empty axes" — it’s unclear whether it refers to `None` or to an empty list `[ ]`. However, the "Inputs" section states there can be one or two inputs and that axes is optional, thus I think interpreting "empty axes" as either `None` or `[ ]` aligns with the specification.

# Error
The error below occurs
```
2025-06-17 22:41:27.297103445 [E:onnxruntime:, sequential_executor.cc:572 ExecuteKernel] Non-zero status code returned while running ReduceL1 node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:484 void onnxruntime::ValidateNoTransposeReduce(int64_t) count == 1 was false. Reduction on all axes, output size should be 1.

Traceback (most recent call last):
  File "/home/ysy/Documents/open_source/tvm/source/me/reduce_test.py", line 107, in <module>
    test2()
  File "/home/ysy/Documents/open_source/tvm/source/me/reduce_test.py", line 98, in test2
    result = sess.run(None, {"x": x})
  File "/home/ysy/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 273, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running ReduceL1 node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:484 void onnxruntime::ValidateNoTransposeReduce(int64_t) count == 1 was false. Reduction on all axes, output size should be 1.
```

### To reproduce

```python
import numpy as np
import onnx
from onnx import helper, TensorProto
import onnxruntime as ort

def test1():
    # 1. Create input data
    x = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int64)

    # 2. Create axes initializer for axis 1
    axes = np.array([], dtype=np.int64)
    axes_initializer = helper.make_tensor(
        name="axes",
        data_type=TensorProto.INT64,
        dims=axes.shape,
        vals=axes,
    )

    # 3. Build Reduce node (opset-18)
    node = helper.make_node(
        "ReduceL1",
        inputs=["x", "axes"],
        outputs=["y"],
        keepdims=1,
        noop_with_empty_axes=1,
    )

    # 4. Build the graph
    graph = helper.make_graph(
        [node],
        "Reduce_v18_graph",
        inputs=[helper.make_tensor_value_info("x", TensorProto.INT64, x.shape)],
        initializer=[axes_initializer],
        outputs=[helper.make_tensor_value_info("y", TensorProto.INT64, None)],
    )

    # 5. Create model with opset 18
    model = helper.make_model(
        graph,
        producer_name="reduce_l1_v18",
        opset_imports=[helper.make_opsetid("", 18)],
    )

    # 6. Save the model to disk
    onnx.save(model, "reduce_l1_v18.onnx")

    # 7. Run the model using ONNX Runtime
    sess = ort.InferenceSession("reduce_l1_v18.onnx")
    result = sess.run(None, {"x": x})

    # 8. Print the input
    print("Input array x:")
    print(x)

    # Print the output
    print("Output array y:")
    print(result[0])
test1()

def test2():
    # Create input data
    x = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int64)

    # Build Reduce node (opset-18)
    node = helper.make_node(
        "ReduceL1",
        inputs=["x"],
        outputs=["y"],
        keepdims=1,
        noop_with_empty_axes=1,
    )

    # Build the graph
    graph = helper.make_graph(
        [node],
        "Reduce_v18_graph",
        inputs=[helper.make_tensor_value_info("x", TensorProto.INT64, x.shape)],
        # initializer=[axes_initializer],
        outputs=[helper.make_tensor_value_info("y", TensorProto.INT64, None)],
    )

    # Create model with opset 18
    model = helper.make_model(
        graph,
        producer_name="reduce_l1_v18",
        opset_imports=[helper.make_opsetid("", 18)],
    )

    # Save the model to disk
    onnx.save(model, "reduce_l1_v18.onnx")

    # Run the model using ONNX Runtime
    sess = ort.InferenceSession("reduce_l1_v18.onnx")
    print("Active providers:", sess.get_providers())
    result = sess.run(None, {"x": x})

    # Print the input
    print("Input array x:")
    print(x)

    # Print the output
    print("Output array y:")
    print(result[0])
test2()
```

### Urgency

_No response_

### Platform

Linux

### OS Version

ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.22.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

_No response_

### LINKED ISSUE #26288: Spec changed for reduction ops when noop_with_empty_axes is True
The ONNX spec has fixed the [issue](https://github.com/onnx/onnx/issues/6103) about incorrect behavior for `ReduceSumSquare` and other reduction ops when `noop_with_empty_axes` is true in this [PR](https://github.com/onnx/onnx/pull/7137).

e.g. for `ReduceSumSquare`, when `axes` input is not provided or is empty and `noop_with_empty_axes` is `True`, `square` should be always applied on individual elements. But current implementation just returns the input.

### PR DESCRIPTION
**Pull request by naomiOvad**
### Description

This PR fixes the behavior of the reduction operators so it's aligned with the ONNX specification.
[See ONNX ReduceSumSquare Specification](https://onnx.ai/onnx/operators/onnx__ReduceSumSquare.html)
for the definition of noop_with_empty_axes and expected behavior when axes=[]  or when the axes input is not provided.

Main changes:

- Added a new helper function ApplyNoopEmptyAxesElementwise<AGG>() to handle the case axes=[] and noop_with_empty_axes=1 for all reduction operators (ReduceSumSquare, ReduceL1, ReduceL2, ReduceLogSum, ReduceLogSumExp, etc.).
This function performs elementwise operations according to the aggregator type:

If the aggregator defines Pre/Post operations (e.g., abs, square, sqrt, log), they are applied elementwise on each element of the input without reduction.

Otherwise, a direct memory copy (memcpy) is performed to efficiently produce an identical output.

- Introduced a compile-time trait system ReduceAggTraits to detect whether each aggregator defines a PreOp and/or PostOp.
This allows compile-time specialization and avoids redundant runtime checks.

- Updated the generic reduction paths (CommonReduce1Loop and CommonReduce2Loops)
to invoke ApplyNoopEmptyAxesElementwise<AGG>() when axes=[] and noop_with_empty_axes=1.
These paths are used by all reduction operators, ensuring consistent handling across the entire operators.

- Fixed the conditional inside CommonFastReduceCopy: replaced the previous unconditional memcpy and return true with a safe return false, since empty-axes cases are now fully handled upstream by ApplyNoopEmptyAxesElementwise<AGG>().
This keeps the control flow explicit and prevents unintended fallback copies.

- Added unit tests for all affected reduction operators (ReduceSumSquare, ReduceL1, ReduceL2, ReduceLogSum, ReduceLogSumExp),and corrected one test that previously expected identity output but now correctly applies Pre/Post operations per the ONNX specification.

These updates ensure spec-compliant behavior for all Reduce ops and slightly improve performance for identity cases.

### Motivation and Context
Before this fix, some Reduce operators (e.g., ReduceSumSquare, ReduceL1, ReduceL2, ReduceLogSum, ReduceLogSumExp) did not follow the ONNX spec when axes=[] and noop_with_empty_axes=1.

Per the ONNX specification:

No reduction should occur if axes is empty and noop_with_empty_axes=1.

Operators with Pre/Post (e.g., abs, square, sqrt, log) must apply them elementwise.

Others should return the input unchanged.

Fixes #26288 
Fixes #25095

**Note:** This fix currently applies to the CPU Execution Provider only.  
Other EPs will need a similar update to align with this behavior.

### CODE REVIEW

**Comment by naomiOvad** [comment]
@microsoft-github-policy-service agree

**Comment by naomiOvad** [comment]
@microsoft-github-policy-service agree

**Comment by naomiOvad** [comment]
@skottmckay @snnn could you please review this PR (#26436)? 
Thank you!

**Comment by naomiOvad** [comment]
@fdwr, I’ve pushed fixes for the failed checks but don’t have permissions to re-run them.  
Could you please re-run the CI checks? Thanks!

**Comment by fdwr** [comment]
> @fdwr, I’ve pushed fixes for the failed checks but don’t have permissions to re-run them. Could you please re-run the CI checks? Thanks!

@naomiOvad: Restarted CI's 🫡.

**Comment by naomiOvad** [comment]
cc @xadupre, @yuslepukhin, @skottmckay Could you please review my PR?
Thanks!

File: onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc [hunk 1]
```diff
@@ -4126,14 +4126,10 @@ TEST(ReductionOpTest, ReduceSumSquare_noop_axes_input_initializer_opset_18) {
...
-  test.Run(
-      OpTester::ExpectResult::kExpectSuccess,
-      "",
-      {kTensorrtExecutionProvider,
-       kOpenVINOExecutionProvider,
-       kDnnlExecutionProvider,
-       kDmlExecutionProvider});
+  test.AddOutput<float>("reduced", {1, 2, 2}, {1.0f, 4.0f, 9.0f, 16.0f});
+  auto cpu = DefaultCpuExecutionProvider();
+  if (!cpu) GTEST_SKIP() << "CPU EP not available in this build.";
```
Comment (yuslepukhin) [inline onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc]: CPU is always available. #Resolved

File: onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc [hunk 2]
```diff
@@ -6128,5 +6124,221 @@ TEST(ReductionOpTest, MissingOptionalAxes) {
...
 }
 
+TEST(ReductionOpTest, ReduceSumSquare_NoopWithEmptyAxes_Scalar) {
+  OpTester test("ReduceSumSquare", 18);
+  test.AddInput<float>("data", {}, {-3.f});
+  test.AddInput<int64_t>("axes", {0}, {}, true);
+  test.AddAttribute<int64_t>("noop_with_empty_axes", 1);
+  test.AddOutput<float>("reduced", {}, {9.f});
+  auto cpu = DefaultCpuExecutionProvider();
+  if (!cpu) GTEST_SKIP() << "CPU EP not available in this build.";
```
Comment (yuslepukhin) [inline onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc]: Ditto here and below

File: onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc [hunk 3]
```diff
@@ -6128,5 +6124,221 @@ TEST(ReductionOpTest, MissingOptionalAxes) {
...
+  test.ConfigEp(std::move(cpu)).RunWithConfig();
+}
+TEST(ReductionOpTest, ReduceSumSquare_NoopWithEmptyAxes_ElementwiseSquare) {
```
Comment (fdwr) [inline onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc:6134]:
```suggestion

TEST(ReductionOpTest, ReduceSumSquare_NoopWithEmptyAxes_ElementwiseSquare) {
```
(consistency nit) All the above functions have a blank line separating them, like between ReduceMax_noop_axes_input_initializer_opset_18 and ReduceMax_empty_axes_input_initializer_opset_18. #Resolved

File: onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc (hunk 1 above)
Comment (naomiOvad) [reply onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc]: Fixed — removed CPU availability checks and updated all occurrences. Thanks!

File: onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc (hunk 3 above)
Comment (naomiOvad) [reply onnxruntime/test/providers/cpu/reduction/reduction_ops_test.cc:6134]: Fixed, thanks!

**Comment by naomiOvad** [comment]
I see that the Linux x64 training CI is consistently failing.
I'm currently investigating whether this is related to my change and trying to reproduce it locally.

**Comment by yuslepukhin** [comment]
1: [ RUN      ] GradientCheckerTest.AddGrad
1: 2025-12-19 01:55:18.034439132 [E:onnxruntime:Add, sequential_executor.cc:572 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'node1_Grad/Reshape_4' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:45 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{2,3,2,3}, requested shape:{}

**Comment by naomiOvad** [comment]
I fixed the handling of axes when they are provided as an input tensor. Previously this case was not handled, so axes were incorrectly treated as empty , triggering the noop_with_empty_axes path and leading to the invalid reshape in GradientCheckerTest.AddGrad.

File: onnxruntime/core/providers/cpu/reduction/reduction_ops.cc [hunk 4]
```diff
@@ -920,25 +914,84 @@ bool check_and_reduce_empty_set_input(OpKernelContext* ctx, const gsl::span<cons
...
+      y[i] = agg.get_value();
+    }
+  }
+}
+
+// Returns the effective reduction axes.
+// If an axes input tensor is provided, it takes precedence over the axes attribute.
+inline gsl::span<const int64_t> GetEffectiveAxes(
+    OpKernelContext* ctx,
+    const gsl::span<const int64_t>& axes_attr,
```
Comment (yuslepukhin) [inline onnxruntime/core/providers/cpu/reduction/reduction_ops.cc]: > const gsl::span<const int64_t>& [](http://example.com/codeflow?start=3&length=32)

Coding guidelines: pass spans by value

Comment (naomiOvad) [reply onnxruntime/core/providers/cpu/reduction/reduction_ops.cc]: Updated GetEffectiveAxes to pass gsl::span by value per coding guidelines.

**Review by fdwr — APPROVED** [review]
👍

**Comment by naomiOvad** [comment]
Thanks for the reviews!  
Let me know if there’s anything else I should do.

**Comment by naomiOvad** [comment]
Hi, Just checking in — I see that all checks have passed.
